### ISSUE TITLE
@testing-library/react-native useRef does not return the same type as getByTestID

### ISSUE THREAD

**Issue by kmalakoff** [callstack/react-native-testing-library#1006]
## Describe the bug

@testing-library/react-native useRef does not return the same type as getByTestID. 

The ref.current is of type "Component" instead of "ReactTestInstance".

## Expected behavior

The ref.current set by useRef should be type of "ReactTestInstance" so that it can be used in an identical manner as an element found through getByTestID

## Steps to Reproduce

Run these commands:
git clone git@github.com:kmalakoff/react-native-contains.git
cd react-native-contains
git checkout  @testing-library/react-native-issue
npm install
npm run build
npm test

You will see this assertion fails: https://github.com/kmalakoff/react-native-contains/blob/%40testing-library/react-native-issue/test/unit/native.test.native.tsx#L53

## Versions

  npmPackages:
    @testing-library/react-native: ^10.1.1 => 10.1.1 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0 => 0.69.0 
    react-test-renderer: 18.0.0 => 18.0.0

**Comment by mdjastrzebski** [comment]
I'm not sure if this is possible at all with the current setup.

Key facts:
1. RNTL renders your components using React Test Renderer (not React Native renderer!). So it's a bit different environment compared to code running on device/simulator. There are various limitations to it, and according to [this old thread](https://github.com/facebook/jest/issues/5462#issuecomment-363532494) it does not support `refs`. 
2. All queries (getByXxx, queryByXxx) return `ReactTestInstance`. This is the object that we get from `TestRenderer.create` method.

**Comment by kmalakoff** [comment]
Understood. Thanks for letting me know

**Comment by mdjastrzebski** [comment]
@kmalakoff I've recently stumbled upon [createMockNode](https://reactjs.org/docs/test-renderer.html#ideas) function in React Test Renderer. We expose this through our `render` function as `createMockNode` option. Maybe you can use that to implement the test you want.
