### ISSUE TITLE
Jest:   expect(getByText('content')).not.toBeDefined(); throw exception

### ISSUE THREAD

**Issue by FilipMessa** [callstack/react-native-testing-library#103]
I would expect that something like this will be possible.
In my test scenario at first I add text `content` to the TextInput, then I test if text content exists, then I click on the delete button and I would like to test if input will be clear.

```expect(getByText('content')).not.toBeDefined();```

but I throw the exception with this  **No instances found**

**Comment by thymikee** [comment]
All `getBy*` throw when no components were found matching the predicate. If you want to assert that the component is not there use `queryBy*` APIs that return `null` when nothing is found:
```js
expect(queryByText('content')).not.toBeDefined();
expect(queryByText('other content')).toBeNull();
```

It's all documented:
- getByText: https://github.com/callstack/react-native-testing-library/blob/master/docs/API.md#getbytext-text-string--regexp
- query APIs: https://github.com/callstack/react-native-testing-library/blob/master/docs/API.md#query-apis
