### ISSUE TITLE
Unable to Test components with re-exports

### ISSUE THREAD

**Issue by NishanthVemula** [callstack/react-native-testing-library#1035]
### Component Folder Structure

| Component File Path | Description of Component |
| - | - |
| src/BaseComponents/BaseComponent1.tsx | exports class BaseComponent1 |
| src/BaseComponents/BaseComponent2.tsx | exports class BaseComponent2 |
| src/BaseComponents/index.tsx | re-exports classes BaseComponent1 and BaseComponent1 |

### FinalComponent

**FilePath:** src/Components/FinalComponent1.tsx

Case 1: Importing BaseComponent1 and BaseComponent2 directly from individual files
Tests work as expected

Case 2: Importing BaseComponent1 and BaseComponent2 from src/BaseComponents/index.tsx
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `FinalComponent1`.
```

## Expected behavior

Case 2 should work as good as Case 1

## Steps to Reproduce

Could be derived from Bug Description

## Versions

    @testing-library/react-native: ^11.0.0 => 11.0.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-test-renderer: 17.0.2 => 17.0.2

**Comment by mdjastrzebski** [comment]
Closing as this seems not be connected with RNTL but rather OP setup.

@NishanthVemula based on your error message I would double check if you use proper imports. Seems like you might be using default import for a module that has named exports. 

In case you believe that this is indeed RNTL issue, please create a minimal repro repository, based on our `examples/basic` example and post it on this issue.
