### ISSUE TITLE
getByText doesn't find texts inside ScrollView (possibly others?)

### ISSUE THREAD

**Issue by lgandecki** [callstack/react-native-testing-library#106]
Took this code straight from your examples, but instead of looking for testId, I tried to look for the text:

```javascript
  const {  getByText } = render(
    <ScrollView testID="scroll-view">
      <Text>XD</Text>
    </ScrollView>
  );

  getByText("XD");
```

Changing ScrollView to View makes it pass.

Am I doing something wrong?

**Comment by thymikee** [comment]
Which version of the lib? What does debug returned from render show?

**Comment by lgandecki** [comment]
"react-native-testing-library": "^1.5.0",

Seems like 
```javascript
debug.shallow(    <ScrollView testID="scroll-view">
      <Text>XD</Text>
    </ScrollView>)
```
doesn't show anything?

 But I have a different component that I tried to test:

```javascript
export default class HomeScreen extends React.Component {


  render() {
    return (
        
      <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
        <Text>MyText</Text>
      </ScrollView>
    );
  }
}
```
this is what I see in the debug:

```
      <ScrollViewMock
        contentContainerStyle={
          Object {
            "paddingTop": 30,
          }
        }
        style={
          Object {
            "backgroundColor": "#fff",
            "flex": 1,
          }
        }
      >
        <Component>
          MyText
        </Component>
      </ScrollViewMock>
```

If I switch ScrollView to View, test passes, and I get :

```
      <Component
        contentContainerStyle={
          Object {
            "paddingTop": 30,
          }
        }
        style={
          Object {
            "backgroundColor": "#fff",
            "flex": 1,
          }
        }
      >
        <Component>
          MyText
        </Component>
      </Component>

```

in the debug


I import things from react-native:
```javascript
import { Platform, ScrollView, StyleSheet, Text, View, Button } from "react-native";
```


I do use expo though, not sure if that changes things?

**Comment by thymikee** [comment]
Unfortunately it changes things. Expo does something weird to their components in test env which I didn't have time to debug. See: https://github.com/callstack/react-native-testing-library/issues/68

**Comment by lgandecki** [comment]
Ok. I'd suggest stating this in bold in the README.md, that there is no support for expo. :)

Thanks!

**Comment by thymikee** [comment]
Happy to accept PR with a note on that. However I'd say this is a temporary bug on Expo side and I expect it to be fixed somewhat soon, because it also affect react-test-renderer.
