### ISSUE TITLE
Wrap render calls with act() for better Hooks integration

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#111]
Hooks work fine even without it, but you'll likely need to add asynchrony to your code. With `act()` you'll be able to achieve the same results in synchronous manner.

See: https://reactjs.org/blog/2019/02/06/react-v16.8.0.html#testing-hooks

**Comment by ccfz** [comment]
It would be great if `update` is also be wrapped with act().

**Comment by Esemesek** [comment]
@ccfz Would appreciate a PR with an example test for this functionality.
