### ISSUE TITLE
jest version compatibility

### ISSUE THREAD

**Issue by henrymoulton** [callstack/react-native-testing-library#1117]
## Ask your Question

I noticed in the React Native Community TypeScript Template it uses jest 26, and the latest version of this library asks to upgrade to jest 28. 

What is the officially supported version of Jest by React Native?

**Comment by mdjastrzebski** [comment]
@henrymoulton afaik RN and Jest do not have such thing as supported version mapping, so you should be able to update Jest version independently of RN. 

@thymikee maybe you have some more info why Typescript Template, but also [RN template](https://github.com/facebook/react-native/blob/main/template/package.json) still uses Jest `26.6.x`?

**Comment by thymikee** [comment]
Simply because no-one sent a PR to upgrade yet :D RN internally upgraded Jest to 29 recently, so it should be fairly straightforward to upgrade, without being blocked by internal Meta stuff.

**Comment by thymikee** [comment]
I'll close this issue, as it's not relevant to the RNTL, but happy to keep the conversation going :)
