### ISSUE TITLE
How to test children props as a function?

### ISSUE THREAD

**Issue by ethantran** [callstack/react-native-testing-library#112]
I get an error 

```    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.``` 

when I test a component that looks something like this 

```
<View>{this.props.children({ status: this.state.status })}</View>
```

**Comment by ethantran** [comment]
Nevermind. It turns out that I had to mock components generated from https://github.com/kristerkari/react-native-svg-transformer.

**Comment by VirtualDOMinic** [comment]
@ethantran Do you remember if you needed to do anything in addition to what's described in the [svg-transformer docs](https://github.com/kristerkari/react-native-svg-transformer#usage-with-jest)? 

I can't get my tests to work on a component containing an SVG, and get the same error even after adding what's described in the `usage-with-jest` section
