### ISSUE TITLE
Do you not need afterEach(cleanup)

### ISSUE THREAD

**Issue by janhesters** [callstack/react-native-testing-library#114]
I noticed that this library doesn't expose a `cleanup` function like react-testing-library does. Is this intentional? Could you clear this issue up in the readme?

**Comment by thymikee** [comment]
We don't interact with the DOM so there's nothing to clean up, it's not necessary.

**Comment by janhesters** [comment]
@thymikee Thank you, I didn't know that 😊

**Comment by thymikee** [comment]
Gonna close it then. Feel free to add a note to the docs if that's something not obvious for users of `react-testing-library` :)

**Comment by janhesters** [comment]
@thymikee [Done](https://github.com/callstack/react-native-testing-library/pull/115)
