### ISSUE TITLE
Native Base <Content/> type is not rendered

### ISSUE THREAD

**Issue by oriharel** [callstack/react-native-testing-library#118]
Hi, 
I have this component:

```
import {
	Container,
	Content,
	Text,
} from 'native-base';


<Container style={styles.container}>			
	<Content padder>
		<Text testID={'emptyCasesList'}>Cases list is empty</Text>
	</Content>
</Container>
```

But the test can't find the '`emptyCasesList`' element. when I run debug.deep, I can't see the `<Content/>` element nor the `<Text>`.
BUT - when I remove the `<Content/>` element (leaving just the `<Text/>`), test passes and I see the `<Text/>` element.
If the answer is something like "_NativeBase is mocking the_ `<Content/>` _in tests_" - could you please elaborate further?

Thanks.

**Comment by thymikee** [comment]
Can you post a repro we can debug? Otherwise it's not actionable

**Comment by pedrohbtp** [comment]
First, thank you very much for the great library!
I have the same issue. The inside of <Content> is generated when running the code on the phone or emulator, but when trying to test it does not show up.
 The Code below should illustrate it. Really could not figure out why that is the case

```javascript
import { render } from 'react-native-testing-library';
import {
  Content, Container, Text
} from 'native-base';


class App extends React.Component {

  render() {
    return (
      <Container>
        <Content>
          <Text testID="textId">Hello</Text>
        </Content>
      </Container>
    );
  }
}

describe('Testing Content', () => {
  const { queryByTestId } = render(<App />)
  it('renders text inside content', () => {
    expect(queryByTestId('textId')).not.toBeNull()
  });

})
```

The versions of packages I am using are the following:

`"expo": "^32.0.0",
"react": "16.5.0",
"native-base": "^2.12.1",
"jest-expo": "^32.0.0",
"react-native-testing-library": "^1.7.0"`

**Comment by pedrohbtp** [comment]
@oriharel , have you have any luck with the issue?

@thymikee, would there be any way of helping you with this?

Thanks

**Comment by thymikee** [comment]
Sure, as soon as anybody provides a repro I can download :)

**Comment by pedrohbtp** [comment]
@thymikee , thank you for the reply and I apologize for the misunderstanding.

I created the following repository to reproduce the behavior:
https://github.com/pedrohbtp/rntl-content-bug

**Comment by thymikee** [comment]
Hey! I looked into the example and it indeed doesn't work. So I jumped into `native-base` internals and found this: https://github.com/GeekyAnts/NativeBase/blob/65f0bc7ff53b28099d177813d2b33ffd987cadcd/src/basic/Content.js#L90-L95

The `Content` component uses `react-native-keyboard-aware-scroll-view` under the hood, which is just not mocked properly. I can see it's even named `KeyboardAwareScrollViewMock`, not sure where it comes from (maybe `jest-expo`? I'll leave that to you to investigate).

Here's the diff that fixes your tests (of course this mock is very basic, feel free to make it closer to the original and send a PR to the library maintainers, or use a better one if available already):

```diff
diff --git a/App.test.js b/App.test.js
index 08bb08d..c02713e 100644
--- a/App.test.js
+++ b/App.test.js
@@ -4,6 +4,10 @@ import {
     Content, Container, Text
 } from 'native-base';

+jest.mock('react-native-keyboard-aware-scroll-view', () => {
+    const KeyboardAwareScrollView = ({ children }) => children;
+    return { KeyboardAwareScrollView };
+});

 class App extends React.Component {

@@ -34,4 +38,4 @@ describe('Testing Content', () => {
         expect(queryByTestId('textIdInside')).not.toBeNull()
     });

-})
\ No newline at end of file
+})

```

Closing, as that's not an issue with this library, but with mocking in general.
