### ISSUE TITLE
Feature: improved `findAll` method

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1181]
## Describe the Feature
We currently use [`ReactTestInstance.findAll`](https://github.com/facebook/react/blob/9ecf84ed7ffb21c8746ecf227209c050d99393cd/packages/react-test-renderer/src/ReactTestRenderer.js#L402) method in order to traverse element tree. This is a basic tree walking algorithm that starts at the root and traverses recursively to the children. 

There is one major issue with the current method: for query predicates that inspect all descendants (e.g. concat all string content) there is no easy way to find only the deepest element matching given predicate.

```
<Text testID="outer">
  <Text testID="inner">
    Hello.
  </Text>
</Text>
```

When using a predict that will concat all nested string contents, then both outer and inner text will be matched. 

## Possible Implementations
This should be a function, with similar signature:

```ts
function findAll(element: ReactTestInstance, predicate: (element: ReactTestInstance) => boolean, options: FindAllOptions)
```

* it should work by traversing tree top-down from root (as current algorithm)
* but it should be inspecting the elements on its way back, so that the deepest element is matched first
* having information about deeper element having been matched inside given branch it would prevent it's ancestor elements also getting match
* this should be an optional behavior controlled by option passed inside `options` argument. Proposed initial option name: `deepestOnly` (default `false`)
* it might be worth considering adding some additional argument to `predicate` callback to facilitate this

## Applications

* This would be an internal API used by queries.
* It could allow us to improve some existing non-trivial queries, e.g. `*ByText` or `*ByRole` with `name` option

**Comment by rparthas** [comment]
I am interested to work on it.

**Comment by mdjastrzebski** [comment]
Go ahead @rparthas

**Comment by mdjastrzebski** [comment]
@rparthas I wanted to check if you still plan to contribute this feature?
