### ISSUE TITLE
Feature: missing `TextMatcherOptions` for `*ByLabelText` and `*ByHintText` queries

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1182]
## Describe the Feature
All basic attribute matcher queries (`*ByText`, `*ByTestId`, ...) accept `TextMatcherOptions` (`exact` and `normalizer`). However `*ByLabelText` and `*ByHintText` do not. 

The goal of this task is to add the same options to that queries.

## Possible Implementations
This should be relatively straightforward copying of code from e.g. `*ByTestId` and applying it to *ByLabelText` and `*ByHintText` queries.

**Comment by ShaswatPrabhat** [comment]
I can give it a shot @mdjastrzebski

**Comment by mdjastrzebski** [comment]
Go ahead @ShaswatPrabhat

**Comment by ShaswatPrabhat** [comment]
Have added the changes (here)[https://github.com/callstack/react-native-testing-library/pull/1193] @mdjastrzebski 

But two tests are failing for me.  Can you please spare some time to help me with the same?

Thanks in advance.

**Comment by mdjastrzebski** [comment]
Closing as done. @ShaswatPrabhat thanks for implementing this feature.
