### ISSUE TITLE
Typing of `act` broken

### ISSUE THREAD

**Issue by mstykow** [callstack/react-native-testing-library#1207]
## Describe the bug

The `act` function exported by `@testing-library/react-native` is always of type `(callback: () => void) => void`. However, the underlying function coming from react-test-renderer also has overloads for promises which are incorrectly suppressed.

This error in typing leads to linter errors when one tries to pass promise-returning callbacks to `act` or tries to await a promise-returning `act`.

## Expected behavior

The `act` function should have the same typing as the underlying function from react-test-renderer.

## Steps to Reproduce

The following snippet will produce linter errors such as [this one](https://typescript-eslint.io/rules/no-misused-promises/), depending on one's linter configuration.
```
import { act } from '@testing-library/react-native'

await act(async () => {
  await Promise.resolve();
});
```

## Versions

    @testing-library/react-native: ^11.3.0 => 11.3.0 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-test-renderer: ^18.2.0 => 18.2.0

**Comment by mdjastrzebski** [comment]
@mstykow Ciule you submit a PR for that?

**Comment by mstykow** [comment]
@mdjastrzebski the problem seems to be here in the flow typings: https://github.com/callstack/react-native-testing-library/blob/main/typings/index.flow.js#L421

Why are you using flow at all when your library is mostly TypeScript? Ideally we'd just forward the correct TypeScript type instead of overriding it with these flow definitions.

**Comment by mstykow** [comment]
Never mind, I misunderstood something. I see the problem now is in the actual `act.ts` file.

**Comment by mstykow** [comment]
OK, I can open a PR but it seems I don't have permissions to create a branch.

**Comment by AugustinLF** [comment]
> OK, I can open a PR but it seems I don't have permissions to create a branch.

You'll need to fork the repo and create a branch there. You'll then be able to create a PR back to this repo from yours.

Please modify both the TS and flow types :)

**Comment by mdjastrzebski** [comment]
@mstykow I've closed your PR without merging as it worked by overriding the `act` type definition instead of actually verifying the related types.

I am curious what is your use cases for needing explicit `act` access in your tests. RNTL should already wrap all relevant calls to React/React Test Render with `act` when needed.

BTW from your deps it seems that you have a mismatch between `react` and `react-test-renderer` versions. They need to use the same version, otherwise weird things might happen.

```
@testing-library/react-native: ^11.3.0 => 11.3.0 
react: 18.0.0 => 18.0.0 
react-native: 0.69.6 => 0.69.6 
react-test-renderer: ^18.2.0 => 18.2.0
```

**Comment by mdjastrzebski** [comment]
@AugustinLF would you like to work on improving the `act` typings?

**Comment by AugustinLF** [comment]
I'm struggling with time right now, got a lot going on at work, so won't be able to do that right now 😞  (and I'm not personally impacted because we use the types of RTL's act).
