### ISSUE TITLE
Log screen.debug() if waitFor gets a timeout

### ISSUE THREAD

**Issue by oatsoda** [callstack/react-native-testing-library#1223]
It would be great if failures in `waitFor` output the `screen.debug()` on failure so that the component output is written to the console on failures.

In the [same way it was done in the this library](https://github.com/testing-library/dom-testing-library/issues/559) - though not sure how you can capture the component output in this case.

**Comment by mdjastrzebski** [comment]
@oatsoda looks like a good idea. Would you be able to submit a PR for that?

**Comment by pierrezimmermannbam** [comment]
I'm not sure adding this to waitFor is the best solution. There are cases where this wouldn't be relevant, for instance when expecting some function has been called or when testing hooks. I think this would be useful only when using queries so maybe this should be called when getBy queries fail instead ? A potential issue with this approach is it wouldn't work when checking that an element is not present using a queryBy query but that wouldn't be covered by waitFor either. This could be added when waitForElementToBeRemoved timeouts though. Also keeping the error at query level would allow further customization based on the predicate

**Comment by mdjastrzebski** [comment]
The way it is implemented in DTL looks like as @oatsoda described, i.e. waitFor shows debug() after failed waitFor calls. So concerns rised by are valid. Maybe we can just update the docs to suggest users to manually call 'screen.debug()' in onTimeout callback?

**Comment by mdjastrzebski** [comment]
Replaced by #1268.
