### ISSUE TITLE
Please add `TextMatch` functions to the RNTL API

### ISSUE THREAD

**Issue by matthew-dean** [callstack/react-native-testing-library#1242]
## Describe the Feature
In the Core API, getBy* [allows a function to be passed in to test individual elements](https://testing-library.com/docs/queries/about#textmatch). This implementation for React Native only allows strings / regex.

## Possible Implementations
Align with the Core API

**Comment by mdjastrzebski** [comment]
@matthew-dean could you explain your use case, so that we can analyse what would be the best way to solve it? Otherwise, I will have to close this issue as missing reason for such addition.

**Comment by mdjastrzebski** [comment]
Closing as the request is missing a convincing argumentation for including such API.
