### ISSUE TITLE
fireEvent.press doesn't return a GestureResponderEvent 

### ISSUE THREAD

**Issue by Rolchau** [callstack/react-native-testing-library#1254]
## Describe the bug
Hi, I am trying to test an onPress event that uses the currentTarget from the GestureResponderEvent (Its setting some positions from the clicked element), but when calling fireEvent.press on said element, the test fails because the event is undefined. 

## Expected behavior
Expected fireEvent to return a GestureResponderEvent so I can use measure on the currentTarget.

## Steps to Reproduce
Simplified test that reproduces the error: 

```jsx
test('this fails', () => {
  const { getByTestId } = render(
    <Pressable testID="pressable" onPress={(elm) => console.log(elm.currentTarget.measure)} />,
    {}
  );
  fireEvent.press(getByTestId('pressable'));
});
```

## Versions

 npmPackages:
    @testing-library/react-native: ^11.4.0 => 11.5.0
    react: 18.2.0 => 18.2.0
    react-native: 0.70.5 => 0.70.5
    react-test-renderer: ^18.2.0 => 18.2.0

**Comment by mdjastrzebski** [comment]
@Rolchau this is a known issue, that our `fireEvent` implementation does not provide event objects by default. We plan to fix it in the future, however the subject requires a lot of research to do it properly. For more details you can check #714.

As a recommended workaround, you can pass the required object by yourself:
```ts
const event = ... // construct whatever object you need
fireEvent.press((getByTestId('pressable'), event);
```

**Comment by Rolchau** [comment]
@mdjastrzebski ah ok, thanks for the fast answer.
