### ISSUE TITLE
Typescript act() got warning `'await' has no effect on the type of this expression.`

### ISSUE THREAD

**Issue by qaynam** [callstack/react-native-testing-library#1276]
## Describe the bug

when i use act with typescript , got warning like 👇

<img width="611" alt="image" src="https://user-images.githubusercontent.com/33139713/211142113-f8a5c3b1-4bec-4cbe-b603-6011b490383c.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/33139713/211142103-e119d109-809e-4a94-8222-749d5b677d16.png">

## Steps to Reproduce

`@testing-library/react-native/build/act.d.ts`

```diff
declare global {
    var IS_REACT_ACT_ENVIRONMENT: boolean | undefined;
}
declare function setIsReactActEnvironment(isReactActEnvironment: boolean | undefined): void;
declare function getIsReactActEnvironment(): boolean | undefined;
- declare const act: (callback: () => void) => void;
+ declare const act: <T>(callback: () => T) => T;
export default act;
export { setIsReactActEnvironment as setReactActEnvironment, getIsReactActEnvironment, };

```

## Versions

<img width="388" alt="image" src="https://user-images.githubusercontent.com/33139713/211142204-6295ea0a-f5c5-4c36-89bc-52fe985830ad.png">

**Comment by mdjastrzebski** [comment]
Looking at `@types/react-test-render` theirs `act` has following type:
```
export function act(callback: () => Promise<VoidOrUndefinedOnly>): Promise<undefined>;
```
As far as I understand the intention of async `act` is to allow for waiting for `Promise` returned by `callback` to resolve, but not to use it's return value in any way. We could actually tweak our typings to match `@types/react-test-render` ones.

RTL does hits in the [following way](https://github.com/testing-library/react-testing-library/blob/c43512a9271f5738496a3ed49aed7e3e9dad071c/types/index.d.ts#L161):
```ts
/**
 * Simply calls ReactDOMTestUtils.act(cb)
 * If that's not available (older version of react) then it
 * simply calls the given callback immediately
 */
export const act: typeof reactAct extends undefined
  ? (callback: () => void) => void
  : typeof reactAct
```

@qaynam Would such solution satisfy your use case?

**Comment by qaynam** [comment]
> ```diff
> declare const act: <T>(callback: () => T) => T
> ```

You're right, I was in a bit of a hurry and wrote it down just the right way.
But I guess the act function needs to be await in any case, otherwise jest will warn me.

so maybe like this? 👇

```ts
export async function act(callback: () => Promise<VoidOrUndefinedOnly>): Promise<undefined>;
```

**Comment by trajano** [comment]
I'm not sure how you'd declare it in the act.ts file but the generated act.d.ts file should have these two lines
```
declare const act: (callback: () => void) => void;
declare const act: (callback: () => Promise<VoidOrUndefinedOnly>): Promise<undefined>;
```

**Comment by trajano** [comment]
I referenced this bug in https://stackoverflow.com/questions/64848604/how-to-resolve-act-in-useeffect/71949404#71949404
