### ISSUE TITLE
Why is "useEffect" being called twice when using "renderHook"?

### ISSUE THREAD

**Issue by akkadaya** [callstack/react-native-testing-library#1277]
After replacing `@testing-library/react-hooks` with `@testing-library/react-native` because of [React 18 support](https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support).
`useEffect` call times assertion tests started failing! when printing the second call's callback function I noticed it is from `renderHook`'s  `RenderHookResult` object.
- Does `renderHook` from `@testing-library/react-native` call `useEffect`? 
- is there any documentation regarding this different behaviour?

Bonus question:
- Is there a point of asserting how many times `useEffect` has been called?

Test:
```typescript
let useEffectSpy: jest.SpyInstance
useEffectSpy = jest.spyOn(React, 'useEffect')

expect(React.useEffect).toHaveBeenCalledTimes(1)  // fails

// console.log the first argument of the second useEffect call 
console.log(useEffectSpy.mock.calls[1][0].toString())
```
`console.log` result:
```
() => {result.current = renderResult;}
```

**Comment by pierrezimmermannbam** [comment]
The renderhook from RNTL uses a useEffect internally to update the result ref (see https://github.com/callstack/react-native-testing-library/blob/main/src/renderHook.tsx#L38) while @testing-library/react-hooks does not. I'm not sure why we use useEffect at all here, we could just inline this call it would also work but really that shouldn't make a difference for end users. 

This behavior isn't documented as it's very unlikely that it has any effects on user tests, in fact I never thought this change would break some tests.

I'd need to see more in detail the code that you're testing but imo checking how many times we have called useEffect isn't a good pattern: it's too focused on implementation details so it doesn't really test that the feature is working and it's very fragile so I'd strongly advise against that, but then again I don't have much details here on what it is you're testing. Could you elaborate on why you are checking the number of useEffect calls ?

**Comment by mdjastrzebski** [comment]
@pierrezimmermannbam the reason we use `useEffect` is our implementation is based on [RTL's `renderHook`](function renderHook(renderCallback, options = {}) {) which also uses that approach.

Maybe this is related to React 18 behavior of running useEffects twice in strict mode in development: https://blog.bitsrc.io/react-v18-0-useeffect-bug-why-do-effects-run-twice-39babecede93

**Comment by mdjastrzebski** [comment]
@akkadaya addressing your question about asserting number of useEffect calls: this is not a good practice. As your tests should validate the external behaviour of the hook, rather than what happens inside.

**Comment by akkadaya** [comment]
G'day @pierrezimmermannbam, just some old tests in the code were asserting `useEffect` has been called once when rendering the component. I couldn't find any good reason to assert that, thus my Bonus Question.
