### ISSUE TITLE
[Bug]: act executed state batch updates incorrectly

### ISSUE THREAD

**Issue by Kirangaira** [callstack/react-native-testing-library#1284]
## Describe the bug

Version: 11.5.0

## Steps to reproduce:

1. Created a simple count down timer, that starts from 30 and decrements every second.

CountDownTimer.tsx

```
import React, { useEffect, useState } from 'react';
import { Text } from 'react-native';

function CountdownTimer() {
  const [seconds, setSeconds] = useState(30);

  useEffect(() => {
    const interval = setInterval(() => {
      if (seconds > 0) {
        setSeconds(seconds - 1);
      } else {
        clearInterval(interval);
      }
    }, 1000);
    return () => clearInterval(interval);
  }, [seconds]);

  return <Text>{seconds}</Text>;
}

export default CountdownTimer;

```
2. Testing it should become 0 after 30 s.

CountDownTimer.test.tsx

```
import React from 'react';
import { act, render } from '@testing-library/react-native';
import CountdownTimer from '../CountdownTimer';

describe('CountdownTimer', () => {
  it('stops at 0', () => {
    jest.useFakeTimers();
    const { getByText } = render(<CountdownTimer />);
    act(() => {
      jest.advanceTimersByTime(30000);
    });
    expect(getByText('0').props.children).toBe(0);
    jest.useRealTimers();
  });
});
```
This was working fine when I was using react version "17.0.2", when I upgraded to react "18.1.0", this broke. The reason is that the seconds don't get decremented in setInterval calls, basically, all the setInterval calls are executed first, and then the component re-renders in the test. So the value of seconds remains 29 only. Just one state happens at the end after the timers have advanced.

### Expected behavior
The act should trigger re-render multiple times in setInterval, not once.
In react version below 18, act triggers re-render for each setState in setInterval.

### Actual behavior
act triggering re-render only once in setInterval.

### Additional context
React Version : 18.1.0
New Architecture not enabled.

### Environment
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm

**Comment by mdjastrzebski** [comment]
@Kirangaira Your code seems to have bug that causes the behavior:

Test works fine when replacing this:
```ts
 setSeconds(seconds - 1);
```

with that:
```ts
 setSeconds(s => s - 1);
```

Using this for of setter is suggested best practice with React, as it avoid stale values. Otherwise, this might be due to React coalescing all your set states due to [automatic batching](https://reactjs.org/blog/2022/03/29/react-v18.html#new-feature-automatic-batching) feature.
