### ISSUE TITLE
More helpers for testing hooks

### ISSUE THREAD

**Issue by hyochan** [callstack/react-native-testing-library#129]
## Ask your Question
I'd like to know how to test `context-api` with `react-native-testing-library`.
It is supported int `react-testing-library` as in [#296](https://github.com/kentcdodds/react-testing-library/pull/296). Also, [useContext] could be covered which was addressed in [#283](https://github.com/kentcdodds/react-testing-library/issues/283).

I searched for [api doc](https://callstack.github.io/react-native-testing-library/docs/api) and I am not seeing any use-case for this one.

**Comment by thymikee** [comment]
No, we don't have that.

**Comment by hyochan** [comment]
I'd like to request feature for better `react-hook` support such as `useContext`, `useRef`.

**Comment by thymikee** [comment]
If you are interested in testing a custom hook, check out [react-hooks-testing-library](https://github.com/mpeyper/react-hooks-testing-library).
