### ISSUE TITLE
Should the custom jest preset be deprecated?

### ISSUE THREAD

**Issue by roryabraham** [callstack/react-native-testing-library#1307]
## Ask your Question

I see that the [custom jest preset](https://github.com/callstack/react-native-testing-library#custom-jest-preset) which does not override promise was added in response to [this upstream issue](https://github.com/facebook/react-native/issues/29303). Now that that issue has been resolved upstream in https://github.com/facebook/react-native/commit/f1fdc8b9b636e010ae5d5e737fc81a8da8f536d4 and released in [v0.71.2](https://github.com/facebook/react-native/releases/tag/v0.71.2), should we update documentation in this repo to deprecate the custom jest preset and only recommend it to developers using ["modern fake timers"](https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers) _and_ RN < `0.71.2` ?

**Comment by mdjastrzebski** [comment]
@roryabraham that's a good question. We will have to review it. However, it seems fairly low prio, so it might take a will to handle it.

**Comment by pierrezimmermannbam** [comment]
Oh I hadn't seen that promise was no longer polyfilled that's great news! I think it's worth mentioning in the readme that it's no longer needed for RN >= 0.71.2, I'll open a PR to update the readme

**Comment by thymikee** [comment]
I wouldn't deprecate it, but treat as a proxy to original preset. When we need to add something custom, we can do it without much work from the users

**Comment by mdjastrzebski** [comment]
Resolved in #1316
