### ISSUE TITLE
Testing eventListener in `componentDidMount`

### ISSUE THREAD

**Issue by tobiastimm** [callstack/react-native-testing-library#131]
## Testing eventListener in `componentDidMount`

Hey folks,

I have a `react-native` component that is listening to `Linking` url event. How would I fire that Event with `react-native-testing-library`?

Example:

```js
import React, { PureComponent } from 'react';
import { View, Text, Linking, ActivityIndicator } from 'react-native';
import SafariView from 'react-native-safari-view';

class WebAuthView extends Component<Props, State> {
  componentDidMount() {
        Linking.addEventListener('url', this.handleAuthUrl);
        SafariView.addEventListener('onDismiss', this.handleDismiss);
   }

   componentWillUnmount() {
       Linking.removeEventListener('url', this.handleAuthUrl);
       SafariView.removeEventListener('onDismiss', this.handleDismiss);
   }

   handleAuthUrl = ({url}) => {
     // Implementation goes here
   }

   render() {
     // ....
   }
}
```

**Comment by thymikee** [comment]
This may be tricky, as you'd need to mock `Linking` in a way that allows you to call e.g. `emit('url', {url})`, mock `Linking.addEventListener` in a way that allows you to listen to such calls.

**Comment by tobiastimm** [comment]
@thymikee thanks! I will ask the `react-native` folks if there is a way to test that, because it looks like there is no builtin way for linking to emit that event

**Comment by dcalhoun** [comment]
For posterity, it looks like @tobiastimm created facebook/react-native#23990, but it was closed due to lack of adhering to the project's issue template. 

The issue did include a link the StackOverflow question, which I [posted my current solution](https://stackoverflow.com/a/58000966/378228) to this problem. Hopefully anyone coming across this finds it helpful.
