### ISSUE TITLE
`findByText` is giving me error when I run the test suites

### ISSUE THREAD

**Issue by Saad-Bashar** [callstack/react-native-testing-library#1318]
## Ask your Question

Coming from this [link](https://github.com/lucasferreira/react-native-flash-message/issues/242). I added `findByText` and the test works perfectly. However when I run all of my test suites together it throws out the following error and the tests are failing as they are not run further.
 
<img width="750" alt="Screenshot 2023-02-15 at 7 51 23 AM" src="https://user-images.githubusercontent.com/13269141/218934406-41749b90-edba-451c-b793-ac7d09add8fc.png">

Most probably the versions of all of the test libraries in my project are the cause of this.My react version is 17 and RN version is 0.67. Here are the packages related to testing in my project. 

```
"@testing-library/jest-native": "^4.0.11",
"@testing-library/react-native": "^11.0.0",
"jest": "^26.6.3",
"jest-circus": "^26.6.3",
"jest-cli": "^26.6.3",
"jest-enzyme": "^7.1.2",
"jest-html-reporter": "^3.3.0",
"jest-junit": "^12.0.0",
"jsdom": "11.11.0",
"react-dom": "^17.0.1",
"react-test-renderer": "17.0.2",
```

I have added `findByText` in just one of the test files. The test looks like the following:

```
import * as React from 'react';
import {fireEvent, render, screen} from '@testing-library/react-native';
import {FeedbackScreen} from './FeedbackScreen';

test('should return error message if user presses submit button without entering any text', () => {
  render(<FeedbackScreen />);

  fireEvent.press(screen.getByText('Submit'));

  expect(
    screen.findByText('Please enter feedback before submitting!'),
  ).toBeTruthy();
});
```

Any guide on this? Thanks a lot!

**Comment by mdjastrzebski** [comment]
@Saad-Bashar you are missing `async`/`await` for your test:

```ts
import * as React from 'react';
import {fireEvent, render, screen} from '@testing-library/react-native';
import {FeedbackScreen} from './FeedbackScreen';

test('should return error message if user presses submit button without entering any text', async () => {
  render(<FeedbackScreen />);

  fireEvent.press(screen.getByText('Submit'));

  expect(
    await screen.findByText('Please enter feedback before submitting!'),
  ).toBeTruthy();
});
```

**Comment by Saad-Bashar** [comment]
Ah, my bad! Again thanks a lot @mdjastrzebski!
