### ISSUE TITLE
toBeOnTheScreen doesn't work with v12.0.0-rc.0

### ISSUE THREAD

**Issue by pierrezimmermannbam** [callstack/react-native-testing-library#1338]
## Describe the bug

When using `toBeOnTheScreen` matcher from jest-native, we get an error because we use `screen.container` which has been removed from v12.

## Expected behavior

It should not throw

## Steps to Reproduce

Any test using `toBeOnTheScreen` matcher will fail

## Versions

v12.0.rc.0

**Comment by pierrezimmermannbam** [comment]
We could release a new version of jest-native but it should either have RNTL v12 as peer dep, which may not be optimal because it's still a rc or be compatible with v12 and prior versions by trying to use both `container` and `UNSAFE_root` or `root`.

I feel like RNTL should be a peer dep of jest-native so I like the first option, we could also release a RC for jest-native and make it stable once RNTL version is stable.

Another option would be to keep `container` for now and have it log a deprecation warning but we'd still need to release a new version of jest-native at some point.

@mdjastrzebski wdyt?

**Comment by mdjastrzebski** [comment]
Good catch @pierrezimmermannbam: pls take a look at https://github.com/testing-library/jest-native/pull/151

**Comment by pierrezimmermannbam** [comment]
I approved your pr in jest-native. I also opened a pr #1340 to update the migration guide to mention it may require an update of jest-native

**Comment by mdjastrzebski** [comment]
Fixed in Jest Native 5.4.2.
