### ISSUE TITLE
Why won't getByTestId work on the root element here?

### ISSUE THREAD

**Issue by pipedreambomb** [callstack/react-native-testing-library#1346]
I really can't work this out and I doubt it's a bug, so I put it as a question. I have this code:

```
...
  return (
    <Animated.View testId="cell" style={[styles.cell, { backgroundColor }]}>
      <Animated.Text
        testID="cellText"
        style={[styles.contents, { textShadowColor, color: textColor }]}
      >
        {/* Show a space instead of nothing to fix flexbox issue in web view */}
        {value ?? ' '}
      </Animated.Text>
    </Animated.View>
  )
```

I have a test like this:
```
 test.each([1, 2, 3])(
    'sets backgroundColor to mapped colour for value %p',
    value => {
      // Act
      act({ value, shells: 0 })

      // Assert
      assertEqual(
        screen.getByTestId('cell').props['style']['backgroundColor'],
        colorMap[value]
      )
    }
  )
```

Edit: I should mention, `act(...)` is just rendering the component with RNTL `render` while providing it my mock Redux store.

Which gives the following output in Jest:

```
  ● Cell › sets backgroundColor to mapped colour for value 3

    Unable to find an element with testID: cell

      45 |       // Assert
      46 |       assertEqual(
    > 47 |         screen.getByTestId('cell').props['style']['backgroundColor'],
         |                ^
      48 |         colorMap[value]
      49 |       )
      50 |     }

      at features/cell/Cell.integration.test.jsx:47:16
```

I don't understand why it doesn't find the element with the test ID `cell`. I have other tests in the suite that use `getByTestId('cellText')` which get the child element with test ID `cellText` without any issues. 

What's the difference, why does one work and not the other? Also, is there something easier I can do than this to get the root element on screen without needing to give it an ID or similar?

**Comment by pipedreambomb** [comment]
Update: I've managed to find a way to [access the root element](https://callstack.github.io/react-native-testing-library/docs/api#root) but I can't seem to inspect the `backgroundColor` of it (it just doesn't seem to exist in the element I get back, even if I use `UNSAFE_root`). Is this just something I can't test for with RNTL?

**Comment by pierrezimmermannbam** [comment]
Hi @pipedreambomb! I think the issue is you're using `testId` prop but we're using the `testID` one for queries, the `testId` prop does not exist in React Native, hope this helps!

**Comment by mdjastrzebski** [comment]
In addition to what @pierrezimmermannbam wrote, I wonder why are you using `assertEquals` in your test. A recommended solution is to use specialized [Jest Native](https://github.com/testing-library/jest-native) matchers, like `expect(...).toHaveStyle({ ... }`.

**Comment by pipedreambomb** [comment]
@pierrezimmermannbam You nailed it! You can tell I haven't been coding much in the past few years... it's not my lack of comprehension of a whole new testing framework that's the problem, it's using the wrong case on a single character that got me. Starting to remember why I quit ;) Also yes, I can see why root is not preferred, now I've dug into it, but thanks for the good advice.

@mdjastrzebski That's a great call, thank you! I was actually in the process of converting my tests over from Enzyme so that `assertEqual` was old code, but I see the idiomatic approach you suggest is much nicer. I'll be using that from now on.

Thanks guys. What a helpful community <3
