### ISSUE TITLE
[1.6.1] Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by wKovacs64** [callstack/react-native-testing-library#135]
## Versions

- Expo v32.0.0
- jest-expo v32.0.0
- React v16.5.0
- NativeBase v2.12.1
- react-native-testing-library v1.6.1
- react-test-renderer v16.8.4
- OS: multiple

## Description

As of v1.6.1, I am receiving the following error when trying to test a NativeBase `Picker` using `getByText` (the same tests pass in v1.6.0):

```
Currently the only supported library to search by text is "react-native".

Cannot read property 'toString' of null
```
This only seems to happen when there are **multiple tests**.

## Reproducible Demo

https://github.com/wKovacs64/rntl-161-repro

**Comment by Chojecki** [comment]
same issue

**Comment by ryanjwessel** [comment]
Just duplicating my comment from the PR for visibility. I am running into this issue on version 7.0.1, so it appears to still be an issue.

**Comment by thymikee** [comment]
@ryanjwessel can you put up a minimal repro or submit a PR with a failing test?

**Comment by ryanjwessel** [comment]
@thymikee sure thing, I will try to. I need to extract a repro from the project I'm experiencing this in. Hope to have one for you soon.
