### ISSUE TITLE
Error: React component type is invalid in LoginScreen.test.js file. Expected a string (for built-in components) or a class/function (for composite components), but received undefined. This could be because you forgot to export the component from the file it's defined in, or there might be an issue with default and named imports. 

### ISSUE THREAD

**Issue by GittyAjay** [callstack/react-native-testing-library#1368]
### LoginScreen.test.js

```

        import { Text } from 'react-native';
        it("Login_Screen_should_render_correctly", () => {
         const { toJSON } = render(<Text >hey</Text>)                               
          expect(toJSON).toMatchSnapshot();
           expect(true).toEqual(true);
         });
```
### Error

      at printWarning (node_modules/react/cjs/react.development.js:220:30)
      at error (node_modules/react/cjs/react.development.js:196:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2215:7)
      at Object.createElement (src/components/LoginScreen/LoginScreen.test.js:7:31)

### package.json

```
    "@testing-library/react-native": "^12.0.0",
    "babel-jest": "^22.4.3",
    "detox": "^20.5.0",
    "eslint": "7.14.0",
    "jest": "^29.5.0",
    "jest-circus": "^29.5.0",
    "jest-environment-jsdom-fifteen": "^1.0.2",
    "react": "17.0.1",
    "react-native": "0.64.1",
```

### jest.config.js

```
module.exports = {
    preset: 'react-native',
    moduleNameMapper: {
        "\\.(png|jpg|svg)$": "<rootDir>/__mocks__/images.js"
    },
    setupFiles: ['./jest.setup.js'],
};
```

### jest.setup.js
```

// include this line for mocking react-native-gesture-handler
import 'react-native-gesture-handler/jestSetup';
import 'react-native-size-matters'
import 'react-native-calendar-strip';
import 'react-native-incall-manager';
import 'react-native-date-picker'
import 'react-native-location'
import React from 'react'

import 'react-native'
import 'react-native-twilio-video-webrtc';
import '@react-native-async-storage/async-storage'

jest.mock('react-native-gesture-handler', () => {
});
jest.mock('react-native-size-matters', () => ({
    moderateScale: () => jest.fn(),
    scale: () => jest.fn(),
    verticalScale: () => jest.fn()
}));
jest.mock('react-native-date-picker', () => ({

}))
jest.mock('react-native-version-number', () => ({

}))
jest.mock('react-native-fast-image', () => ({

}))
//
jest.mock('react-native', () => ({
    useWindowDimensions: () => jest.fn(),
    Platform: ({ select: () => ({}) }),
    StyleSheet: {
        create: () => ({})
    },
    NativeModules: {
        TestConnectNative: () => ({})
    },
    Dimensions: ({ get: () => ({}) }),
    AppState: {
        currentState: 'active',
        addEventListener: jest.fn(),
        removeEventListener: jest.fn(),
    },
}))
//react-native-gifted-chat'
jest.mock('react-native-elements', () => ({

}))
//react-native-stopwatch-timer'
jest.mock('react-native-incall-manager', () => { })
jest.mock('react-native-calendar-strip', () => { })
jest.mock('react-native-twilio-video-webrtc', () => { })
jest.mock('@react-native-async-storage/async-storage', () => { })
jest.mock('@react-native-firebase/messaging', () => ({}))
jest.mock('react-native-material-textfield', () => ({}))
jest.mock('react-native-device-info', () => ({
    hasNotch: () => jest.fn()
}))
jest.mock('react-native-stopwatch-timer', () => ({
}))
jest.mock('@react-native-community/checkbox', () => ({
}))
jest.mock('react-native-countdown-circle-timer', () => ({
}))
jest.mock('react-native-skeleton-placeholder', () => ({
}))
jest.mock('react-native-gifted-chat', () => ({
}))
jest.mock('react-native-image-picker', () => ({
}))
jest.mock('react-native-callkeep', () => ({
}))
jest.mock('react-native-voip-push-notification', () => ({
}))
jest.mock('react-native-location', () => ({
    configure: jest.fn(),
}))
jest.mock('react-native-version-check', () => ({
}))
jest.mock('react-native-background-geolocation', () => ({
}))
jest.mock('react-native-background-timer', () => ({
}))
jest.mock('@notifee/react-native', () => ({
}))
jest.mock('react-native-modal', () => ({
}))
jest.mock('react-native-simple-radio-button', () => ({
}))

jest.mock('react-native-event-listeners', () => ({
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    removeAllListeners: jest.fn(),
}));
jest.mock('react-native-timeline-flatlist', () => ({
}))
jest.mock('react-native-dialog', () => ({
}))
jest.mock('react-native-material-dropdown', () => ({
}))
jest.mock('react-native-picker-select', () => ({
}))
//react-native-picker-select

jest.mock('react-native-linear-gradient', () => { });
```

**Steps to reproduce:**
1. Open LoginScreen.test.js file.
2. Look for the test case Login_Screen_should_render_correctly.
3. Check if the component being rendered in the test is defined and exported correctly.
4. Make sure the import statements are correct, and the component is imported properly.
5. If the above steps don't resolve the issue, look for any syntax errors or typos in the component's code.
6. Once the issue is resolved, run the test again to ensure it passes.

 ### Created issue repository

https://github.com/GittyAjay/rn-test-issue.git

**Expected outcome:**
The test case Login_Screen_should_render_correctly should pass without any errors.

**Comment by mdjastrzebski** [comment]
@GittyAjay Could you create a git repo for this issue. It is a hassle to manualny reproduce these steps.

**Comment by GittyAjay** [comment]
@mdjastrzebski   sorry i can't it's a private project.

**Comment by GittyAjay** [comment]
> @GittyAjay Could you create a git repo for this issue. It is a hassle to manualny reproduce these steps.

Hi, I have created a new repo with this issue,pls check it 
[](https://github.com/GittyAjay/rn-test-issue.git)

**Comment by GittyAjay** [comment]
> @GittyAjay Could you create a git repo for this issue. It is a hassle to manualny reproduce these steps.
https://github.com/GittyAjay/rn-test-issue.git
Have you checked it ?

**Comment by mdjastrzebski** [comment]
@GittyAjay The issue here is that you are mocking `react-native` package in very harsh way:

```
jest.mock('react-native', () => ({
  useWindowDimensions: () => jest.fn(),
  Platform: {select: () => ({})},
  StyleSheet: {
    create: () => ({}),
  },
  NativeModules: {
    TestConnectNative: () => ({}),
  },
  Dimensions: {get: () => ({})},
  AppState: {
    currentState: 'active',
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
  },
}));
```

This basically declares only the above mentioned names.

Typically you should also include are the original functions:

```
jest.mock('react-native', () => ({
  ...jest.requireActual('react-native'),
  useWindowDimensions: () => jest.fn(),
  // ...
}));
```

That doesn't fix your tests yet, but it resolves the reported issue.

In general you should avoid overriding most of the above functions, e.g StyleSheets, Dimentions, AppState, etc as it will break a lot of things for the RN itself.

**Comment by GittyAjay** [comment]
> @GittyAjay The issue here is that you are mocking `react-native` package in very harsh way:
> 
> ```
> jest.mock('react-native', () => ({
>   useWindowDimensions: () => jest.fn(),
>   Platform: {select: () => ({})},
>   StyleSheet: {
>     create: () => ({}),
>   },
>   NativeModules: {
>     TestConnectNative: () => ({}),
>   },
>   Dimensions: {get: () => ({})},
>   AppState: {
>     currentState: 'active',
>     addEventListener: jest.fn(),
>     removeEventListener: jest.fn(),
>   },
> }));
> ```
> 
> This basically declares only the above mentioned names.
> 
> Typically you should also include are the original functions:
> 
> ```
> jest.mock('react-native', () => ({
>   ...jest.requireActual('react-native'),
>   useWindowDimensions: () => jest.fn(),
>   // ...
> }));
> ```
> 
> That doesn't fix your tests yet, but it resolves the reported issue.
> 
> In general you should avoid overriding most of the above functions, e.g StyleSheets, Dimentions, AppState, etc as it will break a lot of things for the RN itself.

after that my error got increased in dramatic way


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at reportLogBoxError (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:72:27)
      at Immediate._onImmediate (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:160:7)
TypeError: ExceptionsManager.handleException is not a function
    at reportLogBoxError (/Users/ajaypandey/esoft/wsmarshals/wsmarshal/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:78:21)
    at Immediate.<anonymous> (/Users/ajaypandey/esoft/wsmarshals/wsmarshal/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:160:7)
    at processImmediate (node:internal/timers:475:21)

**Comment by mdjastrzebski** [comment]
Added [Troubleshooting Guide entry](https://callstack.github.io/react-native-testing-library/docs/troubleshooting#undefined-component-error) about following error:
> "Trying to detect host component names triggered the following error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.":
