### ISSUE TITLE
12.0 *ByRole is failing, even for the migration guide example.

### ISSUE THREAD

**Issue by edkimmel** [callstack/react-native-testing-library#1381]
## Describe the bug

Our project's test suite is failing to find elements with the *ByRole operation changes in 12.X.

## Expected behavior

I would expect to be able to find accessible components with an accessibilityRole set.

## Steps to Reproduce

The [migration guide](https://callstack.github.io/react-native-testing-library/docs/migration-v12) suggests that the following component should match:

// Explicit "accessible" prop for View
<View accessible role="button" />

I have created a simple test in a fork of this repo to show that it does not match.
https://github.com/edkimmel/react-native-testing-library/commit/e5291cd804128849ea520e930f2b58e1c1561e92

```
 FAIL  src/__tests__/render.test.tsx
  ● GetByRole

    Unable to find an element with role: "button"

      249 | test('GetByRole', () => {
      250 |   const { getByRole } = render(<View accessible role="button"/>)
    > 251 |   expect(getByRole("button")).toBeTruthy()
          |          ^
      252 | });

      at Object.getByRole (src/__tests__/render.test.tsx:251:10)
```
## Versions

Fork off of latest main of this repository.

**Comment by mdjastrzebski** [comment]
The prop name should be `accessibilityRole`, the test file you provided seems to use `role` prop.

**Comment by mdjastrzebski** [comment]
The prop name should be `accessibilityRole`, the test file you provided seems to use `role` prop.

**Comment by edkimmel** [comment]
@mdjastrzebski 
1) As of react native 0.71, accessibilityRole is deprecated in favor of role to match the prop used on web (It is just an alias for now) https://github.com/facebook/react-native/commit/a50e6fb341eacd955071e4a7c6d734e7d3c94cd7

2) The migration guide also uses role as the example.


I do see that accessibilityRole still functions

**Comment by mdjastrzebski** [comment]
@edkimmel afaik `accessibilityRole` is not being deprecated at all, the new `role` prop is only a web-inspired alias. Though the values passed to `role` prop are actually mapped to `accessibilityRole` values, with many `role` values being actually mapped to `undefined`. 

In the current RN codebase only the `accessibilityRole` props affect the native iOS/Android "roles" recognized by assistive tech like screen readers.

I've run the test you prepared, and in that test RN does not seem to emit `role` prop translation to `accessibilityRole` that would be necessary for `role` prop to work. Would you have some time to investigate this issue?

**Comment by mdjastrzebski** [comment]
Closing as stale.
