### ISSUE TITLE
Useless dependency to React Navigation in v12.1.0

### ISSUE THREAD

**Issue by hduprat** [callstack/react-native-testing-library#1397]
## Describe the bug

When I updated the library to the latest version, I noticed a dependency to `@react-navigation/native` in its package.json.

## Expected behavior

There is no need for such a dependency in the main package.json, only in examples.

## Steps to Reproduce

https://github.com/callstack/react-native-testing-library/blob/main/package.json#L63

## Versions

v12.1.0

**Comment by mdjastrzebski** [comment]
@hduprat you are right, that must have slipped through review. I'll publish a patch release without it later today.

**Comment by mdjastrzebski** [comment]
This issue has been resolved in [v12.1.1](https://github.com/callstack/react-native-testing-library/releases/tag/v12.1.1) 🚀
