### ISSUE TITLE
How to fix TypeError: Cannot read properties of undefined (reading 'navigate')

### ISSUE THREAD

**Issue by DominicGBauer** [callstack/react-native-testing-library#1414]
## Ask your Question
I am getting this error 
```jsx
    TypeError: Cannot read properties of undefined (reading 'navigate')
      16 |   const handleNavigateToNewPlan = () => {
      17 |     dispatch(updateJourney('NewPlan'));
    > 18 |     navigation.navigate('GetOtp');
         |                ^
      19 |   };
      20 |   const handleNavigateToExistingPlan = () => {
      21 |     dispatch(updateJourney('ExistingPlan'));
```
when trying to test navigation in my component while trying to test react navigation. 

Component:
```jsx
import { Text, Button } from 'react-native-paper';
import { View } from 'react-native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { styles } from './SelectJourney.styles';
import { useAppDispatch } from '../../common/redux/hooks';
import { updateJourney } from './SelectJourney.slice';
import type { RootStackParamList } from '../../../App';

interface Props {
  navigation: NativeStackNavigationProp<RootStackParamList, 'SelectJourney'>;
}

export const SelectJourneyScreen: React.FunctionComponent<Props> = ({ navigation }) => {
  const dispatch = useAppDispatch();

  const handleNavigateToNewPlan = () => {
    dispatch(updateJourney('NewPlan'));
    navigation.navigate('GetOtp');
  };
  const handleNavigateToExistingPlan = () => {
    dispatch(updateJourney('ExistingPlan'));
    navigation.navigate('GetOtp');
  };

  return (
    <View style={styles.container}>
      <Text>Select if this is a new plan</Text>
      <Button mode="contained" onPress={handleNavigateToNewPlan}>
        New Lay Buy
      </Button>
      <Text>Select if this if it is an active plan</Text>
      <Button mode="contained" onPress={handleNavigateToExistingPlan}>
        Existing Lay Buy
      </Button>
    </View>
  );
};
```
and the test 
```jsx
import { render, screen, fireEvent } from '@testing-library/react-native';
import { NavigationContainer } from '@react-navigation/native';
import { Provider } from 'react-redux';
import { SelectJourneyScreen } from './SelectJourney';
import { store } from '../../common/redux/store';

describe('SelectJourneyScreen', () => {
  it('should navigate to GetOtp when New Lay Buy is clicked', () => {
    render(
      <Provider store={store}>
        <NavigationContainer>
          <SelectJourneyScreen />
        </NavigationContainer>
      </Provider>,
    );
    const newLayBuyButton = screen.getByText('New Lay Buy');
    fireEvent.press(newLayBuyButton);

    expect(screen.getByText('Reference Number')).toBeOnTheScreen();
  });
});
```

I've tried to follow the docs and I think I am but not sure what I am doing wrong?

**Comment by pierrezimmermannbam** [comment]
Hi @DominicGBauer ! I could not say for sure what's wrong here but I think that your Screen component will not have a navigation prop unless it's rendered within a navigator. If I'm correct you should also have a typescript error in your test saying that the SelectJourneyScreen component expects a navigation prop. 

Also in you're test you're trying to navigate to a screen that's not rendered so even if the navigation prop of your screen was defined it would not work. To test the navigation between multiple screens you should either:

- render the navigator that contains both those screens, and wrap that navigator with a navigation container. In this case the NavigationContainer will make the navigation object available and the navigator will pass navigation as prop to the screens within. You can refer to the example test on StackNavigator for instance.
- render a single screen and pass a mock object for the navigation. Then you can check if the navigate method has been called with the expected route name and params. Check the test for DetailsScreen in the examples to see how to do that (although in this example we don't directly test the screen it would be done in a similar way).

Hope this makes things clearer!

**Comment by DominicGBauer** [comment]
@pierrezimmermannbam that makes a lot of sense thanks a lot for clarifying!
