### ISSUE TITLE
renderHook's rerender not has undefined prop type unless explicitly typed

### ISSUE THREAD

**Issue by rarenatoe** [callstack/react-native-testing-library#1420]
## Describe the bug

The following code returns a typescript error

```ts
import { renderHook } from '@testing-library/react-native'
import { useMyHook } from '../hooks'

describe('useMyHook', () => {
  it('should pass', () => {
    const { result, rerender } = renderHook((num: number) => useMyHook(num), { initialProps: undefined })

    expect(result.current).toBeUndefined()

    rerender('granted') //Error here, props type is undefined

    expect(result.current).toBe('granted')
  })
})
```

For it to work fine I have to to do
```ts
    const { result, rerender } = renderHook<number, number>((num: number) => useMyHook(num), { initialProps: undefined })
```

this doesn't happen when using 
```ts
import { renderHook } from '@testing-library/react-hooks'
```

## Expected behavior

Not having a typescript error and instead pull the prop types correctly.

## Steps to Reproduce

See description.

## Screenshots

<img width="617" alt="Screenshot 2023-06-20 at 12 58 02" src="https://github.com/callstack/react-native-testing-library/assets/44821537/e5ccd102-0f2b-4878-a9c9-ae6b9fe56d04">

<img width="281" alt="Screenshot 2023-06-20 at 12 58 17" src="https://github.com/callstack/react-native-testing-library/assets/44821537/d4804874-7c9f-4c8d-b8d3-cb62281934cf">

## Versions

```
  npmPackages:
    @testing-library/react-native: 12.1.2 => 12.1.2 
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.9 => 0.70.9 
    react-test-renderer: 18.1.0 => 18.1.0 
```

**Comment by pierrezimmermannbam** [comment]
Hello @rarenatoe, thanks for submitting the issue! I have opened a pr #1421 to fix it
