### ISSUE TITLE
First test running render/renderHook is slow

### ISSUE THREAD

**Issue by KrastanD** [callstack/react-native-testing-library#1423]
## Describe the bug

  The first test in a file that uses render/renderHook is slow. This is exacerbated when ran without jest cache. 

  Locally on my M1 Pro Macbook:
  Without jest cache, the first test takes ~27 times as long as the second test. 1512ms vs 55ms
  With jest cache, the first test takes ~3 times as long which seems reasonable. 142ms vs 56ms

  On Github Actions:
   Without jest cache, the first test takes ~70 times as long as the second test. 
  
  I know it's not related to the actual tests because if I change the order of them it is always the one that is first that takes significantly longer.

## Expected behavior

I would expect that it takes the tests to run under a second whether they are cached or not, first or not.

## Steps to Reproduce

React Query has an example repo using CRA and react testing library with some sample tests [here](https://github.com/TkDodo/testing-react-query/tree/main)
I recreated the repo and tests using expo and react native testing library [here](https://github.com/KrastanD/testing-react-native-query)

When running the RTL repo tests without cache I get the following: 
![image](https://github.com/callstack/react-native-testing-library/assets/32044675/a19b5b94-1d7d-482a-af74-a36d3fb6878f)
All tests take under 100 ms. 

When running the RNTL repo tests without cache I get the following:
![image](https://github.com/callstack/react-native-testing-library/assets/32044675/4498d36f-ea31-4280-a1f0-4b7439a045d8)
Both first tests take 1.6 seconds.

I also ran the RNTL repo tests on Github Actions [here](https://github.com/KrastanD/testing-react-native-query/actions/runs/5424525570/jobs/9864005024) with the following results:
![image](https://github.com/callstack/react-native-testing-library/assets/32044675/89b28cd6-5e30-4eae-99c8-4313dcea92e2)
Interestingly its only the first renderHook that takes a long time of 4.1 seconds. 

I created a branch in the RNTL repo called [renderHook-isolated](https://github.com/KrastanD/testing-react-native-query/tree/renderHook-isolated). There I created two new test files that don't use react-query or msw - just basic react-native and react native testing library. 
Here are the results:
![image](https://github.com/callstack/react-native-testing-library/assets/32044675/5ebe67a5-10cb-449f-adb7-b2376687b426)
Even the very basic react hook test takes 3/4 of a second and it seems react query just makes the matter worse. 

From my understanding, `renderHook` just calls the hook in a 'render`ed Test Component so i would assume the issue is in the `render` function. I won't pretend to know how it works but perhaps whatever setup jest and RNTL do before the tests is somehow leaking into the first test.

Curious to hear your thoughts and thanks in advance!

Note: This is very specific but I noticed that this issue is resolved if I first use `render` on any component wrapped in a [TamaguiProvider](https://tamagui.dev/docs/core/configuration#using-tamagui-provider) in a separate test in the same file.
Perhaps rendering something as complicated as the `TamaguiProvider` causes a big enough delay to not leak into the other tests. 🤷 

## Versions

     npmPackages:
    @testing-library/react-native: ^12.1.2 => 12.1.2 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8

**Comment by KrastanD** [comment]
@pierrezimmermannbam thanks for the explanation. The reason I even noticed this was because one of my tests times out on CI during waitFor. Do you have any recommended way to make sure that the test doesn't take too long? 

As for a solution, I think the default case can be like now where the first test is slow, but allow users to configure it in the jest setup file. If they have it configured then render can grab the components from there and be quick.

**Comment by pierrezimmermannbam** [comment]
@KrastanD is it a waitFor timeout or a jest timeout? If the test takes longer as a whole it may result in a jest timeout but I don't see how it could make a waitFor timeout

**Comment by KrastanD** [comment]
@pierrezimmermannbam It is a waitFor. It times out and returns false instead of true which fails my test. The waitFor for reference:
```
    await waitFor(() => expect(result.current.isSuccess).toBe(true));
```

**Comment by mdjastrzebski** [comment]
@KrastanD should be fixed in v12.1.3. Pls check.

**Comment by KrastanD** [comment]
Confirming this fixed `renderHook` being slow. It doesn't fix `render` being slow so I'll leave it up to you if you want to close this issue or not.

**Comment by mdjastrzebski** [comment]
Closing as the `renderHook` part has been fixed. 

he `render` part, as far as I can tell, can only be fixed by hardcoding core host component names vs. always querying on first render (as is now). The hardcoding approach would improve the speed, as we would not longer have to run `detectHostComponentNames` but it would also make RNTL less robust due to additional assumption about internal RN host component naming, which has been changed in the past.

**Comment by KrastanD** [comment]
@mdjastrzebski What about allowing users to run detectHostComponentNames in `setup-jest`? This would be optional so for users who don't care it will run as part of the first test, but for those that do it won't affect any individual test while keeping RNTL robust.
