### ISSUE TITLE
Issue installing package through yarn or npm "https://registry.yarnpkg.com/@testing-library%2freact-native: Not found"

### ISSUE THREAD

**Issue by zackpudil** [callstack/react-native-testing-library#1430]
## Describe the bug

Getting error when trying to install yarn package:
```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@testing-library%2freact-native: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/zack.pudil/Code/testing-library-sucks/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Is happening for both new projects and projects that have it in the package.json already.  
## Expected behavior

@testing-library should install with no issues.

## Steps to Reproduce

```
cd some-empty-folder
yarn init
yarn add --dev @testing-library/react-native
```

## Screenshots

Issue for new project:
![image](https://github.com/callstack/react-native-testing-library/assets/686539/5c49856e-4bc8-4522-9ecf-6a57e07a4d76)

Issue on existing project with yarn.lock entry:
![image](https://github.com/callstack/react-native-testing-library/assets/686539/092912cf-70ff-49c0-ba29-71e2e960e186)

**Comment by FanchenBao** [comment]
Same here. Running

```
curl https://registry.npmjs.org/@testing-library/react-native
```

results in `{"error":"Not found"}`

**Comment by KevinHu2014** [comment]
Same here

**Comment by mdjastrzebski** [comment]
@zackpudil could be some temporary NPM issue.

**Comment by zackpudil** [comment]
Must've been.  It was only happening to this library so I figured I'd submit a ticket.  Issue isn't happening anymore, closing.
