### ISSUE TITLE
Try to test the event onMomentumScrollEnd, but fail

### ISSUE THREAD

**Issue by Seauning** [callstack/react-native-testing-library#1431]
## Describe the bug
While try to test the event onMomentumScrollEnd by fireEvent.scroll ,  but fail.

## Expected behavior
The callback for onMomentumScrollEnd be executed, and log info.

## Steps to Reproduce
```typescript
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

export interface TestScrollViewProps {}

const style = StyleSheet.create({
    scrollView: {
        width: 330,
        height: 100,
    },
    item: {
        height: 50,
    },
});

const TestScrollView = ({}: TestScrollViewProps) => {
    const onMomentumScrollEnd = () => {
        console.log('end', 1111);
    };
    return (
        <ScrollView
            onMomentumScrollEnd={onMomentumScrollEnd}
            testID="scroll-view"
            style={style.scrollView}
        >
            {[...new Array(200)].map((_, index) => {
                return (
                    <View key={index} style={style.item}>
                        <Text>123</Text>
                    </View>
                );
            })}
        </ScrollView>
    );
};

export default TestScrollView;

// index.test.tsx
import React from 'react';
import TestScrollView from '../TestScrollView';
import { fireEvent, render } from '@testing-library/react-native';

describe('TestScrollView', () => {
    it('events: onMomentumdScrollEnd', () => {
        const { getByTestId } = render(<TestScrollView />);
        const scrollview = getByTestId('scroll-view');
        const eventData = {
            nativeEvent: {
                contentOffset: {
                    x: 1000,
                },
                contentSize: { height: 100, width: 330 },
                layoutMeasurement: { height: 876, width: 414 },
            },
        };
        fireEvent.scroll(scrollview, eventData);
    });
});
```

## Versions
"react-native": "0.62.2",
"react": "16.11.0",
"react-test-renderer": "16.11.0",
"@testing-library/react-native": "^9.1.0",

**Comment by pierrezimmermannbam** [comment]
Hello @Seauning! Thanks for reporting the issue. This is unfortunately the expected behavior for now. What `fireEvent.scroll` does is calling the `onScroll` prop of your component and that's it. When you call `fireEvent.press`, it also only calls the `onPress` prop and not `onPressIn`, `onTouchStart`, etc... It does not simulate a complete scroll event, it only calls a prop, that's a limitation of the library for now.

To make your test work, you can manually trigger the `onMomentumdScrollEnd ` prop by doing the following

```tsx
fireEvent(element, 'momentumdScrollEnd', event);
```

For the longer term, we're currently working on a new API called `userEvent` that would provide a more realistic simulation but it's still a work in progress.

Regarding `fireEvent` API, its behavior is documented in the [API doc](https://callstack.github.io/react-native-testing-library/docs/api#fireevent) but maybe it's not explicit enough that it will only call one prop and we should update it, @mdjastrzebski wdyt? It seems to be very confusing for users rn

**Comment by Seauning** [comment]
> Hello @Seauning! Thanks for reporting the issue. This is unfortunately the expected behavior for now. What `fireEvent.scroll` does is calling the `onScroll` prop of your component and that's it. When you call `fireEvent.press`, it also only calls the `onPress` prop and not `onPressIn`, `onTouchStart`, etc... It does not simulate a complete scroll event, it only calls a prop, that's a limitation of the library for now.
> 
> To make your test work, you can manually trigger the `onMomentumdScrollEnd ` prop by doing the following
> 
> ```tsx
> fireEvent(element, 'momentumdScrollEnd', event);
> ```
> 
> For the longer term, we're currently working on a new API called `userEvent` that would provide a more realistic simulation but it's still a work in progress.
> 
> Regarding `fireEvent` API, its behavior is documented in the [API doc](https://callstack.github.io/react-native-testing-library/docs/api#fireevent) but maybe it's not explicit enough that it will only call one prop and we should update it, @mdjastrzebski wdyt? It seems to be very confusing for users rn

Sounds great, I cloned the source code, saw the specific implementation, and understood it more clearly through your reply, thank you, looking forward to future useEvent.

**Comment by mdjastrzebski** [comment]
@pierrezimmermannbam looks like we have a next candidate for UserEvent event :-)

We can definitely improve the `fireEvent` wording to make it clear how it works and what to expect.

**Comment by Seauning** [comment]
Unfortunately, i try to change `fireEvent.scroll(scrollview, eventData); ` to `fireEvent(scrollView, 'momentumdScrollEnd', eventData);`, but there no something to log.That is why? because of the environment?
Same as the issue for https://github.com/callstack/react-native-testing-library/issues/1431#issue-1807398383

**Comment by Seauning** [comment]
> 

sure, for the issue, try to change `fireEvent.scroll(scrollview, eventData);` to `fireEvent(scrollView, 'momentumScrollEnd', eventData);`, and the callback for `onMomentumdScrollEnd` will excute.
```typescript
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

export interface TestScrollViewProps {}

const style = StyleSheet.create({
    scrollView: {
        width: 330,
        height: 100,
    },
    item: {
        height: 50,
    },
});

const TestScrollView = ({}: TestScrollViewProps) => {
    const onMomentumScrollEnd = () => {
        console.log('end', 1111);
    };
    return (
        <ScrollView
            onMomentumScrollEnd={onMomentumScrollEnd}
            testID="scroll-view"
            style={style.scrollView}
        >
            {[...new Array(200)].map((_, index) => {
                return (
                    <View key={index} style={style.item}>
                        <Text>123</Text>
                    </View>
                );
            })}
        </ScrollView>
    );
};

export default TestScrollView;

// index.test.tsx
import React from 'react';
import TestScrollView from '../TestScrollView';
import { fireEvent, render } from '@testing-library/react-native';

describe('TestScrollView', () => {
    it('events: onMomentumdScrollEnd', () => {
        const { getByTestId } = render(<TestScrollView />);
        const scrollview = getByTestId('scroll-view');
        const eventData = {
            nativeEvent: {
                contentOffset: {
                    y: 1000,
                },
            },
        };
        fireEvent(scrollview, 'momentumScrollEnd', eventData);
    });
});
```

**Comment by Seauning** [comment]
> @Seauning could you confirm that this issues is solved?

sure, for the issue, try to change `fireEvent.scroll(scrollview, eventData);` to `fireEvent(scrollView, 'momentumScrollEnd', eventData);`, and the callback for `onMomentumdScrollEnd` will excute.
```typescript
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

export interface TestScrollViewProps {}

const style = StyleSheet.create({
    scrollView: {
        width: 330,
        height: 100,
    },
    item: {
        height: 50,
    },
});

const TestScrollView = ({}: TestScrollViewProps) => {
    const onMomentumScrollEnd = () => {
        console.log('end', 1111);
    };
    return (
        <ScrollView
            onMomentumScrollEnd={onMomentumScrollEnd}
            testID="scroll-view"
            style={style.scrollView}
        >
            {[...new Array(200)].map((_, index) => {
                return (
                    <View key={index} style={style.item}>
                        <Text>123</Text>
                    </View>
                );
            })}
        </ScrollView>
    );
};

export default TestScrollView;

// index.test.tsx
import React from 'react';
import TestScrollView from '../TestScrollView';
import { fireEvent, render } from '@testing-library/react-native';

describe('TestScrollView', () => {
    it('events: onMomentumdScrollEnd', () => {
        const { getByTestId } = render(<TestScrollView />);
        const scrollview = getByTestId('scroll-view');
        const eventData = {
            nativeEvent: {
                contentOffset: {
                    y: 1000,
                },
            },
        };
        fireEvent(scrollview, 'momentumScrollEnd', eventData);
    });
});
```
