### ISSUE TITLE
Cannot destructure property 'getBy' of '(0 , _makeQueries.makeQueries)(...)' as it is undefined.

### ISSUE THREAD

**Issue by brettscott4** [callstack/react-native-testing-library#1437]
I am receiving the following error when calling the render method: 
` TypeError: Cannot destructure property 'getBy' of '(0 , _makeQueries.makeQueries)(...)' as it is undefined.
 at Object.getBy (node_modules/@testing-library/react-native/src/queries/text.ts:42:9)
      at Object.require (node_modules/@testing-library/react-native/src/within.ts:2:1)
      at Object.require (node_modules/@testing-library/react-native/src/render.tsx:14:1)
      at Object.require (node_modules/@testing-library/react-native/src/pure.ts:4:1)
      at Object.require (node_modules/@testing-library/react-native/src/index.ts:1:1)
`

### Versions:
"react": "18.2.0"
"react-native": "^0.72.3"
"jest": "^29.6.1"
"react-test-renderer": "^18.2.0"
"typescript": "^5.1.6"
"babel-jest": "^29.6.1"

**Comment by mdjastrzebski** [comment]
@brettscott4 Pls post the testing code that causes this error.

**Comment by brettscott4** [comment]
> @brettscott4 Pls post the testing code that causes this error.

```
import * as React from 'react'
import {render} from '@testing-library/react-native'
import Home from './Home'
test('home screen', () => {
  render(<Home />)
})
```

**Comment by mdjastrzebski** [comment]
@brettscott4 the code you posted looks pretty generic and does not seem to contain any reason for failure. Could you create a minimal reproduction scenario using our's [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) so that we can investigate the issue locally?

**Comment by mdjastrzebski** [comment]
@brettscott4 did you managed fix your issue or reproduce it using [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic)?
