### ISSUE TITLE
feature: UserEvent `scroll()`

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1441]
## Describe the Feature

Create a User Event interaction(s) for scrolling. This seems to be pretty frequent interaction on touch based devices, at the same time there are numerous events involved: `onScroll`, `onMomentumScrollBegin/End`, onScrollBegin/EndDrag`, etc. This feature should work with `ScrollView` as well as `FlatList`/`SectionList` (hopefully these will be same event sequences).

## Possible Implementations

As with other User Event interactions:
1. Create ScrollView/FlatList experiment in the experiments app
2. Conduct scroll interactions (dragging, vertical swiping) on both iOS & Android, record logged events in our Wiki
3. Define unified event sequence roughly matching both iOS & Android, as well as events documentation
4. Write implementation and relevant unit tests

## Related Issues
#1405 - core User Event code
#1386 - `press()` implementation
#1396 - `type()` implementation

**Comment by siepra** [comment]
Hi, do you mind if I tried?

**Comment by mdjastrzebski** [comment]
@siepra go ahead.

In order to achieve the high-quality simulation pls submit experiments app PR first, then fill in the Wiki, only then start to work on the actual code (as described in the issue desc).

**Comment by mdjastrzebski** [comment]
You should log it in experiment, but probably does not happen on actual scrolling

**Comment by mdjastrzebski** [comment]
@siepra step 1 merged. Time for recording logged events on wiki.

**Comment by siepra** [comment]
Great, thank you!
I don't have access to edit wiki pages in this repo, am I right? I'm attaching a file containing my recorded logs along with notes on observations (I'm not sure whether the formatting is fully correct) so you can post it by yourself. Or if there's another way, please let me know!
[wiki-draft.md](https://github.com/callstack/react-native-testing-library/files/12290015/wiki-draft.md)

**Comment by mdjastrzebski** [comment]
@siepra I've copied your research into the [wiki](https://github.com/callstack/react-native-testing-library/wiki/ScrollView-Events).

Now we need to decide on the API for user interactions: 
* what interactions to support
* what should be it's parameters
* what events should they emit

Some initial thoughts about API:
* `user.scrollTo({ x, y })`
  * with x and y being optional in order to allow both vertical or horizontal scroll.
  * We should assume the initial scroll position is (x, y) = (0, 0).
  * In order not to assume that each of the scroll operations is starting from (0, 0) and going to (x, y), we should save the current scroll values for the element. Note: this will be "virtual state" not affected by calling `ref.scrollTo()`. 
  * This helper could emit `onScrollBeginDrag`, a number of `onScroll` events (steps between initial and final position), and `onScrollEndDrag`
  * We could have options like `momentumScroll: boolean` to control whether there should be `onMomentumScrollBegin`+ `onScroll` x n, `onMomentumScrollEnd` happening after the initial drag scrolling
  * These should work for both `ScrollView` and `FlatList`.
  * Regarding FlatLists's `onEndReached` event we could treat it as an option to `scrollTo`
* `user.scrollToTop` as a specialized interaction

These are just rough ideas, feel free to challenge them, you can also start coding the implementations & tests to get a better feel for the API.

**Comment by siepra** [comment]
Bummer, I thought we're able to calculate content size and make it smarter.

I'm worried about validating host element type and writing tests for `FlatList` as it renders it's child components and I see `ReactTestRenderer` doesn't handle it well (or maybe I'm doing something wrong?):

```
import { render, screen } from '../../..';

render(
  <FlatList
    data={[]}
    renderItem={jest.fn()}
  />
);
```

```
    TypeError: Cannot destructure property 'getItem' of 'props' as it is undefined.

      11 |   let renderer: ReactTestRenderer;
      12 |
    > 13 |   TestRenderer.act(() => {
         |                ^
      14 |     renderer = TestRenderer.create(component, options);
      15 |   });
      16 |
```

**Comment by mdjastrzebski** [comment]
You should pass a function creating actual JSX elements to `renderItem` instead of `jest.fn()` which return `undefined` by default.

**Comment by siepra** [comment]
You mean like:
```
() => {
    return <View />
}
```
It doesn't work neither

**Comment by mdjastrzebski** [comment]
@siepra You're right, I was able to replicate it easily. tbh I was not aware of that, so that's for catching it.

Anyway, let's work on `ScrollView` first, and I will do some research on FlatList, so we could enable it later.

**Comment by siepra** [comment]
So far I've come with
A `scroll` API endpoint, which accepts:

- x?, y?
- (optional) number of intermediate `onScroll` callbacks
- (optional) momentum, consisting of it's value and number of intermediate `onScroll` callbacks

A `scrollToTop` API endpoint.

They both work with `ScrollView` and are directly accessible in `userEvent`.
There is no validation on host element type due to `FlatList` suspense.

There are some questions that popped into my head:

@mdjastrzebski you said we should save the current scroll values for the element. Could you drop some hints on how to achieve that? We'd have to globally keep the reference to an element instance, wouldn't we?

Do we want to decorate `scrollToTop` method somehow? Is a comment in the code enough?

Remaining things:

- [ ] Add support for `FlatList`
- [ ] Provide option to scroll until `onEndReached` (`FlatList`)
- [ ] Perform validation on host element type

Is there something else I'm missing?

**Comment by mdjastrzebski** [comment]
re saving values:

The way we could achieve this is to have some `WeakMap` object keyed by `ScrollView` element.  Something like that:

```
interface ScrollState { x: number, y: number };

const scrollStateForElement = new WeakMap<ReactTestInstance, ScrollState>();

export function getElementScrollState(element: ReactTestInstance) {
  return scrollStateForElement[element] ?? { x: 0, y: 0 }; // default to (0, 0)
}

export function setElementScrollState(element: ReactTestInstance, scrollState: ScrollState) {
  scrollStateForElement[element] = scrollState
}
```

`WeakMap` has two important properties:
1. It can be keyed by any object, not only strings/symbols as regular objects
2. It holds only a weak reference to the element, hence it will automatically drop it when JS garbage collector decides that given element is no longer reachable, hence preventing memory leaks.

Additionally, iirc. `ReactTestInstances` are stable across re-renders, as they are cached in a similar way we want to handle storing scroll state: https://github.com/facebook/react/blob/a20eea25197df0da80104917df414747eeab1ac9/packages/react-test-renderer/src/ReactTestRenderer.js#L616

**Comment by pierrezimmermannbam** [comment]
If understand correctly the API the user wouldn't need to pass an element to the scroll function. I think it's a good idea but in that case how do we know on which element to apply the scroll events?

**Comment by mdjastrzebski** [comment]
@pierrezimmermannbam they definitely need to pass element there. Otherwise how would we know which element to scroll?

**Comment by siepra** [comment]
@mdjastrzebski it works :) TypeScript doesn't like the idea of `ReactTestInstance` being an index though...
![image](https://github.com/callstack/react-native-testing-library/assets/15381135/c1cdcffe-a550-4dcd-a21d-57993d708427)
I assume `@ts-expect-error` isn't the desired solution?

Also, in tests the rendered `<ScrollView />` element is always being treated as the same instance and I don't really know what to do about it. I've been trying to change it's props but it doesn't seem to make any difference. I've generated snapshots individually per each case for now.

**Comment by mdjastrzebski** [comment]
@siepra you have to use [`set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap/set) and `get` methods, as index operator (`[]`) will attach it as object prop, but since these can be only string or symbol, this means that the actual key will be like `[Object object]` and one entry will override the other.

**Comment by siepra** [comment]
Got it!

**Comment by siepra** [comment]
@mdjastrzebski I think the only remaining thing is `FlatList` now. Would you mind taking a look at https://github.com/callstack/react-native-testing-library/pull/1445 and sharing thoughts on the code?

**Comment by siepra** [comment]
(FlatList) not sure if it's helpful but I see the problem is re-creating component instance at `react-test-renderer.development.js:4460`. React Native's `FlatList` receives actual `props` in it's constructor but then it only references `this.props` which is always `undefined`

**Comment by pierrezimmermannbam** [comment]
> @pierrezimmermannbam they definitely need to pass element there. Otherwise how would we know which element to scroll? 

Well usually there is a single element scrollable on a screen. There may be more but they are most of the time not in the same direction. For most use cases we could detect either a scrollview or a flat list and use that I think. Maybe the element could be optional so that in case user has nested scroll views he may be able to target one specifically? Because otherwise how do you target a scrollview if not with a test id?

**Comment by mdjastrzebski** [comment]
I think we should require element for now, as it matches the convention of all other FireEvent/UserEvent API which also require element to trigger event/interaction on. Users are familiar with this pattern, and it makes the tests more robust, in cases user introduces another scroll view in the complex component.

There are valid UI patterns when you have 2+ scroll views, e.g. 1+ horizontal scroll views that can be scrolled independently inside overall vertical scroll view.

**Comment by pierrezimmermannbam** [comment]
In the case where there is an horizontal and a vertical scrollview we would know which one to scroll on based on the direction of the scroll but it wouldn't work if there are several horizontal scroll views though. Some other cases like scrollviews within tabs may also be problematic so maybe it's not a good idea after all. I thought about this because in e2e tests you don't provide the element but unfortunately we have limitations that prevent us from having the same API so I agree it's better to have the element being mandatory

**Comment by mdjastrzebski** [comment]
I've created a separate issue for discussion just the `scroll` API, without dealing with implementation detals: https://github.com/callstack/react-native-testing-library/issues/1450

**Comment by mdjastrzebski** [comment]
Resolved in https://github.com/callstack/react-native-testing-library/pull/1445
