### ISSUE TITLE
feature: implement `toBeVisible` Jest matcher

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1458]
## Describe the Feature

`toBeVisible` is a [Jest DOM matcher](https://github.com/testing-library/jest-dom#tobevisible) that asserts the visibility of given element by inspecting various CSS styles and other semantic attributes that might make element invisible.

Adapting it to our case it would assert the value in `TextInput` host elements, to match given value.

## Possible Implementations
Proposed API:

```ts
export function toBeVisible(
  this: jest.MatcherContext,
  element: ReactTestInstance
)
```

The matcher should:
1) Validate that it is invoked on host element
2) Check visibility status of given element and all of it's ancestors

Each matcher should have a fairly comprehensive test suite.

Open Questions:
* should this matcher take into account accessibility props? Consider use cases and pros and cons,

## Links

* `toBeVisible` matcher code from Jest DOM: https://github.com/testing-library/jest-dom/blob/main/src/to-be-visible.js
* `toBeVisible` implementation for Jest Native: https://github.com/testing-library/jest-native/blob/main/src/to-be-visible.ts

## Related Issues
#1454

**Comment by thiagobrez** [comment]
Hey, would love to give a try at this one!

**Comment by mdjastrzebski** [comment]
@thiagobrez go ahead! Simply submit PR with your work in progress.

**Comment by thiagobrez** [comment]
PR is ready to review here: https://github.com/callstack/react-native-testing-library/pull/1465

**Comment by mdjastrzebski** [comment]
🎉 Release in version: [v12.4.0](https://github.com/callstack/react-native-testing-library/releases/tag/v12.4.0)
