### ISSUE TITLE
feature: implement `toBeEmptyElement` Jest matcher

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1459]
## Describe the Feature

[`toBeEmptyDOMElement`](https://github.com/testing-library/jest-dom#tobeemptydomelement) is a Jest DOM matcher that asserts the visibility of given element by inspecting whether it contains any child elements.

Adapting it to our case it would assert that given host element does not contain any host children elements. It might contain some composite elements as long as these do not have host descendants. We already have function for getting host children of given element ([`getHostChildren`](https://github.com/callstack/react-native-testing-library/blob/4bfd7fbc6ba76ad376e24f3d41be1d638b6351a2/src/helpers/component-tree.ts#L45)) so that should be relatively straightforward.

## Possible Implementations
Proposed API:

```ts
export function toBeEmptyElement(
  this: jest.MatcherContext,
  element: ReactTestInstance
)
```

The matcher should:
1) Validate that it is invoked on a host element
2) Check if given element contains any host child elements (using `getHostChildren` fn)

Each matcher should have a fairly comprehensive test suite.

## Links

* `toBeEmptyDOMElement` matcher code from Jest DOM: https://github.com/testing-library/jest-dom/blob/main/src/to-be-empty-dom-element.js
* `toBeEmptyElement` implementation for Jest Native: https://github.com/testing-library/jest-native/blob/main/src/to-be-empty-element.ts

## Related Issues
#1454

**Comment by kyawthura-gg** [comment]
Hi @mdjastrzebski, I would like to work on this issue. Thanks

**Comment by mdjastrzebski** [comment]
@kyawthura-gg Go ahead! Pls submit PR when you're ready.

**Comment by mdjastrzebski** [comment]
🎉 Release in version: [v12.4.0](https://github.com/callstack/react-native-testing-library/releases/tag/v12.4.0)
