### ISSUE TITLE
feature: implement `toHaveAccessibleName` Jest matcher

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1503]
## Describe the Feature

[`toHaveAccessibleName`](https://github.com/testing-library/jest-dom#tohaveaccessiblename) is a Jest DOM matcher asserting that given element has certain accessible name: text content or a11y label.

RNTL already contains some code working with accessible name, namely `*ByRole` query accepts an optional [`name` param](https://github.com/callstack/react-native-testing-library/blob/a9f32a69e46bedc9413dd0bdf74637f7a3b2b579/src/queries/role.ts#L37). This matcher should compare expect name parameter with all of these:
1. text content of element referenced by `accessibilityLabelledBy` / `aria-labelledby` prop
2. `accessbilityLabel` / `aria-label` prop
3. text content of given element

These should be evaluated in that particular order.

## Possible Implementations
Proposed API:

```ts
export function toHaveAccessibleName(
  this: jest.MatcherContext,
  element: ReactTestInstance,
  expectedName?: TextMatch,
  options?: TextMatchOptions,
) 
```

The matcher should:
1) Validate that it is invoked on a host element
2) When `expectedName` param is provided check if it matches element's accessible name
3) When `expectedName` is not provided check if element has accessible name

Each matcher should have a fairly comprehensive test suite.

## Related Issues
#1454

**Comment by anishamalde** [comment]
I can do this!

**Comment by mdjastrzebski** [comment]
@anishamalde pls go ahead!

**Comment by anishamalde** [comment]
@mdjastrzebski 

Just checking did you mean for the proposed API to look like:

```
export function toHaveAccessibleName(
  this: jest.MatcherContext,
  element: ReactTestInstance,
  expectedName?: AccessibilityNameMatcher,
) 

```

**Comment by anishamalde** [comment]
@mdjastrzebski just double checking this is correct:

```
export function toHaveAccessibleName(
  this: jest.MatcherContext,
  element: ReactTestInstance,
  expectedName?: TextMatch,
  options?: TextMatchOptions,
) 
```

**Comment by mdjastrzebski** [comment]
Yes it's correct signature

**Comment by anishamalde** [comment]
I have completed the implementation with the exception of it getting labelled by the text content of **nested** element referenced by accessibilityLabelledBy / aria-labelledby prop.

https://github.com/callstack/react-native-testing-library/pull/1509

I tried the `getHostSiblings` but this just returns an empty array.

**Comment by mdjastrzebski** [comment]
@anishamalde you should be able to reuse [`matchLabelText`](https://github.com/callstack/react-native-testing-library/blob/a9f32a69e46bedc9413dd0bdf74637f7a3b2b579/src/helpers/matchers/matchLabelText.ts#L10C2-L10C2`) in order match both label and labelledBy props.

**Comment by anishamalde** [comment]
Just seen the function, thank-you, will update the PR!

**Comment by mdjastrzebski** [comment]
Resolved by https://github.com/callstack/react-native-testing-library/pull/1509

**Comment by mdjastrzebski** [comment]
🎉 Release in version: [v12.4.0](https://github.com/callstack/react-native-testing-library/releases/tag/v12.4.0)
