### ISSUE TITLE
*ByText cannot find text in React fragments when passed into the rendered element as a child component

### ISSUE THREAD

**Issue by islazh** [callstack/react-native-testing-library#1513]
## Describe the bug

`*ByText` methods cannot find text in fragments when the fragment is passed into `<Text />` as a child component.

## Expected behavior

`getByText` should be able to find the text that is passed into `<Text/>` component as a React fragment child component. 

## Steps to Reproduce

Minimal failing case:
```
    const BananaText = () => <>{'BANANA'}</>;
    const componentWithNonWorkingExpectation = render(
      <Text>
        <BananaText />
      </Text>,
    );

    // this fails unexpectedly
    expect(componentWithNonWorkingExpectation.getByText('BANANA')).toBeTruthy();
```

The text is present when `debug()` is used and is also present in the application.

As an aside, `*ByText` *can* find text in fragments when directly inside a component, e.g.
```
    const componentWithWorkingExpectation = render(
      <Text><>{'BANANA'}</></Text>,
    );
   // this passes
    expect(componentWithWorkingExpectation.getByText('BANANA')).toBeTruthy();
```

## Versions
11.2.0

**Comment by pierrezimmermannbam** [comment]
Hello @islazh, this test works on the current version, I believe it was fixed by #1222 so it should work if you upgrade to 11.5.0, let me know if upgrading does fix your problem

**Comment by islazh** [comment]
Great, thank you!

**Comment by pierrezimmermannbam** [comment]
You're welcome! I'm closing this issue then, will reopen if your problem persists after upgrading

**Comment by mdjastrzebski** [comment]
I've checked locally and it works now. Both for:
* ` const BananaText = () => <>{'BANANA'}</>;`
* ` const BananaText = () => 'BANANA';`
