### ISSUE TITLE
[Docs] Update page about host elements after v12 release

### ISSUE THREAD

**Issue by erheron** [callstack/react-native-testing-library#1541]
## Describe the bug
After v12 release, [the docs](https://callstack.github.io/react-native-testing-library/docs/testing-env#queries)  mention that: "**3. `*ByText, *ByDisplayValue, *ByPlaceholderText` queries now return host elements**"
Meanwhile, [the page about queries](https://callstack.github.io/react-native-testing-library/docs/testing-env#queries) mentions that the very same matchers below return composite elements and "There is an effort to make them to return host elemenst"

## Expected behavior
[Queries page](https://callstack.github.io/react-native-testing-library/docs/testing-env#queries) correctly mentions that all (?) queries now return host elements

**Comment by mdjastrzebski** [comment]
Updated the [docs](https://callstack.github.io/react-native-testing-library/docs/testing-env#queries). Thanks for catching this.
