### ISSUE TITLE
[react native 0.73] - require does not work

### ISSUE THREAD

**Issue by idrissakhi** [callstack/react-native-testing-library#1542]
## Describe the bug

const emailMailImage = require('assets/images/email-mail/mail.png');

const emailMailImageDimensions = Image.resolveAssetSource(emailMailImage);

TypeError: Cannot read properties of undefined (reading 'width')Jest

## Expected behavior

Tests passe on 0.72.X

## Steps to Reproduce

install react native 0.73.0 and run a test having 
```          <Image
            source={emailMailImage}
            resizeMode={'contain'}
            style={[
              styles.emailSentImage,
              {
                width: resizeEmailImageWidth,
                aspectRatio: emailMailImageDimensions.width / emailMailImageDimensions.height,
              },
            ]}
          />
          ```

## Versions

  npmPackages:
    @testing-library/react-native: 12.4.1 => 12.4.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.73.0 => 0.73.0 
    react-test-renderer: 18.2.0 => 18.2.0

**Comment by thymikee** [comment]
You'll likely need to mock `Image.resolveAssetSource` method to return something

**Comment by idrissakhi** [comment]
@thymikee but it was working fine on previous versions, also i saw the new react native changelog and no breaking change is introduced in this part

**Comment by thymikee** [comment]
It's possible it was unintended breaking change. To unblock yourself you could do something like:
```js
Image.resolveAssetSource = jest.fn(() => ({width: 128, height: 128}));
```
or use `jest.mock`/`jest.spyOn` if `jest.fn` won't work here

**Comment by mdjastrzebski** [comment]
Closing as it appears to be RN issue, not a RNTL one.

**Comment by jforaker** [comment]
Future googlers, @thymikee's solution worked in 2024 for react-native 0.73.0 and @testing-library/react-native@12.5.2
