### ISSUE TITLE
onEndReached on a FlatList is not being triggered anymore after a fireEvent.scroll

### ISSUE THREAD

**Issue by vanGalilea** [callstack/react-native-testing-library#1549]
## Describe the bug

`onEndReached` on a `FlatList` is not being triggered anymore after a `fireEvent.scroll`

## Expected behavior

`onEndReached` is called the way it used to work before

## Steps to Reproduce

Follow this [example](https://callstack.github.io/react-native-testing-library/docs/api/#on-a-flatlist) from the docs.
My test was something along the lines of:
```
import {FlatList, View} from 'react-native';
import {fireEvent, render, screen} from '@testing-library/react-native';

test('scrolls to bottom and loads more items', () => {
  const onEndReached = jest.fn();

  const eventData = {
    nativeEvent: {
      contentOffset: {
        y: 500,
      },
      contentSize: {
        // Dimensions of the scrollable content
        height: 500,
        width: 100,
      },
      layoutMeasurement: {
        // Dimensions of the device
        height: 100,
        width: 100,
      },
    },
  };
  render(
    <FlatList
      data={Array.from({length: 10}, (_, key) => ({key: `${key}`}))}
      renderItem={() => <View style={{height: 100, width: 100}} />}
      onEndReached={onEndReached}
      onEndReachedThreshold={0.5}
      testID="flat-list"
      initialNumToRender={5}
    />,
  );
  fireEvent.scroll(screen.getByTestId('flat-list'), eventData);
  expect(onEndReached).toHaveBeenCalled();
});
```

## Screenshots
N/A

## Versions
```
@testing-library/react-native: ^12.4.3 => 12.4.3 
react: 18.2.0 => 18.2.0 
react-native: 0.73.1 => 0.73.1 
react-test-renderer: 18.2.0 => 18.2.0 
```

## Side Note
- This occurred after upgrading RN from `0.72.4` to `0.73.1` so I'm suspecting its incompatible with RN's new version.
- `onScroll` is being called after a `fireEvent.scroll` in contrary to `onEndReached`

**Comment by mdjastrzebski** [comment]
@vanGalilea similar issue has been already solved. See issue #1540 for details and PR #1543 for fix (released in [v12.4.2](https://github.com/callstack/react-native-testing-library/releases/tag/v12.4.2))

**Comment by mdjastrzebski** [comment]
Note, we might need to update the [doc](https://callstack.github.io/react-native-testing-library/docs/api/#on-a-flatlist) you linked to.

**Comment by vanGalilea** [comment]
I'm gonna ra

> Note, we might need to update the [doc](https://callstack.github.io/react-native-testing-library/docs/api/#on-a-flatlist) you linked to.
I'll raise a PR to update the docs 👍🏻

**Comment by vanGalilea** [comment]
@mdjastrzebski I see that you removed the `Flatlist` examples in this [commit](https://github.com/callstack/react-native-testing-library/pull/1547/commits/e3b0b2319998dc5ef11f13cf70f6f2938d60b1c3) I've raised this pr #1551 for the time being, though I still haven't find a way testing whether `onEndReached` is being called after simulating a scroll to bottom.

**Comment by mdjastrzebski** [comment]
@vanGalilea you can try calling `fireEvent(element, 'endReached')`. It should raise `onEndReached` event on a `FlatList`. You might need to experiment with proper event payload though.
