### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by valn1** [callstack/react-native-testing-library#1557]
## Describe the bug

most of my tests broke after i upgraded react native on my project, i tried to debug and fix but could not get any progress on that

## Expected behavior

my tests should work again

## Screenshots

![image](https://github.com/callstack/react-native-testing-library/assets/40465512/11ecbb12-a1c9-4735-b31c-bcdd4b354583)

## Versions

  npmPackages:
    @testing-library/react-native: ^12.4.3 => 12.4.3 
    react: 18.2.0 => 18.2.0 
    react-native: ^0.73.2 => 0.73.2 
    react-test-renderer: 18.2.0 => 18.2.0

**Comment by valn1** [comment]
it looks like this change in my babel.config file caused the errors
![image](https://github.com/callstack/react-native-testing-library/assets/40465512/09e72ac4-1b9b-4974-981b-2b331bbefbb2)
i have no idea why tho, i imagine it should work fine

**Comment by valn1** [comment]
rolling that line back seems to have fixed the issue for me, but still, this should not happen.
i made that change because the react-native upgrade helper told me to do so. here is the commit in react-native that made that change from react-native  0.72.10 to 0.73.0
https://github.com/facebook/react-native/commit/d380bb8473f1c03ca277074e952f03649d767766

**Comment by mdjastrzebski** [comment]
@valn1, would you be able to produce a minimal reproduction repository based either on the latest RN CLI? It's hard to give any recommendation without being able to reproduce the issue you are having. That might also help you with diagnosing the issue.

**Comment by mdjastrzebski** [comment]
@pedrohamarques This looks like a potential setup issue, has RNTL generally supports the latest RN versions. In order to help you diagnose the issue, I would need to be able to reproduce it locally. Could you prepare a minimal reproduction repo?

**Comment by pedrohamarques** [comment]
Yeah, it was a wrong setup by my part. Following some tutorial I added the second and third preset in `babel.config`. I removed them and it worked properly. 

This was my file:

```javascript
module.exports = function (api) {
	api.cache(true);
	return {
		presets: [
			'babel-preset-expo',
			['@babel/preset-env', { targets: { node: 'current' } }],
			'@babel/preset-typescript',
		],
		plugins: ['nativewind/babel'],
	};
};
```

**Comment by abhishekgoel101** [comment]
Facing same issue

**Comment by Ajmal0197** [comment]
Same issue:

```
module.exports = {
  presets: [
    'module:@react-native/babel-preset',
    ['@babel/preset-env', { targets: { node: 'current' } }],
  ],
  plugins: ['react-native-reanimated/plugin'],
  env: {
    production: {
      plugins: ['transform-remove-console'],
    },
  },
};

```

**Comment by mdjastrzebski** [comment]
@valn1, @abhishekgoel101, @Ajmal0197 

I've deployed the latest RN CLI (RN ver. 0.73.6) and the tests work out of the box. I encourage you to setup clean RN CLI project in a separate the folder and compare the configs between your setup and RN CLI template.

For reference:

babel.config.js
```json
module.exports = {
  presets: ['module:@react-native/babel-preset'],
};
```

See this comment from @pedrohamarques that removing: `@babel/present-env` and `@babel/preset-typescript` solved this issue for him: https://github.com/callstack/react-native-testing-library/issues/1557#issuecomment-1944548458

**Comment by amashianov** [comment]
@mdjastrzebski 
Faced the same with the same `preset-env` plugins recommended by jest setup docs.

But new problem is if I remove it, jest/babel stops recognizing/transforming dependencies correctly, and uses a version of mobx-react-lite that expects `react-dom` ...

**Comment by antoniovuono** [comment]
I removed 

> @mdjastrzebski Faced the same with the same `preset-env` plugins recommended by jest setup docs.
> 
> But new problem is if I remove it, jest/babel stops recognizing/transforming dependencies correctly, and uses a version of mobx-react-lite that expects `react-dom` ...

same issue here ! I removed this line and the tests passed ...

```ts
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      'babel-preset-expo',
      // ['@babel/preset-env', { targets: { node: 'current' } }],
      '@babel/preset-typescript',
    ],
  };
};
```

**Comment by singhvijay0001** [comment]
Remove  

1. In babel.config.js
 remove 

presets: [
    'module:metro-react-native/babel-preset'] 

and replace this with 

 presets: [
    'module:metro-react-native-babel-preset'] 


2.
 Remove 
plugin: [    'react-native-reanimated/plugin', ]

This solved my issue
