### ISSUE TITLE
Incorrect automatic cleanup order

### ISSUE THREAD

**Issue by alpha0010** [callstack/react-native-testing-library#1565]
## Describe the bug

While  running tests, I get:

> ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.

This appears to be due to the `useEffect()` cleanup being called after Jest has done its own cleanup; manually `unmount()`ing the component before exiting the test resolves the issue.

This is problematic since `jest --runInBand` exits non-zero, causing pipeline failures (even though all tests pass).

## Expected behavior

Automatic cleanup has access to the Jest environment, so I do not need to manually `unmount()`.

## Steps to Reproduce

```tsx
// Add to `MyComponent`
  useEffect(() => {
    const handle = InteractionManager.runAfterInteractions(async () => {
      let nextFrame = new Promise((resolve) => requestAnimationFrame(() => resolve()));
      await nextFrame();
    });
    return () => {
      handle.cancel();
    };
  }, []);
```

```tsx
test('Render example', async () => {
  const {toJSON, unmount} = render( <MyComponent /> );

  expect(toJSON()).toMatchSnapshot();

  // Uncomment to resolve access Jest environment after teardown.
  //unmount();
});
```

## Versions

```
  npmPackages:
    @testing-library/react-native: ^12.4.3 => 12.4.3 
    react: 18.2.0 => 18.2.0 
    react-native: 0.73.4 => 0.73.4 
    react-test-renderer: 18.2.0 => 18.2.0 
```

**Comment by mdjastrzebski** [comment]
Closing as stale. Workaround available (manual calling of `unmount`.
