### ISSUE TITLE
Is it possible to run RNTL and RTL together on a Hybrid application?

### ISSUE THREAD

**Issue by alexborton** [callstack/react-native-testing-library#157]
I have two existing applications in separate code-bases that i would like to combine into a hybrid application (code-sharing for Web and Native).

Aside from the restructure to bring the two together, my major concern is running the Native and Web testing side-by-side. 

My Native (Expo) application is already setup with RNTL and running just as it should. 

Do you have an approach or any tips for consolidating or running Web and Native tests side-by-side?

The main problem i can see is where do i define the separate `render` functions to instruct Native or Web rendering.

Any help and guidance is appreciated

**Comment by thymikee** [comment]
You could define 2 [Jest projects](https://jestjs.io/docs/en/configuration#projects-array-string-projectconfig) with separate configurations, one would import native components, the other would import web components. You could use `moduleNameMapper` to override certain paths, if you care to have them the same, and they would resolve to different testing helpers.

Feel free to share more about your project specifics :)

**Comment by alexborton** [comment]
Thanks @thymikee for the quick response. I will take a look into that approach and let you know some of my findings. 

In honesty, configuration of Jest/RTL/RNTL is not something i have been heavily involved with, so it will all be pretty experimental for me. I was kind of hoping someone had already configured something similar already ;)

**Comment by thymikee** [comment]
Ping @alexborton have you managed to make it work? :) 
I'm gonna close this, but would be nice to link to a write-up on the topic.

**Comment by alexborton** [comment]
@thymikee the Hybrid approach is very much on our roadmap over the coming months, but as of yet, i don't have anything to add in terms of approach. 

As soon as i do, i will add some info to this issue for others looking to do something similar 👍

**Comment by abmantis** [comment]
@alexborton Hey, have you done it? :P 

Sorry to necro-bump...
