### ISSUE TITLE
getAllByTestId is missing

### ISSUE THREAD

**Issue by ccfz** [callstack/react-native-testing-library#161]
## Versions

    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-testing-library": "^1.6.0",
    "react-test-renderer": "^16.8.4"

## Description
getAllByTestId appears to be missing, it is listed as a query in the [docs](https://callstack.github.io/react-native-testing-library/docs/api-queries#bytestid).

<img width="400" alt="Screenshot 2019-04-24 at 13 28 58" src="https://user-images.githubusercontent.com/6050682/56656133-f8fc7b80-6694-11e9-9b16-ed0a26103377.png">

### src: 
```
import React from 'react';
import { Text, View } from 'react-native';

const OptionList = ({ options }) => {
  const renderOptions = (optionList) => {
    return optionList.map(visibleOption => (
      <Text
        key={option.id}
        testID="optionContainer"
      >
        {option.text}
      </Text>
    ));
  };

  return (
    <View>
      {renderOptions(options)}
    </View>
  );
};

export default OptionList;
```

### spec:
```
import React from 'react';
import { Text } from 'react-native';
import { render } from 'react-native-testing-library';

import OptionList from 'src/components/OptionList';

const buildTestProps = props => ({
  options: [
    { id: 1, text: 'Frodo Card' },
    { id: 2, text: 'Gandalf Card' },
    { id: 3, text: 'Sauron Card' },
    { id: 4, text: 'Elrond Card' },
    { id: 5, text: 'Pippin Card' }
  ],
  ...props
});

let props;
let wrapper;

beforeAll(() => {
  props = buildTestProps();
  wrapper = render(<SwipeSelect {...props} />);
});

describe('SwipeSelect', () => {
  it('renders the options', () => {
    expect(wrapper.getAllByTestId(Text).length).toEqual(5);
  });
});

```

**Comment by dev-evans** [comment]
Since get/queryByTestId uses findByProps under the hood and get/queryAllByProps is [being deprecated](https://github.com/callstack/react-native-testing-library/issues/163#issuecomment-487584089) in the next major version due to, I'm guessing, issues with the underlying findAllByProps from `react-test-renderer` (based on the comment below that one), I'm curious if this is something we'll even see added.

Might just be that it needs to be removed from the docs? Or is there an alternative plan to implement *AllByTestId functionality?

**Comment by ccfz** [comment]
Should definitely be removed from the docs if it is not implemented 😄. I tried finding an issue concerning querryAllByProps in react-testing-library but couldn't find any, which seems suspicious. in terms of where the root problem is located. I think we can close this issue, I might have a look at the code and see if I can figure out where the duplicity is coming from. FYI my workaround was using lodash's uniqby.

```
function getAllByTestId(id) {
  const instances = wrapper.getAllByProps({ testID: id });

  return uniqBy(instances, instance => instance.props.children);
}
```

**Comment by thymikee** [comment]
Yep, we should add that. Anybody willing to contribute? :)
