### ISSUE TITLE
Configuration option for customizing error output

### ISSUE THREAD

**Issue by th0r0nd0r** [callstack/react-native-testing-library#1616]
## Describe the Feature
TL/RTL has a config option called [getElementError](https://testing-library.com/docs/dom-testing-library/api-configuration/#getelementerror), that enables you to, among other things, [remove the long DOM output from error messages](https://stackoverflow.com/a/64155473/9238602). Is there any way I can accomplish this in RNTL?

**Comment by mdjastrzebski** [comment]
We do not have anything like this. Why would you be interested in such option?

**Comment by mdjastrzebski** [comment]
Closing as stale.
