### ISSUE TITLE
act is deprecated

### ISSUE THREAD

**Issue by Ejdamm** [callstack/react-native-testing-library#1621]
## Describe the bug

My IDE says: The signature (callback: () => VoidOrUndefinedOnly): DebugPromiseLike of act is deprecated.

react-testing-library had the same issue https://github.com/testing-library/react-testing-library/pull/1319/files

## Versions

  npmPackages:
    @testing-library/react-native: 12.5.0 => 12.5.0 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.16 => 0.71.16 
    react-test-renderer: 18.3.1 => 18.3.1

**Comment by mdjastrzebski** [comment]
@Ejdamm for a time being you should use both `react` and `react-test-renderer` in exact version `18.2.0`. Make sure you have exactly the same version of both of these packages.

Reference: https://react-native-community.github.io/upgrade-helper/?from=0.71.16&to=0.74.1

**Comment by Ejdamm** [comment]
Downgrading react-test-renderer to 18.2.0 didn't help but downgrading @types/react-test-renderer to 18.0.7 did the trick.

**Comment by mdjastrzebski** [comment]
Yeah, this is a typescript deprecation, so it makes sense.

We will support React 18.3.x & later React 19.x (`react`, `react-test-renderer`, `@types/...`, etc), when it's officially supported by React Native.

**Comment by cyberixae** [comment]
I still get `act` deprecation errors. I'm using `@testing-library/react-native` version 12.8.0`. The dependency listing states `"react": ">=16.8.0"` and `"react": "18.3.1"` is listed as a devDependency. I have `"react": "18.3.1"` installed.

**Comment by mdjastrzebski** [comment]
@cyberixae do now worry about this warning. We have plans to replace React Test Renderer with a new test renderer in the v14 release. See the [roadmap](https://github.com/callstack/react-native-testing-library/discussions/1698).

@Ejdamm For the time being you should use `react-test-renderer` in the exact version as the `react` package, otherwise it will not work.
