### ISSUE TITLE
Press event called when not passed down to event handler

### ISSUE THREAD

**Issue by DonBrody** [callstack/react-native-testing-library#1633]
## Describe the bug

Hi. I think I'm running into an issue where an `onPress` event is called even when it is not passed down as a prop, but only when including a wrapper component.

For example, the component below accepts an `onPress` prop through its interface, but never passes that prop down to its internal `Text` component:
```tsx
const _Text = React.forwardRef<Text, TextProps>(({ children }, ref) => (
  <Text ref={ref}>{children}</Text>
))
```
So we'd expect that the following would fail (and it does fail as expected):
```tsx
const mockOnPress = jest.fn()

const { getByText } = render(<_Text onPress={mockOnPress}>Test Text</_Text>)

fireEvent.press(getByText('Test Text'))

expect(mockOnPress).toHaveBeenCalled()
```
But the above will pass if a wrapper component is provided (even a simple one like below):
```tsx
 const Wrapper: React.FC<React.PropsWithChildren> = ({ children }) => children

const { getByText } = render(
  <_Text onPress={mockOnPress}>Test Text</_Text>,
  { wrapper: Wrapper },
)
```
Thank you in advance for any help you could provide here!

## Expected behavior

The test described above should fail.

## Steps to Reproduce

```tsx
it('should fire onPress callback', () => {
  const mockOnPress = jest.fn()

  const Wrapper: React.FC<React.PropsWithChildren> = ({ children }) => children

  const _Text = React.forwardRef<Text, TextProps>(({ children }, ref) => (
    <Text ref={ref}>{children}</Text>
  ))

  const { getByText } = render(
    <_Text onPress={mockOnPress}>Test Text</_Text>,
    { wrapper: Wrapper },
  )

  fireEvent.press(getByText('Test Text'))

  expect(mockOnPress).toHaveBeenCalled()
  expect(mockOnPress).toHaveBeenCalledTimes(1)
})
```

## Versions

`@testing-library/react-native` => `12.5.1`
`jest` => `29.7.0`
`react` => `18.3.1`
`react-native` => `0.73.7`

  npmPackages:
    react: ^18.2.0 => 18.3.1 
    react-native: ~0.73.7 => 0.73.7

**Comment by mdjastrzebski** [comment]
It seems that your custom `Text` component is not properly passing props to native `Text` component.
Is:
```ts
const _Text = React.forwardRef<Text, TextProps>(({ children }, ref) => (
    <Text ref={ref}>{children}</Text>
  ))
```

Should be:
```ts
const _Text = React.forwardRef<Text, TextProps>(({ children, ...rest }, ref) => (
    <Text ref={ref} {...rest}>{children}</Text>
  ))
```

**Comment by DonBrody** [comment]
Yup - the User Event API does properly handle this. We'll update our tests. Thanks for your help!
