### ISSUE TITLE
Featuring React Native Testing Library in Docusaurus

### ISSUE THREAD

**Issue by Hongarc** [callstack/react-native-testing-library#164]
Hello, we would like to feature your project to the Docusaurus users page.

Are you with me on this?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

I created Pull request facebook/Docusaurus#1419

**Comment by thymikee** [comment]
Sure!

**Comment by Hongarc** [comment]
![image](https://user-images.githubusercontent.com/19208123/56945125-2d1de380-6b50-11e9-8643-04138b820464.png)
