### ISSUE TITLE
Firing/Testing a function within a Class

### ISSUE THREAD

**Issue by alexborton** [callstack/react-native-testing-library#165]
I want to test a `handle...` function within a class. 

NB: This could be completely the wrong approach - please tell me if so. 

I have a container than renders a button which will navigate to a new screen, taking with it a callback function that is triggered on complete.

The function it transports should live in this container (i think) as it's logic is related.

The container class looks something like this;

```
class MyContainer extends React.Component {
  handleSomethingOnComplete = token => {
    const { someProps, myAction } = this.props
    myAction({ ...someProps, token })
  }

  render = () => {
    return (
      <React.Fragment>
      ....
        <ButtonPrimary
          onPress={() =>
            navigate(MyOtherScreen, {
              onSomethingComplete: this.handleSomethingOnComplete,
            })
          }
        >
          Cool button
        </ButtonPrimary>
        ...
      </React.Fragment>
    )
  }
}
```

I _think_ i want to write a test something like this;

```
  it('Does the write things when handleSomethingOnComplete is complete', () => {
      // i want to render <MyContainer /> and trigger the handleSomethingOnComplete function
  })
```
But i don't know how to trigger or fire the handleSomethingOnComplete function - or even if i should be. This function is important as the test here will test against saga and transformation logic.

**Comment by thymikee** [comment]
This is pretty deep integration test. I'd suggest using e2e testing for that. However, you can still do it with this library if you use JS-based navigation (like `react-navigation`.

You'll need to wrap your test components with a navigator, create `renderWithNavigation` that renders (with `render` helper) a small navigator with 2 routes you want to test with your base component being the first one to test.

I'm planning on adding docs for some common scenarios like this, but it will take some time and likely not happen before June (unless someone helps me on that :) )

**Comment by alexborton** [comment]
Thanks @thymikee 

I am not completely sure what steps you mean to take after the react-navigation has been mocked in? I already have RN mocked into a renderWithNavigation (as you suggested) for other testing scenarios;

```
const customRenderWithNavigation = (ui, options = {}) => {
  console.disableYellowBox = true

  const DefaultScreen = () => <View>{ui}</View>

  const AppNavigator = createStackNavigator({
    DefaultScreen,
  })

  const AppContainer = createAppContainer(AppNavigator)

  return render(
    <Provider store={store}>
      <IntlProvider locale="en" textComponent={Text}>
        <AppContainer />
      </IntlProvider>
    </Provider>,
    options,
  )
}
```

Not sure if that helps at all with the context of your explanation? :)
