### ISSUE TITLE
Add support for switch to toBeChecked matcher

### ISSUE THREAD

**Issue by sladek-jan** [callstack/react-native-testing-library#1656]
## Describe the Feature

- it would be possible to use the toBeChecked matcher for elements with the `switch` role

## Possible Implementations

- add 'switch' to the condition here: https://github.com/callstack/react-native-testing-library/blob/899de72aaf3c5e81363afd066c62e41fb64e2d2d/src/matchers/to-be-checked.tsx#L41

## Related Issues

https://github.com/callstack/react-native-testing-library/issues/1457

**Comment by mdjastrzebski** [comment]
I will have to consider what is the best value to solve the `Switch` checking problem.

The Switch component in React Native codebase does not actually rely on the `checked` state. See: https://github.com/facebook/react-native/blob/3350050edc6bdec1652448863ab0c6872d2ac4ed/packages/react-native/Libraries/Components/Switch/Switch.js#L188

It uses `value` for that, and setting this prop does to affect the `accessibilityState` prop:
```
        <RCTSwitch
          accessibilityRole="switch"
          onChange={[Function handleChange]}
          onResponderTerminationRequest={[Function returnsFalse]}
          onStartShouldSetResponder={[Function returnsTrue]}
          style={
            {
              "height": 31,
              "width": 51,
            }
          }
          testID="switch"
          value={true}
        />,
```

This is different then web, where `switch` role is related to the `checked` prop: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role

Perhaps this should (also) be handled at the RN repo level.

**Comment by mdjastrzebski** [comment]
Yeah, you have a point there. Let's fix it. 🔨

**Comment by sladek-jan** [comment]
Ok, thank you! For now, I solved it using this snippet as a workaround:

```
const expectSwitchToBeChecked = (instance: ReactTestInstance, checked: boolean) => {
    expect(instance.props.accessibilityState.checked).toBe(checked);
};
```

**Comment by mdjastrzebski** [comment]
@sladek-jan from my research, for native `Switch` element you should examine `element.props.value` instead of `accessibilityState` which afaik is not set by the `Switch` control itself.

**Comment by sladek-jan** [comment]
Ah, sorry for the confusion, we are using a design library in the project and under the hood, it renders a custom View with the role 'switch', which is controlled by setting the 'aria-checked' prop.
So my workaround probably doesn't apply to the real RN Switch.

**Comment by mdjastrzebski** [comment]
nvm, let's ship both `Switch` element and `switch` role 🤣
