### ISSUE TITLE
getInstance() vs getByType(Component)

### ISSUE THREAD

**Issue by mgcrea** [callstack/react-native-testing-library#175]
## Ask your Question

I've seen that you've explicitly removed the `getInstance()` API, as it implied testing implementation details. However isn't it equivalent to just do `getByType(Component)`? How would you "properly" test a onClick handler, eg. the case below:

Might be nice to add "guides" to the doc on how to properly test such basic cases as it looks like you have quite thought about it.

Thanks for the lib!

```jsx
  describe('onPress prop', () => {
    it('should properly call callback', () => {
      const onPressSpy = jest.fn();
      const {getByType, toJSON} = render(<ModalInputButton title="My Title" onPress={onPressSpy} />);
      expect(toJSON()).toMatchSnapshot();
      fireEvent.press(getByType(ModalInputButton));
      expect(onPressSpy).toHaveBeenCalledTimes(1);
    });
  });
```

Component:

```jsx
// @source https://github.com/facebook/react-native/blob/master/Libraries/Components/Button.js

import React, {FunctionComponent} from 'react';
import {
  TouchableOpacity,
  ViewStyle,
  Platform,
  View,
  ButtonProps,
  TouchableNativeFeedback,
  StyleProp
} from 'react-native';
import styled, {css} from 'styled-components/native';

const ModalInputButton: FunctionComponent<ButtonProps & {containerStyle?: StyleProp<ViewStyle>}> = ({
  onPress,
  title,
  containerStyle,
  ...otherProps
}) => {
  const formattedTitle = Platform.OS === 'android' ? title.toUpperCase() : title;
  return (
    <ButtonTouchable onPress={onPress}>
      <View style={containerStyle}>
        <ButtonText {...otherProps}>{formattedTitle}</ButtonText>
      </View>
    </ButtonTouchable>
  );
};

export default ModalInputButton;

const ButtonTouchable = styled(Platform.OS === 'android' ? TouchableNativeFeedback : TouchableOpacity)`
  border-radius: 12px;
  overflow: hidden;
`;

const ButtonText = styled.Text`
  text-align: center;
  /* flex: 0 0 auto; */
  padding: 8px;
  ${Platform.select({
    ios: css`
      color: #007aff;
      font-size: 18px;
    `,
    android: css`
      color: #009688;
      font-size: 16px;
      text-transform: uppercase;
      font-weight: 600;
    `
  })};
`;
```

**Comment by thymikee** [comment]
The test like this have no point, because you're testing React, not your component. The idea is that the component renders actual Views and Texts etc, that are supposed to render to native ones – and these are the handles you should check. 

I'd use `getByText` in this scenario: 
```js
fireEvent.press(getByText(formattedTitle));
```
as this is what your user does – press on the text (or a button with a text)

**Comment by Varmakswiggy** [comment]
I want to access the getInstance Method in the react testing library, 
Is getInstance() method available in the react-test-renderer. 
Is there a way to getInstance using React testing library?

**Comment by AugustinLF** [comment]
> The main purpose that i want getInstance is for accessing all component properties, like methods return inside components also

Then `@testing-library/react-native` is not the library for you :) This library aims to hide react internals on purpose, because in our view, that's not what you should test. You can read more on react testing library's [guiding principles](https://testing-library.com/docs/guiding-principles) to better understand the reasoning.

**Comment by mdjastrzebski** [comment]
@Varmakswiggy you can use `react-test-renderer` directly if needed.
