### ISSUE TITLE
Test fails when component includes react native vector icon children

### ISSUE THREAD

**Issue by rafaalb** [callstack/react-native-testing-library#177]
## Versions

React: 16.8.3
React native: 0.59.3
React native testing library: 1.7.0
## Description
When i try to run a snapshot test, and the rendered component has a react-native-vector-icons children, the test fails.

![Screenshot 2019-05-23 at 5 42 53 PM](https://user-images.githubusercontent.com/9601447/58266572-37638400-7d82-11e9-87c1-9263ab4d6697.png)

## Reproducible Demo

I have the following code:

`import Entypo from 'react-native-vector-icons/Entypo'
import { render } from 'react-native-testing-library'

const AdmissionDate = () => (
 <View>
  <Entypo name="chevron" />
</View>
)

describe('Admission Date tests', () => {
  test('should render', () => {
    const { toJSON } = render(<AdmissionDate />)
    expect(toJSON()).toMatchSnapshot();
  })
})`

**Comment by thymikee** [comment]
This is a native library and you need to mock it

**Comment by rafaalb** [comment]
Any example on how to mock a native library? I tried creating a __mock__ folder at same level than node_modules, but i have no experience doing this.

**Comment by thymikee** [comment]
@rafaalb please check Jest docs on mocking, it's all there :) https://jestjs.io/docs/en/manual-mocks
