### ISSUE TITLE
Any way to fire swipe event?

### ISSUE THREAD

**Issue by terreb** [callstack/react-native-testing-library#193]
I'm using native-base library swiperow component and looking to test for a function to be called on swipe. I'm trying 

```
    const eventData = {
          nativeEvent: {
               translationX: 200
           },
       };
    fireEvent( el, 'pan', eventData )
```

...but not to avail. I'm getting ` No handler function found for event: pan`

**Comment by thymikee** [comment]
Seems like there's no such event on SwipeRow component? https://docs.nativebase.io/Components.html#swipeable-single-def-headref

**Comment by terreb** [comment]
I see, but they have `onRowOpen` property and that's where I have my function. Do I understand right that the only way to test my function to be called is to call onRowOpen directly? How do I do that with react-native-testing-library? I don't see it exposes an instance of the rendered component...

**Comment by thymikee** [comment]
```js
fireEvent(el, 'rowOpen', eventData);
```

**Comment by terreb** [comment]
Ahh sure, thank you!

**Comment by TigranKhachatryan2000** [comment]
Hi, using `screen.getByRole('complementary')` I get SwipeWithAction component, in this case how to test  fireEvent.swipe case?

it('Should check handlePopupChange function work', () => {
    const { asFragment } = render(<TextContent name="inbox" {...props} />, {
      providers,
    });

    expect(asFragment()).toMatchSnapshot();

    const swipeItem = screen.getByRole('complementary');

    fireEvent.swipe(swipeItem);

    expect(mockOpenPopup).toBeCalled()
    screen.debug();
  });
