### ISSUE TITLE
Any way of triggering the onValueChange event of a Picker element?

### ISSUE THREAD

**Issue by reaktivo** [callstack/react-native-testing-library#197]
## Describe the Feature
Not a feature request per se. Just wanted to ask if there's a recommended way of calling the onValueChange event on the Picker element

**Comment by thymikee** [comment]
Hey! There's no recommended way. You should be good using something like: 
```js
fireEvent(pickerItem, 'onValueChange', {someData})
```

**Comment by armandomagalhesJEAN** [comment]
SOOOO HOW IS IT TO PUSH YOUR SHIT ON OTHERS? ​​​​​​​
HELLO!! LOOKING FOR A GREAT BLOWJOB?? CALL CAROLINE +33661818188 OR VERO +33667301419!! OR CONTACT THEIR SLUTTY FRIEND @IRINAKS1 ;) THEY KNOW HOW TO SUCK WELL!! JEAN BAUDIN KNOWS THAT FOR SURE! HE ENJOYED THE CAROLINE THE MOST !! DON’T BELIVE? CALL HIM AND ASK +31657697635 or +31655935354 XOXO

**Comment by armandomagalhesJEAN** [comment]
SOOOO HOW IS IT TO PUSH YOUR SHIT ON OTHERS? ​​​​​​​
HELLO!! LOOKING FOR A GREAT BLOWJOB?? CALL CAROLINE +33661818188 OR VERO +33667301419!! OR CONTACT THEIR SLUTTY FRIEND @IRINAKS1 ;) THEY KNOW HOW TO SUCK WELL!! JEAN BAUDIN KNOWS THAT FOR SURE! HE ENJOYED THE CAROLINE THE MOST !! DON’T BELIVE? CALL HIM AND ASK +31657697635 or +31655935354 XOXO

**Comment by sammysium** [comment]
> 
> ## Describe the Feature
> 
> Not a feature request per se. Just wanted to ask if there's a recommended way of calling the onValueChange event on the Picker element

Ever solved that? I get TypeError: Cannot read property 'charAt' of undefined when I do fireEvent(pickerItem, 'onValueChange', {someData})

**Comment by lukewlms** [comment]
So far we're just mocking the Picker component with a `TextInput`, but it's messy.  I have to translate the `onChange` call to pass an index into the callback.  Would be great to know if someone has a specific example of selecting the Picker control and calling `fireEvent` to manipulate it.

**Comment by sammysium** [comment]
I think I have got it to work. I will check and update you.
