### ISSUE TITLE
Asserting that scroll events happen

### ISSUE THREAD

**Issue by OzzieOrca** [callstack/react-native-testing-library#202]
## Ask your Question

Say I have a component that calls https://facebook.github.io/react-native/docs/flatlist#scrolltoindex either on mount or when a specific user interaction happens. How can I assert that `scrollToIndex` has been called/that the scroll has happened?

We have an old enzyme test that dug into the implementation, replaced that function with `jest.fn()`, and asserted that it was called with the correct params. What's the correct approach for testing in a similar way to what the user would experience? There doesn't seem to be any kind of `window.scrollY`/`element.scrollTop` equivalent in React Native.

**Comment by thymikee** [comment]
That's a good question. For now, I'd make the scrollToIndex handler injectable via props (with a default prop value of what you have there already). Then you'll be able to replace it with `jest.fn()` in the test.

Ideally we should be able to check if the element is visible on the screen. However, we're likely hitting JS<->Native limitations here, as we'd need to account for screen size, and `onLayout` which is not available in JS. Would make more sense to make it an e2e test.
