### ISSUE TITLE
How deep do we render components

### ISSUE THREAD

**Issue by jdmg94** [callstack/react-native-testing-library#224]
## Ask your Question
I am writing tests for a component that contains `react-intl` components for pluralization.

in this specific scenario I intend to get text content of `1 Night • 1 Adult` from a Text component whose children holds a couple of template literals and a couple of `FormattedPlural` for pluralization.

the resulting children looks something like this: 
```
 {
      children: [
        '1 ',
        {
          '$$typeof': Symbol(react.element),
          type: [Function],
          key: null,
          ref: null,
          props: [Object],
          _owner: [FiberNode],
          _store: {}
        },
        ' • 1 ',
        {
          '$$typeof': Symbol(react.element),
          type: [Function],
          key: null,
          ref: null,
          props: [Object],
          _owner: [FiberNode],
          _store: {}
        }
      ]
    }
```

I can pass these components through the render function again and I will get a proper test instance, however shouldn't this be the case already? It feels unsustainable

**Comment by jdmg94** [comment]
I've uploaded a repo to replicate the issue described: https://github.com/jdmg94/react-native-intl-test-instance-bug

I created a custom matcher to achieve the desired result, if you use the regular matcher `toHaveTextContent` it will skip the formatted components, if you inspect the children you'll see the elements that got skipped where not rendered, they don't yet have the `children` prop and that is why the regular matcher doesn't work, my question is shouldn't all children be rendered by `react-test-renderer`?

**Comment by thymikee** [comment]
We rely on `react-test-renderer` for this, which renders everything to host components. If the component is not rendered, maybe there's a reason for that?

With this library, if you want to find text, you need to go with:
```js
getByText('1 Night • 1 Adult')
```
and expect it not to throw, as it only throw if the text is not found.
You definitely shouldn't render recursively, because it's already handled by the test renderer.
