### ISSUE TITLE
Is CreateNodeMock supported?

### ISSUE THREAD

**Issue by leeferfeefer** [callstack/react-native-testing-library#227]
Is CreateNodeMock supported?

I am not sure if I am using this wrong, but I am trying to mock a ref method. According to the API for the render function, it states:

```javascript
function render(
  component: React.Element<any>,
  options?: {
    /* A React Component that renders `component` as children */
    wrapper?: React.ComponentType<any>,
    /* You won't often use this, but it's helpful when testing refs */
    createNodeMock: (element: React.Element<any>) => any,
  }
): RenderResult {}
```

I am passing in the options like so (which I got from [react-test-renderer](https://reactjs.org/docs/test-renderer.html#testrenderercreate)) 

```javascript
const options = {
   createNodeMock: (element) => {
      console.log("element", element);
      return {
         takePictureAsync: takePictureMock
       };
    }
};

const {getByType, queryByTestId} = render(<Camera/>, options);
```

I never see the console.log print anything and I cannot find a test in render.test.js that covers the use of CreateNodeMock.

**Comment by thymikee** [comment]
We pass it to react-test-renderer, but it doesn't seem to work with react-native, at least the last time I tried to use it. Didn't dig it too much though. We'd be glad if you helped us get it working :)

**Comment by leeferfeefer** [comment]
I see. So react-test-renderer doesn't interact with it?

**Comment by thymikee** [comment]
That's how I recall it

**Comment by leeferfeefer** [comment]
Ok well thanks for the info. I will see if I can find anything

**Comment by leeferfeefer** [comment]
I'm going to close this for now and reopen later if I have any insight in this issue. Thanks for the quick replies!

**Comment by almeynman** [comment]
For those who will encounter this problem in the future.

Worked around it by
1. Introduce a useRef optional prop and by default use react's one
```
import React, { useRef as defaultUseRef } from 'react'
const component = ({ useRef = defaultUseRef }) => {
  const ref = useRef(null)
  return <RefComponent ref={ref} />
}
```
2. in test mock useRef
```
...
    const useRef = () => {
      return Object.defineProperty({}, 'current', {
        get: jest.fn(() => ({ refFunction: jest.fn() })),
        set: () => {}
      });
    }
    render(
      <ScanBarcodeView onScan={handleScan} useRef={useRef} />,
    )
...
```
