### ISSUE TITLE
Is getAllByType limited to returning 10 elements?

### ISSUE THREAD

**Issue by leeferfeefer** [callstack/react-native-testing-library#228]
I am not sure if this is how the API works or if its based on my component tree, but is the use of getAllByType limited to retrieving only 10 elements? Does it only return visible elements? Visible as in to the user, not in terms of existing in the tree.

**Comment by leeferfeefer** [comment]
Ah so by default, flatlist renders only 10 items. ```initialNumToRender``` is a prop that you can change.

https://facebook.github.io/react-native/docs/flatlist#initialnumtorender

**Comment by mym0404** [comment]
Thank you. I stuck testing the `FlatList` pagination function with `limit = 10`.
I could solve with your answer.
