### ISSUE TITLE
React Paper Snackbar doesn't get retrieved using any of getBy* queries

### ISSUE THREAD

**Issue by anothersaddeveloper** [callstack/react-native-testing-library#229]
## Versions

react@16.8.3
react-test-renderer@16.8.3
react-native@0.59.10
react-native-paper@2.16.0
react-native-testing-library@1.11.1

## Description

The render function does not fully render all of the components for Snackbar from React-native-paper dependency. Even though it doesn't, it still should retrieve component with accessibility label, but for some reason it doesn't. I have tried all of the queries within the library, only getByType returns the Snackbar, but the fireEvent function won't make it

## Reproducible Demo

https://codesandbox.io/s/react-native-eqkbu

Snackbar.test.tsx, it does not work on the sandbox because of dependency issues, but if you try to run the test on your machine it won't work

**Comment by MattAgn** [comment]
I haven't yet tried  with your version of the packages but at least it works with the most recent versions:
    - "react": "16.9.0",
    - "react-native": "0.61.5",
    - "react-native-paper": "3.6.0",
    - "react-native-testing-library": "1.12.0"
	- "react-test-renderer": "16.12.0",

![image](https://user-images.githubusercontent.com/32499425/73786504-b9bd9800-4799-11ea-8a76-e1057cadf531.png)
