### ISSUE TITLE
How to get text as string from node children 

### ISSUE THREAD

**Issue by automatensalat** [callstack/react-native-testing-library#230]
Hi there, 

I switched over from Enzyme for my current RN project and I'm wondering how to handle a specific assertion. 

Say I have a component like this: 
```tsx
const MyComponent = ({ value }) => {
  return <Text testID="text">Value is {value}</Text>;
}
```

I now want to test that the component renders the value in the Text node:
```tsx
const renderer = render(<MyComponent value="xyz" />);
const text = renderer.getByTestId("text");
expect(text.props.children).toBe("Value is xyz");
```
However, the test fails: `Expected: "Value is xyz", Received: ["Value is ", "xyz"]`

In Enzyme there is a .text() method on the node which flatly returns the text contained in the child. Is there a way to do this smoothly in react-native-testing-library? 
Of course I could change the component to use string templates or reduce the `props.children` in the test method to a string myself, just wondering if there is a better way.

**Comment by thymikee** [comment]
Are you using the latest version? I think we fixed that: https://github.com/callstack/react-native-testing-library/pull/132

**Comment by automatensalat** [comment]
I'm using v1.11.1 which seems to be the latest version. 

The PR you liked to is very similar to my question, however the changes are only related to the `getNodeByText` method, i.e. searching for a node by its text. 

My use case is slightly different: I already have a node which I find e.g. with its `testID`, now I want to assert against its properties, which is the text in this case. It's basically the reverse as what's described in the PR.

**Comment by thymikee** [comment]
Oh, so there's nothing really we can do in the library. You check for `text.props.children`, which we don't alter, so either create a custom matcher that would do what you expect, or assert on an array.
