### ISSUE TITLE
snapshot has more instances than actual render

### ISSUE THREAD

**Issue by deepakaggarwal7** [callstack/react-native-testing-library#231]
## Ask your Question

    "react": "16.9.0",
    "react-native": "0.60.5",
    "react-native-swiper": "https://github.com/deepakaggarwal7/react-native-swiper/tarball/master",
 
I've created a swiper with two text elements. When I run the application, two items are rendered as expected. However, my unit test fails as it gets 4 text items. using more console, I found that the componentTree generated by render has a duplicate pair of the two text nodes causing the total length to be 4 whereas expected is 2.

component looks like:
```
<View style={{ marginTop: 10, height: 450 }}>
            <Swiper>
                <View><Text>1</Text></View>
                <View><Text>2</Text></View>
            </Swiper>
        </View>
```

and the test looks like:
```
 it('should render a swiper with as many children as questions length',()=>{
        const {getAllByType} = componentTree;
        let AllTextElements = getAllByType(Text);
        console.log(_.map(AllTextElements,e=>(e.props)))
        expect(AllTextElements).toHaveLength(2) //FAILS
    })
```
and the log shows:
```
    [
      { children: '2' },
      { children: '1' },
      { children: '2' },
      { children: '1' }
    ]
```

**Comment by thymikee** [comment]
A lot of "swipers" out there create duplicates for continuous scrolling. Isn't this the case?

**Comment by thymikee** [comment]
Also, please don't rely on ByType, or ByProps matchers. They have issues and we're going to deprecate them. See: https://github.com/callstack/react-native-testing-library/issues/139 – it's likely connected.

**Comment by deepakaggarwal7** [comment]
> A lot of "swipers" out there create duplicates for continuous scrolling. Isn't this the case?

The problem is that ultimately what is rendering is different than what debug() returns. I see only two items getting rendered but this library returns me 4 which means there's some gap between ultimate output and what library returns

**Comment by thymikee** [comment]
What happens if you inspect the hierarchy in React Devtools? Is it only 2 items, or 4 there? Without a repro we can download it's hard to tell the actual issue.

**Comment by deepakaggarwal7** [comment]
Makes sense! Thanks. Going off-topic (feel free to ignore), I wonder that in your documentation, there's always a reference to a QuestionBoard app, but I could never find that sample code. Could you please suggest if it is accessible to us?

**Comment by deepakaggarwal7** [comment]
Solved. The problem was with swiper. Whenever swiper children > 1, it would add a hidden child at the start and at the end for loop. I set the loop={false} property after which it started working fine.
THE ISSUE WASN'T WITH react-native-testing-library

**Comment by thymikee** [comment]
Awesome, thanks for getting back with it, appreciated :)
