### ISSUE TITLE
Invariant Violation: Unable to find node on an unmounted component. When Using fireEvent.press

### ISSUE THREAD

**Issue by LeoMosiah** [callstack/react-native-testing-library#236]
## Unable to find node on an unmounted component.
I am getting this error when I try to press my TouchableOpacity component on my tests. My test looks like this:
```js
const [manaColorCheckbox, manaIndentityCheckbox] = getAllByText(
      WHITE_MANA_COLOR_CHECKBOX_TEXT,
    );
    fireEvent.changeText(searchCardInput, SEARCH_INPUT);
    fireEvent.press(searchButton);
    fireEvent.press(manaColorCheckbox);
    fireEvent.press(manaIndentityCheckbox);
```
![image](https://user-images.githubusercontent.com/37636805/69055957-c11ca300-09ed-11ea-8de1-cce297ebd743.png)

https://github.com/mtg-community/trading-card-manager/blob/bc99849b3f66596af97ce49ef309139376ff920d/packages/frontend/src/presentation/screens/__tests__/cardSearchFilter.test.tsx#L153-L205

Can someone help me?

**Comment by evargast** [comment]
@LeoMosiah  were you able to solve this ?

**Comment by gusbmurphy** [comment]
I just came across this issue because I was running into a similar one with this block of code:

```
const minuteInput = getByA11yLabel(minuteInputA11yLabel);
const hourInput = getByA11yLabel(hourInputA11yLabel);
const numOfMinutes = randomIntFromInterval(5, 30);
const numOfHours = randomIntFromInterval(1, 3);
fireEvent.changeText(minuteInput, numOfMinutes.toString());
fireEvent.changeText(hourInput, numOfHours.toString());
```

Producing this error:

```
Unable to find node on an unmounted component.

      307 |     const numOfHours = randomIntFromInterval(1, 3);
      308 |     fireEvent.changeText(minuteInput, numOfMinutes.toString());
    > 309 |     fireEvent.changeText(hourInput, numOfHours.toString());
          |               ^
      310 |
      311 |     nextButton = getByA11yLabel(nextButtonA11yLabel);
      312 |     fireEvent.press(nextButton);
```

For some reason, I've solved this by changing that block around to look like this:
```
const minuteInput = getByA11yLabel(minuteInputA11yLabel);
const numOfMinutes = randomIntFromInterval(5, 30);
fireEvent.changeText(minuteInput, numOfMinutes.toString());

const hourInput = getByA11yLabel(hourInputA11yLabel);
const numOfHours = randomIntFromInterval(1, 3);
fireEvent.changeText(hourInput, numOfHours.toString());
```

This leads me to believe that there's something going on with calling consecutive `fireEvent` methods (in my case, `changeText`, in the original post's case, `press`), but I am entirely unsure! Hopefully this can be helpful to someone else down the road.

**Comment by thymikee** [comment]
I bumped into this error when version of `react-test-renderer` was 17, while React was on 16. Please make sure they're in sync

**Comment by gusbmurphy** [comment]
> I bumped into this error when version of `react-test-renderer` was 17, while React was on 16. Please make sure they're in sync

@thymikee I'm running into this with `"react": "16.13.1"` and `"react-test-renderer": "16.13.1"`.
