### ISSUE TITLE
How to trigger View onLayout event

### ISSUE THREAD

**Issue by acollazomayer** [callstack/react-native-testing-library#240]
I dont know if it is a bug or not, But I have a onLayout event on a screen that is setting some value in the store. When I first render the view with the render function, the onLayout event is not triggering.

I tried to call a custom event onLayout but is not working either. Any suggestions

**Comment by thymikee** [comment]
Since you're not in a native environment, the onLayout is not triggering, because there's no layout phase. You'll need to mock it

**Comment by acollazomayer** [comment]
@thymikee please dont close the issue, any help with this. Ok I mock it, but how do I trigger it

**Comment by sregg** [comment]
I have the same need 
see https://github.com/FaridSafi/react-native-gifted-chat/issues/1637

![image](https://user-images.githubusercontent.com/1479283/87824739-d3cccd80-c843-11ea-9f3d-91f7f19370b3.png)


![image](https://user-images.githubusercontent.com/1479283/87824689-bc8de000-c843-11ea-945e-b34c70a98aa4.png)
