### ISSUE TITLE
How to get element on react native navigation header

### ISSUE THREAD

**Issue by hengvenchang** [callstack/react-native-testing-library#243]
Great Library! I enjoy using it so far, but i came across this problem that i have to access a component on navigation header:

export default class AddAlarmScreen extends Component {
  static navigationOptions = () => {
    return {
      headerTitle: 'Add New Alarm',
      headerRight: (
        <TouchableOpacity        
          testID="addIconButton"
          <Text>Save</Text>
        </TouchableOpacity>
      ),
    };
  };
};

here's my test:

 it('It save new alarm when save button is click', () => {
          fireEvent.press(getByTestId('addIconButton'));
  });

The test fail with a response "No instances found"

So i wonder is there anyway to get access to element that render on navigation?

**Comment by thymikee** [comment]
You need to render your component inside navigator context. Something like this (here I a:
```js
export const renderWithNavigation = (component, options) => {
  const Navigator = createAppContainer(
    createSwitchNavigator({
      Root: () => component
    })
  );
  return render(<Navigator />, options);
};
```

**Comment by hengvenchang** [comment]
Ma Man! Thank you so much
