### ISSUE TITLE
Blog post about testing

### ISSUE THREAD

**Issue by sweatC** [callstack/react-native-testing-library#245]
## Describe the Feature
I am writing a blog post about the modern way of testing React Native apps and want to include one paragraph about `react-native-testing-library` as a unit testing tool.

## Possible Implementations
I need one well-described paragraph about your tool and one simple example of using.
Instead, I want you to promote my article on your site or blog.

**Comment by thymikee** [comment]
Thanks, I'm happy to put the article somewhere on the docs, but unfortunately I don't have time to write the paragraph for you. Feel free to use existing resources in the current docs, it's all there really :)
