### ISSUE TITLE
Unable to get AnimatedOpacity

### ISSUE THREAD

**Issue by deepakaggarwal7** [callstack/react-native-testing-library#247]
I want to test a button with visibility toggle based on isVisible prop (Buttin has no text). As most of the recommended queries are text driven (which doesn't exist in my comp), I opted for test ID. I wanted to test that based on the ```isvisible``` property, animated opacity value is either 0 or 100.

TEST
```
describe('FloatingButton', () => {
  it('isVisible is set to false', () => {
    const { debug, getByTestId, toJSON } = render(
      <FloatingButton isVisible={false} testID="floatingButton1" />
    )
    expect(toJSON().children[0].props.style.opacity).toEqual(0) //WORKS
   
    console.log(
      getByTestId('floatingButton1').children[0].children[0].props.style
    ) // DOESN'T RETURNS VALUE
  })

})
```

 I reckon toJSON() is more for debug and shouldn't be used for an assertion. Hence, I wanted to refer the component and then drill to its opacity value. However, I've tried all options, but couldn't get the value as toJSON easily does. First, you need to find the children and then getting the style returns AnimatedValue object instead of the value
```
[
      undefined,
      {
        opacity: AnimatedValue {
          _listeners: {},
          _children: [Array],
          _value: 1,
          _startingValue: 1,
          _offset: 0,
          _animation: null
        }
      }
    ]
```
Please help me with three questions:
1. Is my understanding to NOT use toJSON() for assertion is right?
2. When there's no text in component, using testid and drilling to the nested chidren is the only way? It is tedious as it sometimes need several rounds of console.log to find right child.
3. How can I get opacity value in code above instead of animated object

Followig is the component code.
```
// @flow
import React, { Component, useEffect, useState } from 'react'
import { Text, Animated, StyleSheet, TouchableOpacity } from 'react-native'
import { Colors } from '../../styles'

type Props = {
  onPress: Function,
  text: string,
  isVisible: boolean
}

const FloatingButton = (props: Props) => {
  const [opacityValue, setOpacityValue] = useState(0)

  useEffect(() => {
    setOpacityValue(props.isVisible ? 100 : 0), [props.isVisible]
  })

  return (
    <TouchableOpacity style={styles.TouchableOpacityStyle}>
      <Animated.View
        style={[
          styles.MainContainer,
          {
            opacity: opacityValue
          }
        ]}
      />
    </TouchableOpacity>
  )
}

const styles = StyleSheet.create({
  MainContainer: {
    position: 'absolute',
    width: 50,
    height: 50,
    backgroundColor: Colors.Red,
    right: 30,
    bottom: 30,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center'
  },

  buttonText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: Colors.White
  }
})

export { FloatingButton }

```

**Comment by thymikee** [comment]
Hey! Can you provide a minimal repro we can download and verify?

**Comment by thymikee** [comment]
You need to pass the `testID` prop to the native `TouchableOpacity` component.

**Comment by sobernaut** [comment]
@thymikee This does not answer the question above.

**Comment by thymikee** [comment]
@sobernaut please create a new issue with a clear description and repro steps :)
