### ISSUE TITLE
Should and how to test redux  connected components?

### ISSUE THREAD

**Issue by deepakaggarwal7** [callstack/react-native-testing-library#248]
As component testing doesn't include full app, there's no store. Based on my search, some suggest not to do component testing of redux connected components and to do ETE testing instead (which makes many components out of component testing scope) OR use mock to test (which might dilute the essence of component testing where an event in one makes some change in other)
Could you please share some opinions on using react-native-testing-library for redux connected components?

thanks

**Comment by thymikee** [comment]
You can expose a custom render which wraps your component with a custom provider, like: 

```jsx
const provideReduxStore = (
  component: React.Element<any>,
  preloadedState?: { [key: string]: mixed }
) => {
  const { store } = configureStore(preloadedState);
  return <Provider store={store}>{component}</Provider>;
};

type Options = {
  createNodeMock?: (element: React.Element<any>) => any,
  wrapper?: React.ComponentType<any>
};

const renderWithRedux = (
  component: React.Element<any>,
  options?: Options,
  storeOptions?: { preloadedState?: Object } = {}
) => render(provideReduxStore(component, storeOptions.preloadedState), options);
```

and then use `renderWithRedux` instead of original `render` where applicable.
