### ISSUE TITLE
`getByType` not working on memoized component

### ISSUE THREAD

**Issue by karlmarxlopez** [callstack/react-native-testing-library#252]
## Versions

`1.12.0`

## Description
This is similar to [react-test-renderer issue](https://github.com/facebook/react/issues/17301)

## Reproducible Demo
```tsx
import React, {FC, memo} from 'react';
import {render} from 'react-native-testing-library';

const Foo: FC =  memo(() => null);

const Bar:FC = () => <Foo/>;


it('should render Foo', ()=> {
       const {getByType} = render(<Bar />);

     expect(getByType(Foo)).toBeDefined();
});

```

**Comment by thymikee** [comment]
As you noticed, it's an upstream issue in `react-test-renderer`, which we depend on. This is not actionable.
