### ISSUE TITLE
Question: how to mock UI Manager?

### ISSUE THREAD

**Issue by artyorsh** [callstack/react-native-testing-library#256]
## Ask your Question

Hi! 

I need help. Any chance to mock UI Manager with Jest? My setup requires mocking `measureInWindow` and probably `findNodeHandle` to perform testing components that relies on this module and native measurements.

What I do (here `Modal` is a custom component)

```js
jest.mock('react-native/Libraries/ReactNative/UIManager', () => {
  const UIManagerModule = jest.requireActual('react-native/Libraries/ReactNative/UIManager');
  return {
    ...UIManagerModule,
    measureInWindow: (node, callback) => {
      callback(0, 0, 42, 42);
    },
  };
});

const TestModal = (props) => (
  <Modal {...props}>{props.children}</Modal>
);

it('should render content when visible', async () => {
  const component = render(
    <TestModal visible={true}>
      <Text>I love Jest</Text>
    </TestModal>,
  );

  const content = await waitForElement(() => component.queryByText('I love Jest'));
  expect(content).toBeTruthy();
});
```

But this seems not to work, since making query with `getBy` api  throws and `queryBy` always returns null even when it should not.

Sorry if it is not the right place for asking. Can I get some help with it?

**Comment by thymikee** [comment]
Don't test private APIs like jest.mock('react-native/Libraries/ReactNative/UIManager')
UIManager is exposed through `react-native` and that's what you need to mock

Example:
```js
jest.mock("react-native", () => {
  const RN = jest.requireActual("react-native");

  RN.UIManager.getViewManagerConfig = name => {
    return {};
  };

  Object.defineProperty(RN, "findNodeHandle", {
    get: jest.fn(() => () => 1),
    set: jest.fn()
  });

  return RN;
});
```

**Comment by artyorsh** [comment]
Many thanks @thymikee, you made it work 👍

**Comment by myou11** [comment]
Hi @thymikee, how would you go about mocking [this part of a popover library](https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Utility.ts#L10-L22) I'm trying to use?

Before mocking anything, I tested triggering the popover upon a long press but got this error:
```
TypeError: _reactNative.NativeModules.UIManager.measure is not a function
```

So I tried to mock the react native module similar to what you are doing above. This is what I have currently:
```js
jest.mock("react-native", () => {
  const RN = jest.requireActual("react-native");
  RN.UIManager.getViewManagerConfig = (name) => {
    return {};
  };
  Object.defineProperty(RN, "findNodeHandle", {
    get: jest.fn(() => () => 1),
    set: jest.fn(),
  });

  RN.NativeModules.UIManager = {
    //   measure: jest.fn(),
    measure: (node, callback) => {
      callback(undefined, undefined, 0, 0, 0, 0);
    },
  };

  return RN;
});
```

I am getting an error from the popover library saying: `getRectForRef - current is not set`, which is [line 19 from the popover Utility file](https://github.com/SteffeyDev/react-native-popover-view/blob/master/src/Utility.ts#L19). Before the mock, the code was able to get past the `if (ref.current)` check, but after mocking, that if statement no longer passes, hence we get the error.

If you have some time, could you help me figure this out please? Thanks in advance!

**Comment by silvapereiraeduardo** [comment]
Hi, I tested both solutions, but the following error is still returning me when running tests with jest:
`TypeError: _reactNative.NativeModules.UIManager.measure is not a function`
can anybody help me?

```shell
✗ npx react-native info 
info Fetching system and libraries information...
System:
    OS: macOS 13.6.1
    CPU: (10) x64 Apple M2 Pro
    Memory: 73.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/eduardosilvapereira/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**Comment by retyui** [comment]
In case of usage of modern version of React Native:

```tsx
  const x = 1;
  const y = 2;
  const width = 30;
  const height = 40;
  const pageX = 500;
  const pageY = 600;

  jest
    .mocked(View.prototype.measure)
    .mockImplementation((callback) => callback(x, y, width, height, pageX, pageY));

  render(<View ref={(instance) => instance?.measure(console.log)} />); // log: 1 2 30 40 500 600
```
