### ISSUE TITLE
Cleanup the Readme and setup docs website with Docusaurus

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#26]
There's a lot of information in the Readme right now. We should move the API and examples into separate files and then maybe generate a website out of it with Docusaurus.

**Comment by thymikee** [comment]
Would also be cool to mention Rally. 
cc @FLGMwt, feel free to send a PR with a wording of your preference :)

**Comment by brooksbecton** [comment]
Docusaurus creates a new website with it's own package.json
Here is an example of the structure: https://docusaurus.io/docs/en/installation#verifying-installation

Are ya'll wanting to keep this Docusaurus site within this repo or have a seperate repo for the doc site? 

I was just going move stuff into a "docs/" folder, but having 2 package.jsons seemed weird to me. 

Any thoughts on where to put this site?

**Comment by thymikee** [comment]
Thanks for offering help!
I'm cool with this sitting in `docs/` directory, no need to sync between repos. 
cc @Esemesek as he started to work on this but didn't have time to finish.

**Comment by thymikee** [comment]
FYI @brooksbecton #70 brings `docs/api.md` to the table. So adding Docusaurus should be easier once that's merged.

**Comment by thymikee** [comment]
Awesome! Can you send a PR btw?

**Comment by thymikee** [comment]
#74 by @brooksbecton is merged, which means we have a website set up (but not running yet)! Now we need to polish it a bit, add nice icons, and publish. Anybody interested in doing so? 😃

**Comment by thymikee** [comment]
The website is started and lives under `website/` directory. We need to:

- clean it up from Docusaurus defaults
- set up a task for publishing docs to `gh-pages`

After we have docs set up and deployed to `gh-pages` branch, I'm planning to write a series of common examples for "how to write test for this use case".

I'd greatly appreciate help on the mentioned topics :)
