### ISSUE TITLE
Add more examples 

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#27]
There's never too little. As a part of it we could show examples with Redux, Apollo, Relay, React Navigation, etc.

**Comment by sibelius** [comment]
Relay Modern example here https://github.com/entria/ReactNavigationRelayModern/pull/32

not working yet \o/

any help is appreciated

**Comment by thymikee** [comment]
I have no experience with Relay. I've checked out the code and it looks like `UserList`'s `render` method is not being called for some reason (perhaps `UserListPaginationContainer` is not calling it?). Try to investigate that.

You can also use `debug.deep(renderedComponent)` to take a look what's rendered.

**Comment by LaurenceRolandJames** [comment]
I've added an example with redux integration here: https://github.com/LaurenceRolandJames/react-native-testing-library-redux-example

Feel free to use it however you wish.

**Comment by thymikee** [comment]
Awesome, thank you @LaurenceRolandJames!

**Comment by thymikee** [comment]
Closing this, since we now have more specific issues like #281 or #280
