### ISSUE TITLE
Creating an example directory in root folder

### ISSUE THREAD

**Issue by cross19xx** [callstack/react-native-testing-library#279]
## Describe the Feature

As a way to improve the documentation, we will place an example directory in the project root so that people can simply clone from this either onto their local machine or into CodeSandbox.

**Comment by thymikee** [comment]
Would be lovely to have "Open in CodeSandbox" badge in the readme 🚀 https://twitter.com/dferber90/status/1252876456394289153

**Comment by thymikee** [comment]
This is already happening, and we have Redux and React Navigation guides for starters
