### ISSUE TITLE
Include an example for mocking native modules

### ISSUE THREAD

**Issue by cross19xx** [callstack/react-native-testing-library#282]
## Describe the Feature
As part of the examples being created, please include an example of mocking native modules.

**Comment by thymikee** [comment]
FYI, you may find this helpful: https://github.com/facebook/react-native/issues/28839#issuecomment-625453688 in the meantime, or as a reference to contribute the example.

**Comment by JanithaR** [comment]
Right now I'm struggling with a case where I subscribe to a native event emitted when barcodes are read. And I'm clueless how I should go about testing my screen component. I'm tempted to use Enzyme and call the callback function but it feels so wrong to do so.

**Comment by thymikee** [comment]
The native component would call some method or event handler normally. Do the same thing in your test and imporatively call such method on your native module mock. Your component should pick up on that change.

**Comment by JanithaR** [comment]
The drawback with what you propose is there's no way to change the returned value over time. 
Ex./ Subscribing to the 'barcodeScanSuccess' event and then simulate scanning more than one barcode.
Or I'm missing something trivial.

However, I was able to resolve my problem by mocking NativeEventEmitter.

**Comment by thymikee** [comment]
> However, I was able to resolve my problem by mocking NativeEventEmitter.

That's also a viable option, all depending on the internals of native modules you test :)

**Comment by mdjastrzebski** [comment]
Closing as stale.
