### ISSUE TITLE
Don't use *ByTestId queries in documentation examples

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#283]
## Describe the Feature

A few examples in the documentation use `getByTestId` and alike. We need to get rid of that and change to safer queries, because querying by `testID` encourages low-quality tests.

**Comment by cross19xx** [comment]
This has been addressed in PR #294

**Comment by alexakasanjeev** [comment]
> because querying by testID encourages low-quality tests.

@thymikee Could you please explain reason for your above statement, why `testID` encourages low-quality tests?

**Comment by thymikee** [comment]
@alexakasanjeev because a user can't interact with it, which may result in having a positive test for an interaction that may never happen. `testID` may be useful at times, but it should be avoided.

**Comment by alexakasanjeev** [comment]
@thymikee sorry, I didn't quite get it, could you state an example where it may render positive test but user will never interact with it
