### ISSUE TITLE
Add FindBy* queries

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#296]
## Describe the Feature
The original React Testing Library uses findBy* queries for async element queries ([docs](https://testing-library.com/docs/dom-testing-library/api-queries#findby)). Essentially it combines getBy* query with waitFor, providing a cleaner shorter syntax for async queries.

Using findBy* queries is mentioned as high importance pattern by @kcdodds in [this article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library).

## Possible Implementations
Implemented probably as a combined getBy* and waitForElement.

## Related Issues
Not known.

**Comment by thymikee** [comment]
Yea let's do it!
