### ISSUE TITLE
Ability to query children of given element

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#297]
## Describe the Feature
In certain scenarios it is useful to restrict query to only a part of component tree.
Sample use cases:
1. when displaying a `FlatList` of items we might want to find a certain item and query for some views inside it
2. when rendering multi-screen integration test using react-navigation and navigating from list screen to details screen. The global query still returns elements from hidden master screen. Forcing test code to use getAllBy* with arbitrary indices instread of getBy* queries.

## Possible Implementations
DOM/React Testing Library provides [`within`/`getQueriesForElement`](https://testing-library.com/docs/dom-testing-library/api-helpers#within-and-getqueriesforelement-apis) for such use case. 

```typescript
const boundQueries = within(getByA11yHint('Some Item'));
expect(boundQueries.getByText('Some text')).toBeTruthy();
```

Alternative would be to provide query functions accepting container element as one of their parameters e.g. `getByText(container, text)` as in DOM Testing Library.

## Related Issues
Not found.

**Comment by thymikee** [comment]
I think I like the `within` helper more, let's implement it 👍
