### ISSUE TITLE
Make sure we support @testing-library/jest-native

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#298]
## Describe the Feature
Current set of jest matchers is limited only to the base ones provided by jest. This makes simple queries like checking the text content of found element rather non-intuitive be directly working with its `children` prop.

The @testing-library/jest-native adds a number of useful React Native specific queries like: toHaveTextContent, toHaveStyle, toBeEnabled/Disabled, etc. 

Such addition is motivated by providing the best potential developer experience for RNTL users. 

As a reference point, the original React Testing Library includes @testing-library/jest-dom dev dependency.

## Possible Implementations
Add @testing-library/jest-native to dev dependencies. 

Alternatively, we can document existence of this related package and provide a suggestion to use it with RNTL as a suggested practice.

## Related Issues
None.

**Comment by mdjastrzebski** [comment]
cc @thymikee

**Comment by thymikee** [comment]
We should include this as our dev dependency, write some smoke tests, and provide documentation in Getting Started guide and Readme (they're similar) on how to include it. Should be opt in though
