### ISSUE TITLE
render does not return the renderer

### ISSUE THREAD

**Issue by wKovacs64** [callstack/react-native-testing-library#32]
The [`render` section of the README](https://github.com/callstack/react-native-testing-library/blob/6097c8f64ce6ad0b3626e2616615d74d73318b22/README.md#render) says:

> For convenience it also returns react-test-renderer's instance and renderer objects, in case you need more control.

But [it doesn't](https://github.com/callstack/react-native-testing-library/blob/6097c8f64ce6ad0b3626e2616615d74d73318b22/src/render.js#L18). But it should! 🙂 Looks like they were removed in e6ac5ad9977b81619ddf1e7cbdeb98cf553c82a8, but I think they would be valuable (at least `renderer`). Was there a reason they were removed?

PR incoming to add them back.

**Comment by thymikee** [comment]
Renderer was removed so you're not allowed to access the component internal instance. What's your use case?

**Comment by wKovacs64** [comment]
The getBy APIs weren't finding something that I knew was there, so I needed to debug to see what react-native-testing-library was seeing. I was able to figure it out* using `renderer.toJSON()` (after modifying my local node_modules `render.js` to include `renderer`).

(* react-native's jest setup script was mocking out ScrollView, but that's neither here nor there)

**Comment by thymikee** [comment]
Closing, as we've moved the discussion to the mentioned PR and changed the scope of the ticket.
