### ISSUE TITLE
Reorganize internal queries code by predicate typ

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#325]
## Describe the Issue

Current queries are organized in files by return type (`getByAPI.js`, `queryByAPI.js`, `findByAPI.js`) with exception for `A11yAPI.js` which is organized by predicate (byA11yLabel, byA11yHint, etc). Generally `getBy` and `getAllBy` queries are used as core query, with `queryBy`/`queryAllBy` and `findBy`/`findAllBy` as manually written wrappers around `getBy`/`getAllBy` quries.

There is a lot of repeated code, especially in duplicate `getBy` and `getAllBy` queries as well as manual `queryBy`/`queryAllBy`/`findBy`/... wrappers. 

This presents an opportunity to refactor queries so that for each predicate type (`ByText`, `byA11yLabel`, etc) there is only function encoding the search algorithm, while all other functions are generated by some generic code.

In Testing Library this is achieved by implementing query predicates as `queryAll` function first, and then using generic [`buildQueries` function](https://github.com/testing-library/dom-testing-library/blob/master/src/query-helpers.js) that returnes `getBy`/`getAllBy`/etc variants.

## Benefits

1. Single definition of each predicate, so avoiding recent `getByTestId`/`getAllByTestId` differences.
1. Easier creation of additional predicates, you just need to create `queryAll` version and all other queries will generated for you by `buildQueries` function.
1. Reduced code side

## Downsides
None found yet.

## Considerations
1. This change should not change the API
1. We should keep the same unit tests, but we might reorganize them by predicate vs by return type to match new queries file structure.
1. Queries performance should be the same, because `react-test-renderer` `find` uses `findAll` under the hood without any query optimization.
1. Typescript typings tests should probably stay the same, i.e. repeated use-case statements, and not be generated for code correctness reasons.

**Comment by thymikee** [comment]
Good call, let's do it.

> 3. Queries performance should be the same, because react-test-renderer find uses findAll under the hood without any query optimization.

This is an implementation detail. I guess that in some far-away future some optimizations may be added, but it's not the case now, and I don't think it has any priority. Once RTR does that, we can think about including these optimizations.

**Comment by MattAgn** [comment]
I'd be glad to lend a hand on this issue @thymikee @mdjastrzebski. I could try to do it for one query before validating with you, what do you think?

**Comment by thymikee** [comment]
@MattAgn lovely!

**Comment by michaelduminy** [comment]
It looks like the PRs above have changed the results of the API. Before these changes the `getBy` functions would be:
```ts
try {
  return instance.find((node) => getNodeByText(node, text));
} catch (error) {
  throw new ErrorWithStack(
    prepareErrorMessage(error, 'text', text),
    getByTextFn
  );
}
```

I assume this returns the first result that satisfies the condition.

Compare this to the new `getBy` function:
```ts
const results = queryAllByQuery(instance)(args);

if (results.length > 1) {
  throw new ErrorWithStack(getMultipleError(args), getFn);
}

if (results.length === 0) {
  throw new ErrorWithStack(getMissingError(args), getFn);
}

return results[0];
```

In this case, the API contract is different since now an error is thrown if the query finds more than 1 result. This might be an improvement since it is clearer and more aligned with dom-testing-lib but it is _different_.

In the project I'm working on this forces us to re-write our queries from:
```ts
// FROM
const { getByText } = render(<MyComponent />)
await fireEvent.press(getByText('.cancel'))

// TO
const { getAllByText } = render(<MyComponent />)
await fireEvent.press(getAllByText('.cancel')[0])
```

Granted this is because we have a design system that results in multiple elements being detected (a button element + a label for the button = 2 results). This is just in case anyone else comes across this.

**Comment by michaelduminy** [comment]
> Queries performance should be the same, because react-test-renderer find uses findAll under the hood without any query optimization.

I don't think this is correct - `find` calls `findAll(predicate, {deep: false})` which doesn't recursively search through children ([source](https://github.com/facebook/react/blob/1a3f1afbd3cf815d4e55628cd7d84ef20171bab8/packages/react-test-renderer/src/ReactTestRenderer.js#L340)).

If this search is synchronous this might explain why on super deep render trees (like those used in the app in which I work) some tests can take 15s to complete, even if the test timeout is 5s.

**Comment by thymikee** [comment]
@mdjastrzebski 👍🏼

**Comment by MattAgn** [comment]
Yes sounds good! I can take care of the first item -> "Replace GetByAPI, QueryByAPI and FindByAPI types and functions (xxxByAPI) with per query type (ByXxx) interfaces"

**Comment by mdjastrzebski** [comment]
@MattAgn could you do PR review for #965 first?

**Comment by MattAgn** [comment]
Sure on it!

**Comment by thymikee** [comment]
https://github.com/callstack/react-native-testing-library/pull/965 is merged. Anyone willing to port a11y queries? :)

**Comment by mdjastrzebski** [comment]
@MattAgn you wanted to volunteer so let me know if you want to pick it up :-)

Couple of thoughts on that topic:
1. `makeA11yQuery.ts` has too much abstractions inside, so it's not a good model for code that is easy to reason.
2. Each a11y query should be put into separate file in `src/queries` folder, e.g. `src/queries/labelText.ts`
3. The file should resemble current `testId.ts` structure. So that we first have `queryAllByXxx` predicate with accompanying `getMultipleError` and `getMissingError` which we pass to `makeQueries` to get derived queries (`getBy`, etc), and finally we export `ByTestIdQueries` type `bindByTestIdQueries` function.
4. That means that from the existing a11y code we are only interested in extracting logic for `queryAllByXxx` predicates. 
5. Aliases should be made by hand, as it is easier to understand:
```
export const bindByTextQueries = (
  instance: ReactTestInstance
): ByTextQueries => {
  const boundGetBy = getBy(instance),
  //...

  return {
    getByLabelText: boundGetBy,
    getByA11yHint: boundGetBy,
  // ...
  }
}
```

Little repetition hurt nobody, unlike too much abstraction.

**Comment by MattAgn** [comment]
@mdjastrzebski yes i'm on board with all your points
is it alright if I tackle that next week?

**Comment by mdjastrzebski** [comment]
@MattAgn that works for me 👍🏻

**Comment by MattAgn** [comment]
@mdjastrzebski should we close this issue now that our [PR](https://github.com/callstack/react-native-testing-library/pull/977) is merged?
