### ISSUE TITLE
Deprecate `flushMicrotaskQueue`

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#339]
## Summary

Writing async tests using `flushMicrotasksQueue` is quite not intuitive, as there are better alternatives available like `waitFor` or `findBy` queries. Similar function while contained in RTL is not exported from it.

Let's deprecate it in 2.x release and the remove it in 3.x. Users still relying on it, will be able to replace it with copy-paste implementation.

**Comment by mdjastrzebski** [comment]
cc @thymikee @cross19xx @Esemesek

**Comment by thymikee** [comment]
Closed via #340
