### ISSUE TITLE
testing not finishing...

### ISSUE THREAD

**Issue by kkh975** [callstack/react-native-testing-library#345]
## Versions
I just used under command.
> npx react-native init AwesomeProject

## Description
My Simple Components(.tsx) is:
```
import React, { useCallback, useState } from 'react';
import { TouchableHighlight, Text, View } from 'react-native';
import CheckBox from '@react-native-community/checkbox';

const FormCheckbox: React.FC<Props> = ({
  value = false,
  label = '',
  onChanged,
}) => {
  const [thisValue, setThisValue] = useState(value);
  const onPressed = useCallback(() => {
    const newValue = !thisValue;
    setThisValue(newValue);
    onChanged && onChanged(newValue);
  }, [onChanged, thisValue]);

  return (
    <View style={styles.wrap}>
      <TouchableHighlight onPress={onPressed} testID="CheckBoxTouch">
        <CheckBox value={thisValue} testID="CheckBox" />
      </TouchableHighlight>
      {label.length > 0 && (
        <TouchableHighlight onPress={onPressed} testID="CheckBoxLabel">
          <Text style={styles.input} testID="CheckBoxLabelText">
            {label}
          </Text>
        </TouchableHighlight>
      )}
    </View>
  );
};
```

and Test Code(.tsx) is:
```
import React from 'react';
import { render, fireEvent, act } from 'react-native-testing-library';
import FormCheckbox from '../../src/common/FormCheckbox';

describe('FormCheckbox component', () => {
  it('기본 동작', () => {
    let targetValue;
    const mockFn = jest.fn((v) => (targetValue = v));
    const result = render(<FormCheckbox label="test" onChanged={mockFn} />);
    const checkboxTouch = result.getByTestId('CheckBoxTouch');
    const checkbox = result.getByTestId('CheckBox');
    const text = result.getByTestId('CheckBoxLabelText');

    expect(checkbox.props.value).toBe(false);
    expect(text.children).toEqual([label]);

    fireEvent.press(checkboxTouch);

    expect(mockFn).toBeCalledTimes(1);
    expect(targetValue).toBe(true);
  });
})
```

but result is:
<img width="326" alt="스크린샷 2020-05-25 오후 3 47 26" src="https://user-images.githubusercontent.com/1680132/82786164-0f2fc900-9e9f-11ea-8ce0-4c84e81e0aa7.png">

It was not finish ;;;

**Comment by thymikee** [comment]
I'm sorry, but the screenshot clearly shows that the test run was finished. There is no snapshots in your examples, so there's none in the summary.

**Comment by kkh975** [comment]
It just looks like that because it is terminated by memory out.

**Comment by thymikee** [comment]
I can't see that from your post.

**Comment by kkh975** [comment]
![image](https://user-images.githubusercontent.com/1680132/82789089-ab100380-9ea4-11ea-8c70-0f275979d7dd.png)

**Comment by thymikee** [comment]
Try newer version of Node (if latest 12 won't work, try 14). It's possible that your machine has too little RAM for V8 to execute the tests that depend on React dependencies (Jest transpiles a lot with Babel and keep all of that in the memory).
If it only happens with this library, try plain "react-test-renderer", it's probably going to be the same, because we mostly forward to its APIs.

**Comment by kkh975** [comment]
Hum.. I updated to version 14 but it is the same. (My Mac has 16G 2400, DDR4)
I will try to "react-test-renderer". 
Thanks~

**Comment by kkh975** [comment]
Hi, @thymikee 
I finally realized what wrong.
Under code fired Loop.
```
expect(text.children).toEqual([label]);
```

**Comment by thymikee** [comment]
Glad you worked it out!
