### ISSUE TITLE
check if a matching node doesn't exist

### ISSUE THREAD

**Issue by iconicsammy** [callstack/react-native-testing-library#351]
Hi,

Perhaps this is found somewhere else but I couldn't find one. My scenario is straight forward: 

 expect(UNSAFE_getByType(ComponentName)).toEqual(undefined)

I want to make sure the ComponentName doesn't exist. The above fails because ComponentName doesn't exist indeed (no instance with node exists error) but it should pass. Currently I am doing it in a trycatch but I was wondering if there is a way to do it?

**Comment by thymikee** [comment]
You can use `toThrow` Jest matcher:
```js
expect(() => UNSAFE_getByType(ComponentName)).toThrow("instances not found")
```
or use `queryByType` and assert `.toEqual(null)`
