### ISSUE TITLE
getByText No instances found error

### ISSUE THREAD

**Issue by alexakasanjeev** [callstack/react-native-testing-library#359]
## Ask your Question
I'm writing a simple Button component , which has a prop loading, if loading is send true, `Text` component is not rendered, in place of it a loader is rendered. I want to test, if I pass `loading` prop true, the `Text` component is not rendered but I'm getting `No instance found` when using `getByText`

**MyButton.js**
```jsx
const MyButton = ({ title, loading, onPress }) => (
    <TouchableOpacity onPress={onPress} accessible accessibilityRole="button">
         {!loading && (<Text>{title}</Text>)}
         {loading && (<ActivityIndicator />)}
    </TouchableOpacity>
);
```

**MyButton.test.js**
```js
test('loading state is handled', () => {
    // Setup
    const buttonTitle = 'Press me';
    const { getByText } = render(<MyButton loading={true} title={buttonTitle} onPress={() => {}} />);

    // Exercise
    const textElement = getByText(buttonTitle);

    // Verify
    expect(textElement).toBeUndefined();
  })
```

But I'm getting `No instances found` error

![Screenshot from 2020-05-30 10-08-14](https://user-images.githubusercontent.com/13250741/83319640-ef612200-a25d-11ea-9a07-c0b0e5faaf32.png)

**Comment by thymikee** [comment]
`loading` is true, so text doesn't render and hence `getByText` throws an error. 

From the docs:

> getBy* queries return the first matching node for a query, and throw an error if no elements match or if more than one match is found (use getAllBy instead).

If you want to verify the text is not there, use `queryByText`

**Comment by alexakasanjeev** [comment]
Thank you
