### ISSUE TITLE
Tests using React Navigation (including examples in documentation) fail with ForwardRef(NavigationContainer) error

### ISSUE THREAD

**Issue by wwdrew** [callstack/react-native-testing-library#360]
## Versions

react: 16.11.0
react-native: 0.62.2
react-native-testing-library: 2.0.0
react-navigation/native: 5.5.0
react-navigation/stack: 5.4.1

## Description

I've created a new RN project (0.62.2) and installed 2.0.0 of react-native-testing-library and the latest React Navigation. To test them out, I've recreated the two examples from here (https://callstack.github.io/react-native-testing-library/docs/react-navigation), but every time I run I get this error:

```
PASS  src/screens/tests/AppNavigator.spec.js
  ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:131
      Warning: An update to ForwardRef(NavigationContainer) inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in ForwardRef(NavigationContainer)
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:131
      Warning: An update to ForwardRef(NavigationContainer) inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in ForwardRef(NavigationContainer)
```

I've tried on my own tests as well and I get the same error.

## Reproducible Demo

Create a new repo and add the example tests.

**Comment by thymikee** [comment]
Yea, we need to replace `getBy` queries with `await findBy`. Would you like to do that change? :)

**Comment by wwdrew** [comment]
You are a legend, that worked!

For being so awesome, I'd absolutely be happy to do that change! Shall open a PR asap!

Thank you again so much!

**Comment by thymikee** [comment]
Ace attitude!
