### ISSUE TITLE
How to test styles

### ISSUE THREAD

**Issue by QuevedoIB** [callstack/react-native-testing-library#367]
Good morning and thanks for the library, I've been reading the documentation and I didn't see any reference about how to test a rendered component styles, is there any way to achieve that using react-native-testing-library? Any help is highly appreciated, thanks and have a nice day!

**Comment by thymikee** [comment]
There's a couple of ways:
1. Use snapshot testing (but be cautious not to produce snapshots larger than you're able to review)
2. The queries return a TestRendererInstance, which has access to `props` so you can always check if the `props.style` has been set properly. `style` is a public API of almost all core React Native components, so you shouldn't be worried about accessing it.

Ideally a `.toHaveStyle()` custom matcher could be created inside https://github.com/testing-library/jest-native, which would access the `props.style` under the hood, so you don't have to worry about it. I'd appreciate if you opened an issue there so somebody, someday can implement it :)

**Comment by QuevedoIB** [comment]
Thanks a lot, .toHaveStyle is what I've tried but I see it's not yet implemented so I'll open the issue there and see If someone can implement it, meanwhile I will go for the second option you mentioned, again thanks a lot!.

**Comment by sammysium** [comment]
@QuevedoIB how did you end up doing this? I see .toHaveStyle in the jest-native library but for some reason, it is undefined when used in my test coverage. @thymikee any input?

**Comment by thymikee** [comment]
@sammysium feel free to open an issue with detailed repro in jest-native repository. Maybe even you could investigate and fix it? :)
