### ISSUE TITLE
Allow debug() to return HTML (not only print)

### ISSUE THREAD

**Issue by petrkrejcik** [callstack/react-native-testing-library#386]
## Describe the Feature
Allow users to get the output of `debug()` as a regular string.
My use case is that I would like to see the HTML in a regular browser rather than in a terminal.

## Possible Implementations
Add `return format(instance)` to `debugDeep` and `debugShallow`.

**Comment by thymikee** [comment]
I'm not sure I understand your intention. The `debug` already returns a string (but colored with ansi codes). Can you provide an example that makes it clearer?

**Comment by petrkrejcik** [comment]
I am developing my native app in a browser (using Expo) and in my test I would like to do:
```js
const html = debug()
```
and then send this html to a browser to see what's actually rendered. It's easier for me to visually check in a browser what's rendered rather than reading the output of `debug` in a terminal.

I do the same in RTL (using `container.innerHTML`) but maybe I was too eager in writing this feature request because I didn't realised that `debug` returns RN elements rather than HTML elements. And I'm not sure how to convert them by myself because Expo does that for me under the hood. 

Sorry for being too eager, I'm closing it.
