### ISSUE TITLE
@react-native-community/netinfo: NativeModule.RNCNetInfo is null. To fix this issue try these 

### ISSUE THREAD

**Issue by RicardoBrito1938** [callstack/react-native-testing-library#389]
Hello Guys, sorry if that is dumb question, i am trying to configure and start working with tests, in the first case i just wanted to know if the component is capable of rendering so i wrote the following test

```import 'react-native';
import React from 'react';

import QuizFeedBannerComponent from '../../app/components/QuizFeedBannerComponent';
import { render } from '@testing-library/react-native';

describe('QuizFeedBannerComponent', () => {
  it('I renders correctly', () => {
    render(<QuizFeedBannerComponent />);
  });
});
``` 

but i got the following error, i tried to rebuild the project, but error persists, see the error below, if there is further info i can provide, please let know

 FAIL  __tests__/components/QuizFeedBannerComponent.test.js
  ● Test suite failed to run

    @react-native-community/netinfo: NativeModule.RNCNetInfo is null. To fix this issue try these steps:

    • Run `react-native link @react-native-community/netinfo` in the project root.
    • Rebuild and re-run the app.
    • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
    • Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
    * If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-netinfo

      at Object.<anonymous> (node_modules/@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.ts:15:9)
      at Object.<anonymous> (node_modules/@react-native-community/netinfo/lib/commonjs/internal/state.ts:11:1)

**Comment by thymikee** [comment]
Hey! This library is `react-native-testing-library` and you're using similar `@testing-library/react-native`. Nonetheless, you need to mock the RNCNetInfo native module. They provide docs on how to do that: https://github.com/react-native-community/react-native-netinfo#errors-while-running-jest-tests :)

**Comment by RicardoBrito1938** [comment]
> Hey! This library is `react-native-testing-library` and you're using similar `@testing-library/react-native`. Nonetheless, you need to mock the RNCNetInfo native module. They provide docs on how to do that: https://github.com/react-native-community/react-native-netinfo#errors-while-running-jest-tests :)

Thank you Very much!!
