### ISSUE TITLE
Unable to return a match if wrapped in any kind of <Provider />

### ISSUE THREAD

**Issue by bjjeong** [callstack/react-native-testing-library#418]
I'm running into a strange problem whenever I try to test a component that is wrapped in any type of Provider (`react-redux`, `react-native-safe-area-context`, `styled-components`).

When I run the following test, it successfully passes as expected,
```javascript
test('Sample test', async () => {
    const component = (
        <View>
            <Text>Hello</Text>
        </View>
    );
    const { queryByText } = render(component);
    const element = await queryByText('Hello');
    expect(element).toBeTruthy();
}
```

However, as soon as I wrap the component in a Provider, the query returns no matches. This goes the same with all the other types of `queryBy` and `getBy` matchers.

```javascript
test('Sample provider test', async () => {
    const component = (
        <Provider store={store}> // Mock store created
            <View>
                <Text>Hello</Text>
            </View>
        </Provider>
    );
    const { queryByText } = render(component);
    const element = await queryByText('Hello');
    expect(element).toBeTruthy();
}
```

What is returned:

```
expect(received).toBeTruthy()

    Received: null

      25 |         const { queryByText } = render(component);
      26 |         const element = await queryByText('Hello');
    > 27 |         expect(element).toBeTruthy();
```
- I've tried passing in the Provider as a wrapper through the `options` parameter of `render`
- I have followed the guide for [Redux Integration](https://callstack.github.io/react-native-testing-library/docs/redux-integration) but for some reason, I can't get it to work.

- I've even tried [this wrapper method](https://testing-library.com/docs/react-testing-library/setup#custom-render) as linked in the docs but the outcome is the same. Any suggestions?

```
"react-native": "0.62.2",
"react-native-testing-library": "^2.1.0",
"@testing-library/jest-native": "^3.1.0",
```

This is my `jest.config.js`:
```javascript
module.exports = {
    preset: 'react-native',
    setupFiles: ['./node_modules/react-native-gesture-handler/jestSetup.js'],
    setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
    transformIgnorePatterns: ['node_modules/(?!(jest-)?react-native|@react-native-community|@react-navigation)'],
    resetMocks: true,
};
```

**Comment by thymikee** [comment]
Isn't `Provider` mocked which results in children not being rendered? What's the outcome of `debug` from this render?

**Comment by mdjastrzebski** [comment]
```js
test('Sample provider test', async () => {
    const component = (
        <Provider store={store}> // Mock store created
            <View>
                <Text>Hello</Text>
            </View>
        </Provider>
    );
    const { queryByText } = render(component);
    const element = await queryByText('Hello');
    expect(element).toBeTruthy();
}
```
You shouldn't call `queryByXxx` with `await` like this:
```js
const element = await queryByText('Hello');
```
but simply as a regular method like this:
```js
const element = queryByText('Hello');
```

Otherwise this code looks legit, and I've used to have similar code working correctly.

Please check the render output using `toJSON`. As @thymikee mentioned you `Provider` might be somehow mocked, which prevented its children from rendering.

**Comment by gkouziik** [comment]
@bjjeong Same problem here

**Comment by camilossantos2809** [comment]
Just in case anyone have problems with `SafeAreaProvider` from `react-native-safe-area-context`, is necessary to pass the prop `initialMetrics` as mentioned in the docs.

```
    <SafeAreaProvider
      initialMetrics={{
        frame: { x: 0, y: 0, width: 0, height: 0 },
        insets: { top: 0, left: 0, right: 0, bottom: 0 },
      }}
    >
      {children}
    </SafeAreaProvider>
```

https://github.com/th3rdwave/react-native-safe-area-context#testing
