### ISSUE TITLE
UNSAFE_getByType equivalent method

### ISSUE THREAD

**Issue by LFSCamargo** [callstack/react-native-testing-library#427]
## Ask your Question
There's a way that I can test the same way as the getByType or equivalent? And why this method is called as `UNSAFE`?
I just need to test the component props and how can I do this without needing to find a children with a test id or a text??
There's any way that I can test only the component props?

**Comment by thymikee** [comment]
If you only want component props and you know what you're doing, then using the `UNSAFE_` method is totally fine :) We're not planning to remove those.

**Comment by iuliuvisovan** [comment]
But why exactly is this method called `UNSAFE`? Can't find this info in the docs.

**Comment by thymikee** [comment]
Because it makes your test reliant on implementation details (react element type), which can break without observable changes (e.g when wrapping element with forward refs or else)
