### ISSUE TITLE
Navigation & Redux setup providing errors

### ISSUE THREAD

**Issue by BlinkVonDoom** [callstack/react-native-testing-library#431]
I am trying to write a test for an app using react-navigation and I am running into issues of the route and params being read correctly.

I am getting an error of

TypeError: Cannot read property 'params' of undefined

`on const [leadId] = useState(route.params.leadId);`

my components looks like

```
export default function AComponent() {
  const route = useRoute();
  const navigation = useNavigation();
  const dispatch = useDispatch();
  const [leadId] = useState(route.params.leadId);

...rest
}
```
I have tried following [](https://callstack.github.io/react-native-testing-library/docs/react-navigation/ )but I received `Warning: React.createElement: type is invalid when wrapping the component.`

My test looks like

```
import React from 'react';
import { Provider } from 'react-redux';
import { NavigationContainer } from '@react-navigation/native';
import { render, fireEvent, cleanup } from 'react-native-testing-library';
import configureMockStore from 'redux-mock-store';

import AComponent from 'components/contact/AComponent';

const mockStore = configureMockStore([]);

describe('<AComponent />', () => {
  let getByTestId, store;

  beforeEach(() => {
    store = mockStore({});

    ({ getByTestId } = render(
      <Provider store={store}>
        <NavigationContainer>
          <AComponent />
         </NavigationContainer>
      </Provider>
    ));
  });
});
```
my mock is

```
jest.mock('@react-navigation/native', () => {
  return {
    useNavigation: () => ({ goBack: jest.fn() }),
    useRoute: jest.fn(),
  };
});
```
I am not sure if I am wrapping the components incorrectly, or if I am missing something else.

Any ideas or help would be greatly appreciated.

Thanks.

**Comment by thymikee** [comment]
Don't mock navigation and it will work.

**Comment by hisham-blackbuck** [comment]
@BlinkVonDoom add this to your jest config. 
@thymikee I'm mocking navigation, and have no issues.
```
jest.mock('react-redux', () => {
    return {
          ...jest.requireActual('react-redux'),
          useSelector: jest.fn().mockImplementation(() => ({})),
          useDispatch: () => jest.fn(),
     };
 });

**Comment by thymikee** [comment]
@hisham-blackbuck please don't mock the libraries. It's hardly ever necessary. Instead use them in your test code as you'd use them in the app. It often comes with some boilerplate, but it's not really new code, you already use it similarly in your app. When mocking, you'll need to maintain a more complex setup that's prone to errors because of implementation details changing in the library. Don't do it please.

**Comment by Zakyyy** [comment]
@thymikee How can I avoid mocking the libraries and every time I run npm test without having the mock files it sends me an error of undefined for the functions in side this library
can you help me on this?
