### ISSUE TITLE
How to simulate navigating to component 2 level down.

### ISSUE THREAD

**Issue by tahmidmozaffar** [callstack/react-native-testing-library#443]
Hi, I am using 1.13.0 version for a project.

I have a scenario where I have 3 components. 1st component has a button, clicking on that, 2nd component will come, It has a 
List. And then clicking on any list item, 3rd component will be visible, But when I am trying to simulate clicking on a list item, navigation not working, so my test is failing.

What I am missing? For two components, it is always working. Why it is not working for three nested components?

**Comment by thymikee** [comment]
It's not a matter of nesting, which is irrelevant. You mix nesting and navigation here, so I don't quite get what's the actual issue. Please add a repro and code examples, otherwise it's not actionable.

**Comment by sregg** [comment]
I've had the issue in the past where I would have 3 screens in a react-navigation stack.
I was able to see elements of the first 2 screens but when I would navigate to the 3rd, it wouldn't show anything.
I fixed it by updating to the latest version of react-navigation.
It was the weirdest thing. I never understood what happened there.
BTW that was with `native-testing-library`.

**Comment by NilsonLima** [comment]
Has anyone found any solution to this issue? I'm facing the same. In my case I can navigate from Screen A to Screen B but not from Screen B to Screen C. In both screens `navigation.navigate` is being called properly but nothing happens (even `navigation.goBack` does not have any effect).
