### ISSUE TITLE
chore: [TL migration] rename getByPlaceholder to getByPlaceholderText (or provide an alias)

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#447]
## Describe the Feature
Currently we have `getByPlaceholder` (and related queries). However, both RTL and deprecated TL/RN use `getByPlaceholderText`.

This seems to be consistent with other RTL, TL/RN names likes `getByLabelText`, `getByHintText`, etc. 

## Possible Implementations
1. Rename `getByPlaceholder` -> `getByPlaceholderText`
2. Add alias for `getByPlaceholderText`

Selected option should be mentioned in the migration guide.

My preferred option would be 1 (rename), as it would keep things simple & consitent.

## Related Issues
This is part of migration to official TL repo.

CC: @thymikee @Esemesek @cross19xx

**Comment by thymikee** [comment]
I'm in for option 1, the change is easy enough to migrate without too much effort.

**Comment by thymikee** [comment]
Closed via #455
