### ISSUE TITLE
feat: introduce `getQueriesForElement` as alias for `within`.

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#457]
## Describe the Feature
TL/RN v6 has provided `getQueriesForElement` for scoping queries to given element & it's children. RNTL v2 had a similar `within` function. Both of these were modeled on similar RTLs helper. In [RTL both names are available (as alias)](https://testing-library.com/docs/dom-testing-library/api-helpers#within-and-getqueriesforelement-apis) to provide the same function.

## Possible Implementations
Provide `getQueriesForElement` as alias to `within`.

## Benefits

* compatibility with RTL
* easier migration path for TL/RN v6 users.

## Related Issues
Migration to v7, #456

**Comment by mdjastrzebski** [comment]
CC: @thymikee, @cross19xx, @Esemesek

**Comment by thymikee** [comment]
This is a simple rename and I've already created a migration doc for it: https://github.com/callstack/react-native-testing-library/pull/456/files#diff-e96d057ee0b5c209da93af10f6a373c1R51-R54

On the other hand, DOM testing library has this alias as well. Feel free to contribute this, but I'd prefer focusing more on the migration guide.

**Comment by thymikee** [comment]
Closed via #461
