### ISSUE TITLE
No handler function found with fireEvent.press on disabled TouchableOpacity

### ISSUE THREAD

**Issue by Andarius** [callstack/react-native-testing-library#469]
## Describe the bug

When running `fireEvent.press` on a disabled TouchableOpacity, the following error appears: ` No handler function found for event: "press"`

## Expected behavior

Should not raise an error

## Steps to Reproduce

Run the following

```
import { TouchableOpacity } from 'react-native'

describe.only('Test TouchableOpacity', () => {
    const Button = ({ onPress }) => {
        return <TouchableOpacity testID='testBtn' disabled={true} onPress={onPress}></TouchableOpacity>
    }

    const onPressSpy = sinon.spy()

    it('onPress does not trigger', () => {
        const { getByTestId } = render( <Button onPress={onPressSpy}/>)
        fireEvent.press(getByTestId('testBtn'))
        expect(props.onPress.callCount).toBe(0)
    })
})
```

## Versions

```
  npmPackages:
    @testing-library/react-native: ^7.0.0 => 7.0.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
    react-test-renderer: ^16.13.0 => 16.13.1 
```

**Comment by thymikee** [comment]
The "touchable" is disabled, so the handler won't be invoked, hence the error thrown. I think we could improve the wording to be more obvious here.

**Comment by thymikee** [comment]
cc @mdjastrzebski as he also has some thoughts on the topic :)

**Comment by Andarius** [comment]
So what is the best option here to test a disabled touchable ? Something like  
```
    const Button = ({ onPress, isDisabled }) => {
        return <TouchableOpacity testID='testBtn' disabled={isDisabled} onPress={isDisabled ? () => {}: onPress} />
    }
```

**Comment by thymikee** [comment]
```js
expect(...).toThrowError("No handler function found")
```

**Comment by Andarius** [comment]
```
    it('onPress does not trigger', () => {
        const { getByTestId } = render( <Button onPress={() => console.log('called')}/>)
        expect(fireEvent.press(getByTestId('testBtn'))).toThrowError('No handler function found')
    })
```
Still raises an error

**Comment by thymikee** [comment]
The expectation must be in a function body because that's what Jest is trying to call:
```js
expect(() => {
  fireEvent.press(getByTestId('testBtn'))
}).toThrowError('No handler function found')
```

**Comment by Andarius** [comment]
Oh sorry nevermind it works, thanks !

**Comment by mdjastrzebski** [comment]
@Andarius I think your original complain is a valid point. So `fireEvent` throws error when it does not find any matching event handler, which should suggested to the programmer that there is a problem with assertions or components under test. 

However the case when there is event handler but is disabled should probably be handled without throwing error.

**Comment by thymikee** [comment]
We've just release 7.0.1 which now doesn't throw. So please adjust your tests to something like this:
```js
fireEvent.press(getByTestId('testBtn'));
expect(handlePress).not.toHaveBeenCalled();
```
