### ISSUE TITLE
Support "editable" on TextInput

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#476]
## Describe the Feature

`TextInput` component from `react-native` has its own handling of being disabled/editable. It's not using responder system like Views, Texts and thus Touchables, so the logic we have already fails to catch it. 

We should consider adding custom handling specific to native TextInput component, since it was working with `@testing-library/react-native` before v7.

## Possible Implementations

Will likely involve detecting `TextInput` and verify if it's editable or not.

Test that fails with current implementation:

```js
test('should not fire on disabled TextInput', () => {
  const handleChangeText = jest.fn();

  const screen = render(
    <TextInput onChangeText={handleChangeText} editable={false}>
      <Text>Trigger</Text>
    </TextInput>
  );

  fireEvent.changeText(screen.getByText('Trigger'), 'Trigger');
  expect(handleChangeText).not.toHaveBeenCalled();
});
```

**Comment by pitpitpat** [comment]
Hi @thymikee, I'd like to tackle this one.

**Comment by thymikee** [comment]
@pitpitpat go for it!

**Comment by douglasjunior** [comment]
`fireEvent(textInput, 'focus')` still working when `editable={false}` 😢

**Comment by thymikee** [comment]
@douglasjunior we have 2 tests for this scenario which are passing on our infra. Mind investigating on your side, reducing it to a minimal setup and see if some 3rd-party code doesn't interfere? Btw, there's no need to wrap `fireEvent` with `act`, it's done under the hood

**Comment by douglasjunior** [comment]
Hi @thymikee, thank you for the quick response!

I've just tested on a new project here.

Create a new RN 0.68.2 project using TypeScript template:

```
npx react-native init TestingLibrarySample --template react-native-template-typescript@6.10.4
```

Add testing-library:

```
yarn add -D @testing-library/react-native
```

Edit the `__tests__/App-test.tsx` to add:

```tsx
  it('test TextInput native', () => {
    const handleFocus = jest.fn();

    const result = render(
      <TextInput testID="my-input" onFocus={handleFocus} editable={false} />,
    );

    const rnTextInput = result.getByTestId('my-input');

    fireEvent(rnTextInput, 'focus');

    expect(handleFocus).not.toBeCalled();
  });
```

Run tests:

```
yarn test
```

Sample project: https://github.com/douglasjunior/TestingLibrarySample

Other people with similar problem: https://stackoverflow.com/q/65625330/2826279

Thanks!

**Comment by thymikee** [comment]
Would you be able to create a PR with this test failing?

**Comment by douglasjunior** [comment]
I think I figured out the problem, if using "placeholder" in place of "testID" works as expected.

```ts
  it('test TextInput native by placeholder', () => {
    const handleFocus = jest.fn();

    const result = render(
      <TextInput
        placeholder="my-input"
        onFocus={handleFocus}
        editable={false}
      />,
    );

    const rnTextInput = result.getByPlaceholderText('my-input');

    fireEvent(rnTextInput, 'focus');

    expect(handleFocus).not.toBeCalled(); // <--- pass
  });

  it('test TextInput native by testID', () => {
    const handleFocus = jest.fn();

    const result = render(
      <TextInput testID="my-input" onFocus={handleFocus} editable={false} />,
    );

    const rnTextInput = result.getByTestId('my-input');

    fireEvent(rnTextInput, 'focus');

    expect(handleFocus).not.toBeCalled(); // <--- fail
  });
```

**Comment by thymikee** [comment]
Thanks! Looking forward to the PR :)

**Comment by douglasjunior** [comment]
Done https://github.com/callstack/react-native-testing-library/pull/1080

**Comment by douglasjunior** [comment]
Another scenario that's don't work as expected, even using `getByPlaceholderText`, was when using `withTheme` from `@callstack/react-theme-provider`;

```tsx
  it('test TextInput native by custom component', () => {
    const CustomTextInput: React.FC<{ theme: AppThemeType } & TextInputProps> = props => <TextInput testID="rn-text-input" {...props} />;

    const CustomInputWithTheme = withTheme(CustomTextInput);

    const handleFocus = jest.fn();

    const result = render(
      <CustomInputWithTheme
        placeholder="my-input"
        onFocus={handleFocus}
        editable={false}
      />,
    );

    const rnTextInput = result.getByPlaceholderText('my-input');

    fireEvent(rnTextInput, 'focus');

    expect(handleFocus).not.toBeCalled(); // <--- fail
  });
```
