### ISSUE TITLE
Is there a better way to get state from a rendered element?

### ISSUE THREAD

**Issue by jewseppi** [callstack/react-native-testing-library#48]
I wrote a helper function to retrieve state after a changeText or press event. Is there a better way to do this? 

My components are all wrapped in styled-component tags as well..

```
const getState = instance => {
  const [ReactTestInstance] = instance.children;
  const {
    stateNode: { state },
  } = ReactTestInstance['_fiber'].memoizedProps.children['_owner'];
  return state;
};
```

**Comment by sibelius** [comment]
the idea is not the test implementation

user can't change state (or validate state) itself, you should be able to validate state based on rendered components

**Comment by jewseppi** [comment]
okay thanks that was my assumption, thanks!

**Comment by thymikee** [comment]
State is an implementation detail of the component and shouldn't be asserted on in testes. Just don't do it. If your state is complex and you feel like testing it in units, extract it to functions. 

Just 2h ago React team presented a new way of declaring stateful function components called Hooks. When you assert on the output, like you should, your test will pass even though you rewritten your test from class to hooks or suspense or whatever.

**Comment by hyochan** [comment]
@thymikee Could you provide an extra example? I can bearly understand what you are saying but I want to be more clear with some codes.
