### ISSUE TITLE
Typescript diff for queryAllByTestId says it can return null

### ISSUE THREAD

**Issue by ericbiewener** [callstack/react-native-testing-library#486]
## Describe the bug

According to the docs, all the `queryAll` methods are guaranteed to return an array. However, [the TS definition for `queryAllByTestId` indicates that it can return null](https://github.com/callstack/react-native-testing-library/blob/master/typings/index.d.ts#L73).

## Expected behavior

TS definition says it returns an array.

**Comment by thymikee** [comment]
Happy to accept a PR fixing that :)
