### ISSUE TITLE
Failing tests on change to fireEvent.press due to HOC

### ISSUE THREAD

**Issue by mdarke1** [callstack/react-native-testing-library#487]
## Describe the bug

On upgrade to version 7 the change in fireEvent.press behaviour is now causing our tests to fail due to the use of a HOC on our side. 

We are using a two step modal form process which is controlled by a pure component that then passes a step function (via context) using the index as the render method to move to the next screen. Relevant excerpts are attached below.

Since the upgrade the tests fail with error message:
 _Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number. Check the render method of `ImageModal`._

Whilst this is rendered by a number, this does not practically cause a failure in the render method. I've also tested on android emulator and iphone and appears to be rendering correctly.

As I'm relatively new to the library it may be that I've missed something here and would appreciate any guidance you may have. 

## Steps to Reproduce
[FormStep (2).zip](https://github.com/callstack/react-native-testing-library/files/5039357/FormStep.2.zip)

## Versions

    npmPackages:
    @testing-library/react-native: ^7.0.1 => 7.0.1
    react: 16.11.0 => 16.11.0
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    react-test-renderer: ^16.13.1 => 16.13.1

**Comment by thymikee** [comment]
Based on the error returned (it's from React), I'm afraid this is not related to the testing library itself. In test environment `ImageModal` returns invalid React element, you'll need to check that. Make sue you use `"preset": "react-native"` in your Jest configuration. Closing as not actionable.

**Comment by mdarke1** [comment]
On Thu, 3 Sep 2020 at 9:32 pm, Michał Pierzchała <notifications@github.com>
wrote:

>
>
> Closed #487
> <https://github.com/callstack/react-native-testing-library/issues/487>.
>
> Thanks Michael- however I’m confused - imagemodal is simply a different
> nested

component. It could be any component used under this process, so not sure
> how that creates an invalid react element. Are you saying this is specific
> to a react testing environment?


I’m finding it difficult to believe that it is a react issue given that the
test was passing before but after upgrading react native testing library
and no other dependencies it began failing.
