### ISSUE TITLE
Convert repository to monorepository

### ISSUE THREAD

**Issue by cross19xx** [callstack/react-native-testing-library#493]
## Describe the Feature
The idea behind this PR is to convert the repository into a monorepo, allowing us to have multiple packages and allowing inter-dependence between them.

## Possible Implementations
The proposed folder structure are as follows:
```sh
/ # Project root. Contains all configurations
/ examples   # Contains all examples. Will be using the `react-native-testing-library` package
/ website    # Contains the RNTL website
/ packages
    / react-native-testing-library
```

**Comment by mdjastrzebski** [comment]
Closing as partially done because of lack of recent activity.
