### ISSUE TITLE
React Native Testing Library matching every screen in ReactNavigation StackNavigator

### ISSUE THREAD

**Issue by DzoYee** [callstack/react-native-testing-library#499]
I am trying to test navigating from one StackScreen to another and back.

I have a component 

`const Accounts: React.FC = () => (
  <Stack.Navigator>
    <Stack.Screen name="AccountsSummary" component={AccountsSummary} />
    <Stack.Screen name="AccountDetails" component={AccountDetails} />
  </Stack.Navigator>
)`

When I render it with RNTL

`const {findByText} = render(
      <NavigationContainer>
        <Accounts />
      </NavigationContainer>,
    )`

I am able to assert that some content is showing in AccountsSummary whether I'm in AccountDetails or AccountsSummary.

Is there a current solution to this? How might you go about making assertions when the context is polluted by all the other screens? I would think this might normally be something you could fix with the toBeVisible matcher but it doesn't look like RNTL supports that.

**Comment by thymikee** [comment]
You can query a certain screen by its ID or something and use `within` to scope queries inside it. We're thinking about other solutions (more accessibility aware queries), but currently that's the way to go.

**Comment by DzoYee** [comment]
I'm not sure how this would help, am I missing something?

I render Accounts which defaults with AccountSummary using the Navigation. I then navigate to AccountDetails and then navigate back to AccountSummary. The issue is that I am able to assert on seeing AccountSummary even while on AccountDetails.

My thought is that even if I scope the query, it wouldn't fix the issue because it exists in the "DOM" either way.

**Comment by sregg** [comment]
Any update on this?
