### ISSUE TITLE
React Native's Modal mock contains a bug

### ISSUE THREAD

**Issue by vanGalilea** [callstack/react-native-testing-library#508]
So it seems like React Native's Modal is being mocked wrong. 

When rendered in tests the Modal and its children are constantly showing in the tree, also when set to be **_not visible_**.
Just figured out how to fix this issue in my examples repo: https://github.com/vanGalilea/react-native-testing

Does somebody know whether the Modal is actually mocked by RN or by RNTL.
If it's mocked by RNTL, where can I update the Modal mock? so I can create a PR.

Cheers!

**Comment by thymikee** [comment]
We don't provide any mocks.
