### ISSUE TITLE
Port guides from Native Testing Library

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#512]
## Describe the Feature

Port the most relevant guides from this page: https://www.native-testing-library.com/docs/guide-queries.
I'm not sure if we need them all, so feel free to pick the best ones :) 

## Possible Implementations

We already have a section for Guides in the sidebar, so they could be linked there.
We can also link to the official docs: https://testing-library.com/docs/guide-which-query but there are slight differences in APIs

**Comment by pplytas** [comment]
Hi @thymikee, there aren't many guides in this page: https://www.native-testing-library.com/docs/guide-queries Just a brief explanation of the getBy methods and a couple of paragraphs for Manual Queries.

Did you mean this page as well: https://www.native-testing-library.com/docs/guide-disappearance and the examples below (i.e Context, Input Event, Intl, Navigation, Redux, Update Props)?

**Comment by thymikee** [comment]
I meant "How Should I Query?" specifically. Would be great to add more docs though! :)

**Comment by pplytas** [comment]
I'm preparing a PR for this. Should the 'Manual Queries' section be included as well, since the library doesn't support the `findAll` method mentioned there?

**Comment by thymikee** [comment]
Yup, skip `findAll`.
