### ISSUE TITLE
The string precision API is missing in v7

### ISSUE THREAD

**Issue by TAGraves** [callstack/react-native-testing-library#514]
In v6, queries could be passed string precision options so that they performed fuzzier text matching or normalized text differently (see https://www.native-testing-library.com/docs/next/api-queries#precision). These options are not available in v7. v6's behavior matches that of [dom-testing-library](https://testing-library.com/docs/dom-testing-library/api-queries#textmatch) so it is probably worth adding them back in -- those docs do a good job of describing the expected behavior of them, too.

**Comment by RafikiTiki** [comment]
I'll try to tackle this
