### ISSUE TITLE
ExceptionsManager.handleException is not a function

### ISSUE THREAD

**Issue by eliw00d** [callstack/react-native-testing-library#532]
## Describe the bug

We recently upgraded to React Native 0.63, Jest 26, and React Native Testing Library 7. When running jest with `--runInBand` we have noticed the following error randomly in our CI:

```
/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:104
  ExceptionsManager.handleException(error, true);
                    ^
TypeError: ExceptionsManager.handleException is not a function
    at reportLogBoxError (/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:108:21)
    at Immediate.<anonymous> (/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:217:7)
    at processImmediate (internal/timers.js:456:21)
```

I noticed a similar error in the previous project: https://github.com/testing-library/native-testing-library/issues/132

Any thoughts?

## Expected behavior

No errors.

## Versions

```
❯ npx envinfo --npmPackages react,react-native,react-test-renderer,@testing-library/react-native

  npmPackages:
    @testing-library/react-native: 7.0.2 => 7.0.2 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by thymikee** [comment]
This library has nothing to do with LogBox, nor ExceptionsManager. Make sure to use "react-native" Jest preset and mock the native module if necessary. Looks like ExceptionsManager is already mocked, but `handleException` is not there: https://github.com/facebook/react-native/blob/master/jest/setup.js#L42

**Comment by thymikee** [comment]
RNTL provides no mocks on its own, where did you get that information from? It's `"react-native"` Jest preset that ships with React Native that handles mocking for Jest. If something is not there, while it should, send a PR to the core RN repo :)

**Comment by lukewlms** [comment]
Ah somehow I hallucinated that 🙂 thanks for the info!!

**Comment by gustavommarini** [comment]
[This](https://github.com/facebook/react-native/issues/29849#issuecomment-734533635) solved my problem. :)
