### ISSUE TITLE
Out of memory error using debug() in an Animated.FlatList with a ref

### ISSUE THREAD

**Issue by Paduado** [callstack/react-native-testing-library#539]
## Describe the bug

I'm implementing a test in a component that renders an `Animated.FlatList`, when I use debug the test hangs and eventually throws a JavaScript heap out of memory error.

I found out that If I remove the ref I'm passing to the `Animated.FlatList` everything works fine.
It also works with a regular `FlatList`.

## Expected behavior
Test shouldn't hang and debug() output should be visible in the console.

## Steps to Reproduce
Run this test:
```js
function MyFlatList() {
  const ref = useRef();
  return (
    <Animated.FlatList
      ref={ref}
      data={[1, 2, 3]}
      renderItem={({ item }) => <Text>{item}</Text>}
    />
  );
}

test('FlatList', () => {
  const { debug } = render(<MyFlatList />);
  debug();
  expect(true).toBe(true);
});
```
The test will hang and throw this error:
**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

## Versions
    @testing-library/react-native: 7.0.2 => 7.0.2 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-test-renderer: ^16.13.1 => 16.13.1

**Comment by Ziew** [comment]
Any update on that?
Workaround for me was mocking Animated.ScrollView but it's not perfect solution.

**Comment by raimonkh** [comment]
What I did was increase the size of memory for node `export NODE_OPTIONS := --max_old_space_size=8192`

**Comment by pke** [comment]
Just encountered this too in the form of https://github.com/facebook/jest/issues/8109

Sad, that there does not seem to be a workaround for that. Increasing the memory of the node process is not really a valid solution. The ref problem has its roots somewhere else.

**Comment by scrungrth** [comment]
adding this worked for my test:
```tsx
    Object.defineProperty(Animated, 'View', {
      get value() {
        return View;
      },
    });

**Comment by sparachi** [comment]
On the lines of @pke  comments, re-adjusting the `ref` worked for me too. https://github.com/facebook/jest/issues/10577#issuecomment-970574846

**Comment by blimmer** [comment]
Depending on the Node version you're using, the OOM might be compounded by this issue: https://github.com/facebook/jest/issues/11956

**Comment by mdjastrzebski** [comment]
Seems like the root issue is related to the actual size of component tree generated by using `Animated` wrappers. If so then the you can work around the issue by:
1) including memory allocated to `jest` instance using approach described by @raimonkh 
2) mocking `Animated` implementation as described by @scrungrth, preferably using `jest` features instead of `Object.defineProperty`

**Comment by redreceipt** [comment]
> Any update on that?
> Workaround for me was mocking Animated.ScrollView but it's not perfect solution.

How did you mock `Animated.ScrollView` this is the solution I'd like to go with
