### ISSUE TITLE
integrate with https://github.com/testing-library/jest-native

### ISSUE THREAD

**Issue by sammysium** [callstack/react-native-testing-library#543]
## Describe the Feature
Would love to have toHaveStyle integrated with the library. For now, it throws error toHaveStyle is not defined. Checking for styles is quite important for UI tests. A scenario is: i have a component that takes one color and out puts applies to colors (text and background colors) to it. I would love to test its color and backgroundColor.

wrapper.getByTestId('test').props.style is undefined whereas props just returns its props.

**Comment by thymikee** [comment]
I've already answered this in another issue. It's something that needs to be tackled in jest-native.
