### ISSUE TITLE
How to use with Expo?

### ISSUE THREAD

**Issue by bitttttten** [callstack/react-native-testing-library#544]
Hi hi!

I am wondering what is the best practise to use alongside Expo? [The Expo docs](https://docs.expo.io/guides/testing-with-jest/#jest-configuration) suggest to use the "jest-expo" preset, and your docs suggest the "react-native" present.

If I just use the "react-native" preset, then babel is not compiling my code and I run into "Cannot use import statement outside a module" errors. Perhaps this is another issue, although I just wanted to clarify just in case I am doing something immediately obviously wrong :)

Thanks!

**Comment by thymikee** [comment]
Go with what Expo suggests. This is generic React Native library, we're not optimizing for Expo.

**Comment by bitttttten** [comment]
Thanks @thymikee for clearing it up!

**Comment by realmhamdy** [comment]
I think this should be mentioned in somewhere obvious in the docs. I just wasted a few hours trying to configure this to work with Expo.

Here's a good starting template:

_**Don't even try to get this to work with Expo, dumba**!!!**_

**Comment by thymikee** [comment]
I think you can contribute something meaningful to let other Expo users know about how things work :)

**Comment by bitttttten** [comment]
> _**Don't even try to get this to work with Expo, dumbass!**_

What doesn't work for you @realmhamdy ? I am using this library successfully with Expo 🤔

**Comment by realmhamdy** [comment]
@bitttttten well that contradicts @thymikee comment above. I think you should reach an agreement together and document that. Either it can work (if you do these steps...) or it can't work.

**Comment by realmhamdy** [comment]
@bitttttten how did you do it? Enlighten our conversation with your wisdom.

**Comment by bitttttten** [comment]
I am using the jest-expo preset, and I extended the matches using the `setupFilesAfterEnv` [as explained in the docs](https://github.com/callstack/react-native-testing-library#additional-jest-matchers).

If you're having trouble I would recommend starting a new expo project, adding in jest and this library, and seeing if it doesn't work from there.

**Comment by realmhamdy** [comment]
So I have a test that looks like this:

```javascript
import React from "react"
import { render } from "@testing-library/react-native"
import App from "./App"


test("App component shows greeting", () => {
    const { getAllByText } = render(<App />)
    expect(getAllByText("Hello there!")).toHaveLength(1)
})
```

And a `jest` entry in `package.json` that has this:

```json
{
    "preset": "jest-expo",
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ]
  }
```
Giving me this error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
Do you have any directions?

**Comment by thymikee** [comment]
@realmhamdy Rename your `App` component to something else. Jest has an issue with `App.tsx` and `app.json` being next to each other and it picks `app.json`, hence you React thinks you want to render an object (app.json) instead of a function (App.tsx).

I haven't investigated where this comes from yet, but will try to prioritize this.

**Comment by rdjpalmer** [comment]
[Happened to stumble across someone](https://metareal.blog/en/post/2021/01/16/setup-jest-for-expo-typescript-project/) who mentioned the same problem as you @thymikee, and (I haven't tested this yet), but it's apparently fixed by providing `moduleFileExtensions` in the order you'd prefer for them to be picked up on:

> The error was happened because the import loads app.json instead of App.tsx. To prevent this, configure Jest’s [moduleFileExtensions](https://jestjs.io/docs/ja/configuration#) to prioritize .tsx and .ts over .json when loading modules.
>
>  ```
> "jest": {
>    ...
>    "moduleFileExtensions": [
>      "ts",
>      "tsx",
>      "js",
>      "jsx"
>    ]
>  },
> ```

**Comment by codearis** [comment]
> [Happened to stumble across someone](https://metareal.blog/en/post/2021/01/16/setup-jest-for-expo-typescript-project/) who mentioned the same problem as you @thymikee, and (I haven't tested this yet), but it's apparently fixed by providing `moduleFileExtensions` in the order you'd prefer for them to be picked up on:
> 
> > The error was happened because the import loads app.json instead of App.tsx. To prevent this, configure Jest’s [moduleFileExtensions](https://jestjs.io/docs/ja/configuration#) to prioritize .tsx and .ts over .json when loading modules.
> > ```
> > "jest": {
> >   ...
> >   "moduleFileExtensions": [
> >     "ts",
> >     "tsx",
> >     "js",
> >     "jsx"
> >   ]
> > },
> > ```

Had this issue today, definitely a solution.
