### ISSUE TITLE
Fire Custom Events - Press in, press out

### ISSUE THREAD

**Issue by napsta32** [callstack/react-native-testing-library#545]
## Describe the Feature
Add more events to `fireEvent` like press in, press out.

I was checking coverage report and I saw that some lines are not tested:

```
onPressIn={() => setPressed(true)}
onPressOut={() => setPressed(false)}>
```

I would like to add snapshots when component is pressed and when it isn't.

Is there a guide on how `fireEvent` was implemented to create custom events like these?

**Comment by thymikee** [comment]
If you care about events like onPressIn etc, you're free to use the generic form of fireEvent: https://callstack.github.io/react-native-testing-library/docs/api/#fireevent. It's all in the docs, with an example.

**Comment by napsta32** [comment]
thanks for the quick response!
