### ISSUE TITLE
getBy error message should include the value that was not found

### ISSUE THREAD

**Issue by sregg** [callstack/react-native-testing-library#549]
## Describe the Feature
Currently, when a `getBy` (or `findBy`) fails, the error is only `No instance found`.
It would be great to have what value was not found.
e.g. `getByText('text that doesn't exist')` would throw `No instance found with text 'text that doesn't exist'`

## Possible Implementations
If it's easier to implement you could even omit the type like `No instance found: 'text that doesn't exist'`

## Related Issues
https://github.com/callstack/react-native-testing-library/issues/547
Currently `findBy` doesn't show the stack-trace so it's hard to know which one failed.
Having a better error message would make it easier to debug, even without the stack-trace.

**Comment by thymikee** [comment]
Isn't the code frame enough to determine where the error happens? It should point to the faulty code. If it's not there, it's a bug and should be fixed

**Comment by sregg** [comment]
The stack-trace is not working for `findBy` and `waitFor` at the moment (see #547).
Adding the value in the error message seemed to be an easier thing to prioritize.

**Comment by mdjastrzebski** [comment]
This is implemented, as all queries now report their predicate: e.g. 
`Unable to find an element with text: ${String(text)}`
