### ISSUE TITLE
fireEvent.press does not work on TouchableOpacity

### ISSUE THREAD

**Issue by TrebuhD** [callstack/react-native-testing-library#552]
## Describe the bug

`TouchableOpacity`'s `onPress` is not called when calling `fireEvent.press` on it.

This is the same bug as in https://github.com/testing-library/native-testing-library/issues/113.

**Comment by thymikee** [comment]
Which version of the library are you using? Please provide a failing test, we have various tests in our suite that verify this exact scenario working, so I'm curious about your setup.
