### ISSUE TITLE
web - getByTestId does not return any instances (change of behaviour from v2)

### ISSUE THREAD

**Issue by Dammic** [callstack/react-native-testing-library#574]
Hello!

I'm using this library on my project and so far it is a very good experience! We've recently made a jump from v1 to the latest version, but we have a problem with 'getByTestId'

I know the stance about this and I actually try use any other possible selectors first when I'm writing tests.
The problem I have is with web. With v2, there is this from the doc:

```
In version 1.x the getByTestId and queryByTestId queries could return non-native instances. This was a serious bug. Other query functions like getAllByTestId, queryAllByTestId, findByTestId and findAllByTestId didn't have this issue. These correctly returned only native components instances (e.g. View, Text, etc) that got the testID.

In v2 we fixed this inconsistency, which may result in failing tests, if you relied on this behavior. There are few ways to handle these failures:
```

This change makes it that the tests work fine for 'ios' and 'android' runners, but fail for web due to Views being converted into web elements. I was trying to use any other selectors (with aria-labels, accessibilityHint, accessibilityLabel), but I could not make it work for web.

The case I have is with drawer and clickable overlay:
```
<TouchableWithoutFeedback onPress={onCloseDrawer}>
        <View
          style={{ opacity: overlayOpacityAnimation, zIndex: overlayZIndex }}
          testID="drawer-overlay"
          accessibilityHint="hello-there"
          accessibilityLabel="hello-1"
/>
```
And the test:
```
const { debug, getByTestId, getByAccessibilityHint, getByAccessibilityLabel } = render(
         <ActionDrawer />
);

debug();

fireEvent(getByAccessibilityLabel('hello-1'); // no instances
// or
fireEvent(getByTestId('drawer-overlay'), 'press'); // no instances
// or 
fireEvent(getByAccessibilityHint('hello-there'), 'press'); // no instances
```

Both of the checks return 0 instances for me.
This is what is being returned from the debug (for this part):
```
<div
        aria-label="hello-1"
        className="css-view-1dbjc4n"
        data-focusable={true}
        data-testid="drawer-overlay"
        onClick={[Function onClick]}
        onContextMenu={[Function onContextMenu]}
        onKeyDown={[Function anonymous]}
        style={
          Object {
            "opacity": 0,
            "zIndex": 901,
          }
        }
        tabIndex="0"
/>
```

How should I approach tests for web for that problem? Thanks in advance! I think something like 'getByTitle' might work, but it is not supported right now.

**Comment by thymikee** [comment]
We don't convert our queries to be compatible with web. It's advised to use React Testing Library for any logic that's web-specific, as it provides better support for web.

**Comment by Dammic** [comment]
I understand, though perhaps there could be a way to have some configuration that would at least bring back the v1 version behaviour regarding testId (just enable returning the non-native elements)? It was working very well before and would be more flexible with that.

If not, then of course I'll write my own adapter to handle that case depending on environment.

**Comment by thymikee** [comment]
Unfortunately we won't go back to returning non-native elements, it would be quite breaking now and also would go against Testing Library org principles.
