### ISSUE TITLE
fireEvent not working for "responderMove"

### ISSUE THREAD

**Issue by abmantis** [callstack/react-native-testing-library#576]
## Describe the bug

After updating to v7, calling fireEvent for "responderMove" stopped working. This is due to the new checks to see if a component is "disabled". Since RNTL only checks for onStartShouldSetResponder(), a component that uses onMoveShouldSetResponder() but not onStartShouldSetResponder(), will always be considered to be "disabled" by RNTL.

For testing, I replaced onStartShouldSetResponder with onMoveShouldSetResponder on the following and it solves the issue:
https://github.com/callstack/react-native-testing-library/blob/b9f9ab754e7ac6fa8e704928694332bb57e083bd/src/fireEvent.js#L26

## Expected behavior

The following would work:
```
  fireEvent(container, 'responderMove', {
    touchHistory: { mostRecentTimeStamp: '2', touchBank: [] },
  });

```
## Versions

  npmPackages:
    @testing-library/react-native: ^7.0.2 => 7.0.2 
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    react-test-renderer: ^16.11.0 => 16.13.1

**Comment by thymikee** [comment]
Sounds like this check could be extended then. Would you like to send a PR?

**Comment by abmantis** [comment]
@thymikee done. See #577
