### ISSUE TITLE
Install from git not working correctly

### ISSUE THREAD

**Issue by abmantis** [callstack/react-native-testing-library#578]
## Describe the bug

Doing `npm i --save-dev git://github.com/callstack/react-native-testing-library` finishes successfully, but when running tests the library is not found: `Cannot find module '@testing-library/react-native' from 'NewCardButton.test.tsx'`

## Expected behavior

Installing from github would work.

## Versions

```
  npmPackages:
    @testing-library/react-native: git://github.com/callstack/react-native-testing-library.git => 7.1.0 
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
    react-test-renderer: ^16.11.0 => 16.13.1 
```

**Comment by thymikee** [comment]
This library is meant to be consumed from npm module. We don't give any guarantee it would work when installing from github directly. Happy to accept contributions to make it easier, if possible.
