### ISSUE TITLE
The links in the "How Should I Query?" page are not pointing to the correct links

### ISSUE THREAD

**Issue by ryanjwessel** [callstack/react-native-testing-library#579]
## Describe the bug

Clicking any one of the links from the "How Should I Query?" page on the documentation website results in [this screen](https://i.imgur.com/CVemA7n.png)

The current path looks like this: https://callstack.github.io/react-native-testing-library/docs/how-should-i-query/api-queries#bydisplayvalue

So, it seems that the URLs are relative to the "How Should I Query?" page.

## Expected behavior

The link should point to the correct query path on the documentation website (example: https://callstack.github.io/react-native-testing-library/docs/api-queries#byplaceholdertext)

## Steps to Reproduce

- Go to the "How Should I Query" page
- Click on any of the referenced query links.

## Screenshots

[Example screenshot](https://i.imgur.com/CVemA7n.png)

## Versions

Current documentation version?

**Comment by thymikee** [comment]
PRs welcome :)

**Comment by ryanjwessel** [comment]
I would be happy to! I'll aim to have one for today.

**Comment by ryanjwessel** [comment]
The links are working on the production website now, so this can be closed. Thanks, @thymikee!
