### ISSUE TITLE
getByText across siblings

### ISSUE THREAD

**Issue by bitttttten** [callstack/react-native-testing-library#587]
## Describe the Feature
To enable `getByText` to fetch across sibling Texts

Imagine the following tree:

```js
<View>
    <Text>
        a
        <Text>               
            b
        </Text>
    </Text>
    <Text>
        c
    </Text>
</View>
```

Currently we can do `getByText('a b')`, `getByText('a')`, `getByText('b')`, `getByText('c')`, although it's not possible to do `getByText('a b c')`, even though that is what is rendered to the user. It would be great to be able to look for text across the siblings with Text a + c inside.

**Comment by Esemesek** [comment]
I think we can check for nested `Text` components but not sure about the example you gave. Everything depends on how you style the top-level `View` component. If you give it a `flex-direction: column`, which is the default btw, it will become an `a b \n c`. WDYT @thymikee ?

**Comment by thymikee** [comment]
Yea, it's a tricky request to make. I think the only scenario where this would make sense would be having a parent `<View accessible />` or `Text`, as this then the text inside would actually be read in a single sentence. We're not integrating this far into the RN accessibility system yet.

**Comment by bitttttten** [comment]
Ah, true, I would think it makes sense that it returns `a b \n c` in my example, and then it would also return `a b c` if the View has `flex-direction: row`?

**Comment by Esemesek** [comment]
I think it would make this matcher less stable and would be prone to a lot more errors. There are many more conditions that can make the text overflow to the next line for example. For now, I think we should stick with what we have.

**Comment by bitttttten** [comment]
Yeah, it is a tricky one 😅 

For parts of my use case I could move what I want to check for to the assertion, like get the View element and assert that `toHaveText("a b c")`. And for the rest, I'll get by with testID. :)

Thanks for the explanation and your time to consider the proposal!
