### ISSUE TITLE
Usage with Flow requires react-test-renderer types to be installed

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#59]
We should either 
1) make it explicit to install the typings using `flow-typed` or
1) add `node_modules/react-native-testing-library/flow-typed/` to `[libs]` in `.flowconfig`
1) move the `ReactTestInstance`/`ReactTestRendererJSON` to our codebase. 

I'm leaning towards options 1 & 2 as both make sense in some scenarios.

cc @Esemesek

**Comment by wtrocki** [comment]
Vote for Option 1
