### ISSUE TITLE
React native test: Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by Tommos0** [callstack/react-native-testing-library#604]
## Describe the bug

See https://stackoverflow.com/questions/64566527/react-native-test-error-unable-to-find-node-on-an-unmounted-component/

After updating to version `17`, running into this error (from testing a tree using `@react-navigation/stack`).

## Steps to Reproduce

See stackoverflow link.

## Versions

react-test-renderer@17.0.1

**Comment by thymikee** [comment]
If it's `react-test-renderer` v17 that causes issues, there's likely nothing we can do really to work it around, since we build on top of this package

**Comment by Tommos0** [comment]
Oh my bad, in my hurry I created this in the wrong repo!
