### ISSUE TITLE
Dont retrieve props from father of root component

### ISSUE THREAD

**Issue by charleycesar** [callstack/react-native-testing-library#607]
## Ask your Question

I don't know if is a Bug. 

But when I use ReactInstance.parent.props It doesnt retrieve anymore the father props.

MyComponent
`
const Breadcrumb = ({
    onPressGoBack,
    onPressChoose,
    onPressGenre,
    onPressSearch,
    choose,
    genre,
}) => ( <Box testID={'XPTO'} />)
`
`
const getProps = (component, testID) => {
    return component.getByTestId(testID).parent.props
}
`
I want to get default values from 
  onPressGoBack,
    onPressChoose,
    onPressGenre,
    onPressSearch,
    choose,
    genre,

In previous version its work but in this current version stop to work I don't know why.

**Comment by thymikee** [comment]
Previously, the `getByTestId` would return a composite component, but now we return host components (i.e. native ones like View, Text). That's why there's a difference. Tip: don't use `parent`, it's gonna break e.g. if you wrap your component with a HoC or just another component.
