### ISSUE TITLE
No handler function found for event: "scroll"

### ISSUE THREAD

**Issue by jahseng-lee** [callstack/react-native-testing-library#609]
## Describe the bug
I was writing tests to see if I could invoke the `refreshControl` component on my `<ScrollView />`.
When invoking `fireEvent.scroll(getByText("foobar"), eventData);`, I get the error `No handler function found for event: "scroll"`.

I haven't defined an `onScroll` on my `<ScrollView />` component. I shouldn't need to, it's an optional parameter for the component.

It's interesting to see in the [docs](https://callstack.github.io/react-native-testing-library/docs/api#on-a-scrollview) that a "scroll handler" is mocked.

## Expected behavior
I can use a query to select a component on my screen, which exists inside of a `<ScrollView />` component and call `fireEvent.scroll(queriedComponent, eventData)`.

## Steps to Reproduce
```
// Foobar.tsx - skipped set up code for brevity
const _onRefresh = async () => {
  setRefreshing(true);
  await someAsyncFunction();
  setRefreshing(false);
};

return (
  <ScrollView
       accessible={false}
       refreshControl={
         <RefreshControl refreshing={refreshing} onRefresh={_onRefresh} />
       }
  >
    <View>
       <Text}>"Foobar"</Text>
    </View>
  </ScrollView>
);

// Foobar.test.tsx
it("test foobar scroll", async () => {
  const { getByText } = await waitFor(() => render(<Foorbar />);

  // Scroll Up
  const eventData = {
    nativeEvent: {
      contextOffset: {
        y: -200,
      },
    },
  };
  const someText = getByText("Foobar");
  fireEvent.scroll(someText, eventData); // breaks here
});
```

then run

```
yarn test <path-to-test-folder>/Foobar.test.tsx
```

## Screenshots
N/A

## Versions
```
  npmPackages:
    @testing-library/react-native: ^7.0.2 => 7.1.0 
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.3 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by thymikee** [comment]
`fireEvent.scroll` expects that there's a `onScroll` prop attached to the ScrollView (or other components). That's why it complains about no handler being found.

**Comment by jahseng-lee** [comment]
> `fireEvent.scroll` expects that there's a `onScroll` prop attached to the ScrollView (or other components). That's why it complains about no handler being found.

Hey @thymikee, I appreciate the quick response.

However, I feel like this may have been closed prematurely. My argument here is that this expectation of the `ScrollView` **having to have a onScroll** is wrong.

Here's official React Native documentation showing that an `onScroll` prop is _not_ required: https://reactnative.dev/docs/scrollview#onscroll

In the same page, here's the official example given by React Native that _does not have a `onScroll` prop_: https://reactnative.dev/docs/scrollview#example

So either `react-native-testing-library`:
* does not supporting testing `ScrollView` as React Native intended it's use
* expects users of the library to implement custom `onScroll` handlers for every use of `ScrollView`; even though **without the custom `onScroll` handler the code executes as intended**
* is implying that having a `ScrollView` without a custom `onScroll` implementation is incorrect usage of `ScrollView`, contrary to the official React Native docs.

**Comment by jahseng-lee** [comment]
@thymikee could you address the comment above?

**Comment by thymikee** [comment]
The implementation of `fireEvent` is simply quite naive and doesn't reflect the complexity of React Native's event system. PRs welcome to improve it :)

**Comment by maestor** [comment]
@jahseng-lee, looks like you want to test ScrollView's refreshControl, not actual scrolling. you can test it for example this way:

add something to get ScrollView, for example testId if no other good solutions available:
```
<ScrollView
       testId="scroll-container"
       accessible={false}
       refreshControl={
         <RefreshControl refreshing={refreshing} onRefresh={_onRefresh} />
       }
  >
    <View>
       <Text>"Foobar"</Text>
    </View>
  </ScrollView>
```

in tests:
```
it("test pull to refresh working", async () => {
  const { getByTestId } = await waitFor(() => render(<Foorbar />);

  const ScrollContainer = getByTestId("scroll-container");
  await waitFor(() =>
    fireEvent(ScrollContainer.props.refreshControl, 'refresh', {
      nativeEvent: {},
    })
  )
  
  // Check there if things changed after refreshing
});
```
