### ISSUE TITLE
Add waitForElementToDiminish to helper functions

### ISSUE THREAD

**Issue by flpStrri** [callstack/react-native-testing-library#61]
I started using the library in our react-native project and I keep facing problems to wait until ApolloClient finish loading. Why don't we implement a waitForElementToDiminish so we can always add the loading label/testID and simplify our waits.

**Comment by thymikee** [comment]
I'm not sure if I understand your request. Can you write a proper RFC with API proposal and how would that works?

**Comment by flpStrri** [comment]
```javascript
export const waitForExpectToDiminish = (
  expectation,
  timeout = 4500,
  interval = 50
) => {
  const startTime = Date.now();
  return new Promise((resolve, reject) => {
    const rejectOrRerun = error => {
      if (Date.now() - startTime >= timeout) {
        reject(error);
        return;
      }
      setTimeout(runExpectation, interval);
    };
    function runExpectation() {
      try {
        const error = expectation();
        rejectOrRerun(error);
      } catch (result) {
        resolve(result);
      }
    }
    setTimeout(runExpectation, 0);
  });
}
```
it is the exact oposite of waitForElement, it stop waiting when an element desapear.

**Comment by flpStrri** [comment]
@thymikee I don't know how to make an RFC, can you point me out to a reference?

**Comment by thymikee** [comment]
I'm really not sure if we should add this to official helpers. I'm cool with this being a 3rd-party library, but having it here people may start using this API to test stuff that's technically unrelated – e.g. disappearing loading indicator could lead to a fallback rendered, not the actual component, and I think you should explicitly check fot something to appear.

cc @Esemesek @kpsroka

**Comment by flpStrri** [comment]
Another option is to include the `wait` the same way @kentcdodds did: https://github.com/kentcdodds/react-testing-library#wait
