### ISSUE TITLE
Add type and clear events

### ISSUE THREAD

**Issue by nickmccurdy** [callstack/react-native-testing-library#625]
## Describe the Feature

[`user-event`](https://github.com/testing-library/user-event) has high-level [`type`](https://github.com/testing-library/user-event#typeelement-text-options) and [`clear`](https://github.com/testing-library/user-event#clearelement) events for representing user input. These can handle gradual typing, optionally with a delay, to provide more realistic tests than just using `onChange` (React DOM's version of `changeText`).

## Possible Implementations

`user-event` requires a DOM, so it probably doesn't make sense to use it. It would be easier to just implement these two functions than to try to adapt it to work for React Native, though I'm not sure exactly how you'd abstract away this functionality besides calling `changeText` with optional batching and delays.

**Comment by thymikee** [comment]
Let's start small, even in a hacky way, and iterate once we get a better understanding of the topic :)
