### ISSUE TITLE
Is there a way to get component size?

### ISSUE THREAD

**Issue by aryella-lacerda** [callstack/react-native-testing-library#635]
## Ask your Question

Hello! My use case is this: I'd like to use this lib to check if a button is accessible in that its dimensions are at least 44 pt x 44 pt. But I'm having trouble figuring out how to do this. 🤔 I tried using `jest-native`, but their matcher `toHaveStyle()` apparently only picks up styles that are explicitly defined. 

Is there a way to get the component's size, even when `width` and `height` aren't explicitly defined in their styles?

**Comment by thymikee** [comment]
Not quite, since we render in Node.js, not a real device. A native module responsible for layout would need to be mocked to return the specific view size, may be tricky to implement reliably.
