### ISSUE TITLE
`queryByText` always return null

### ISSUE THREAD

**Issue by chj-damon** [callstack/react-native-testing-library#636]
## Describe the bug
I set up a new react-native project and install the testing library following the docs. But it seems all the expected behavior does not work as an aspect.

Am I missing something? I have no idea what happened.

## Steps to Reproduce
[https://github.com/chj-damon/testDemo](https://github.com/chj-damon/testDemo)

in `App.js`:
```js
import React from 'react';
import {View, Text} from 'react-native';

export default () => {
  return (
    <View>
      <Text>hello, test</Text>
    </View>
  );
};
```

in `App.test.js`:
```js
import React from 'react';
import {render} from '@testing-library/react-native';

import App from './App';

test('render', () => {
  const {debug, queryByText} = render(<App />);

  debug();

  const result = queryByText('hello');
  expect(result).not.toBeNull();
});
```

## Screenshots
![image](https://user-images.githubusercontent.com/4902684/103409999-4e946580-4ba4-11eb-8e09-754360cda0a6.png)

**Comment by kieran-osgood** [comment]
Your test is searching for a text value that matches exactly `'hello'`, either adjust the string to be 'Hello World' ( `queryByText('Hello World');`) or my preference would be to use a case insensitive regex if you want to search for a partial string e.g. 
test('should find Hello World', async () => {
  const { getByText } = render(
    <View>
      <Text>Hello World</Text>
    </View>,
  );
  getByText(/hello/i);
});

N.B. (getBy* queries will fail if it doesn't find a match, so this tends to be a more concise way to search for an element you expect to be there, save queryBy* for when it may *not* be in the DOM e.g. error messages that conditionally appear)

**Comment by chj-damon** [comment]
@kieran-osgood thanks for your reply.
