### ISSUE TITLE
Warning: Failed prop type: Invalid prop `source` supplied to `Image`

### ISSUE THREAD

**Issue by ThakurBallary** [callstack/react-native-testing-library#648]
## Description
React Native Image component has source prop but when I ran test its giving this warning.
**Warning: Failed prop type: Invalid prop `source` supplied to `Image`**

It was resolved when I replaced `source` with `src`

`<Image source={require('./logo.png')} />` - gives warning

`<Image src={require('./logo.png')} />` - not giving warning

Looks like test are validating React props instead of React Native props

## Expected output
Test should not give warning if `source` is supplied to `Image` because it is a valid prop in React Native.

**Comment by thymikee** [comment]
The warning comes from React Native, not this library. It's probably a shortcoming of the mock or the component running in a different environment than native.
