### ISSUE TITLE
Add support for pointerEvents

### ISSUE THREAD

**Issue by Trancever** [callstack/react-native-testing-library#650]
## Describe the Feature

Currently, when there is a wrapping `View` with `pointerEvents="none"` testing lib still allows pressing buttons that are rendered inside of that View.

Expected behaviour:

```js
// component
<View pointerEvents="none">
  <Touchable onPress={onPress}>Click me</Touchable>
</View>

...

// test
const mockOnPress = jest.fn();
const { getByText } = render(<Component onPress={mockOnPress} />);

fireEvent.press(getByText('Click me'));

expect(mockOnPress).not.toHaveBeenCalled();
```

## Possible Implementations

No idea, cause I am not familiar with the codebase :(

**Comment by thymikee** [comment]
Yup, that's a fair call to make. Needs adjustments in `fireEvent` implementation:
https://github.com/callstack/react-native-testing-library/blob/199de62c74c8afb132798d46e4645485443dcc28/src/fireEvent.js#L34-L68
