### ISSUE TITLE
Jest Warnings: You are trying to import a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by IPWright83** [callstack/react-native-testing-library#658]
## Describe the bug

Getting lots of warnings when running tests with Jest:

> 
> ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
>
>      at reportLogBoxError (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:95:27)
>      at Immediate._onImmediate (node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:201:7)
> /home/iw***/src/mobileApp/myuoy/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:104
>  ExceptionsManager.handleException(error, true);

I believe that this is likely this library due to https://github.com/testing-library/native-testing-library/issues/132 but I may be wrong

## Expected behavior

No warnings

## Steps to Reproduce

I'm not exactly sure, as I don't know where this is being triggered from. The stack trace is originating within LogBoxData.

## Versions

```
npmPackages:
    @testing-library/react-native: ^7.1.0 => 7.1.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by thymikee** [comment]
This is not related to this library. It's something that likely should be mocked in the official react-native jest preset. Feel free to propose such change. Meanwhile you should be good with e.g. this:
```js
jest.mock('react-native/Libraries/LogBox/LogBox');
```

**Comment by IPWright83** [comment]
Thanks @thymikee - especially for the suggestion rather than just a close.

**Comment by thymikee** [comment]
Yea, it's a bummer it's not properly mocked in the source, but I believe it should be done there, instead of just patching it in this library. That's why I encourage folks to target their efforts to the right place.

**Comment by sabun123** [comment]
@thymikee, I just wanted to thank you for the mock you suggested. It solved my issue.

I was previously on `React Native 0.63.3` with **@testing-library/react-native** version `7.1.0` and my jest unit tests worked fine. After upgrading to `React Native 0.64` and `React 17.0.1` I started experiencing Jest failing the entire suite with :

```javascript
/Users/USER/Documents/code/project-name/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:104
  ExceptionsManager.handleException(error, true);
  
  TypeError: ExceptionsManager.handleException is not a function
    at reportLogBoxError (/Users/USER/Documents/code/project-name/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:108:21)
    at Immediate.<anonymous> (/Users/USER/Documents/code/project-name/node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js:214:7)
```

After adding the following lines to my `jest/setup.js` file, everything works again!
```JavaScript
jest.mock('react-native/Libraries/LogBox/LogBox');
```

It's unfortunate that an upgrade to React Native can still break unit tests at a fundamental level like this, but your answer is a lifesaver for those of us in production work.
