### ISSUE TITLE
Implement the "screen" object just like react-testing-library

### ISSUE THREAD

**Issue by sregg** [callstack/react-native-testing-library#664]
## Describe the Feature
See https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen

**Comment by thymikee** [comment]
Happy to accept contributions :)

**Comment by mdjastrzebski** [comment]
As a side note, you can easily simulate `screen` benefits by writing: 
```const screen = render(...);``` 
instead of 
```const { getByTestId, ... } = render(...);```.

**Comment by mdjastrzebski** [comment]
Implemented in #994. Released in [v10.1](https://github.com/callstack/react-native-testing-library/releases/tag/v10.1.0)
