### ISSUE TITLE
No handler function found for event: "press"

### ISSUE THREAD

**Issue by mksglu** [callstack/react-native-testing-library#667]
Hello everyone, when I try to use `fireEvent.press` I get this error: "No handler function found for event: "press""

```
const Button = ({onPress, title}) => (
  <TouchableOpacity testID="button" onPress={onPress}>
    <Text>{title}</Text>
  </TouchableOpacity>
);
```

```
it('Button', () => {
    const onPressMock = jest.fn();
    const title = 'press me';
    const {getByTestId} = render(<Button onPressMock={onPressMock} title={title} />);
    const button = getByTestId('button');
    fireEvent.press(button);
  });
```

## Screenshots
![image](https://user-images.githubusercontent.com/6067714/107214819-89977d80-6a1b-11eb-8307-8736a2d7c9a2.png)

## Versions
```
  npmPackages:
    @testing-library/react-native: ^7.1.0 => 7.1.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by thymikee** [comment]
Change `onPressMock={onPressMock}` to `onPress={onPressMock} `. Use TS of Flow to avoid such typos in the future :)

**Comment by lalitkumarrock** [comment]
Hii 

In react-native.I found this issue because I do not provide the callable function to the component . 
Hopefully it'll help you .
