### ISSUE TITLE
Does react-native-testing-library work on react-native 0.60.6?

### ISSUE THREAD

**Issue by FrederickEngelhardt** [callstack/react-native-testing-library#668]
## Ask your Question

**Does react-native-testing-library work on react-native 0.60.6?**

Follow up question: **Should react-native-testing-library be bumped to require `>=0.61.0`**

Looks like **react-native** on `0.60.6` requires **react** on `16.8.6` which is below the required `16.9.0` for react-native-testing-library. Is 0.60.6 compatible or should the documentation be changed to `>=0.61.0`.

This is in response to the documentation quote

> In order to properly use helpers for async tests (findBy queries and waitFor) you need at least React >=16.9.0 (featuring async act) or React Native >=0.60 (which comes with React >=16.9.0).

Upgrade link for 0.60.6 -> 0.61.0 diff
https://react-native-community.github.io/upgrade-helper/?from=0.60.6&to=0.61.0

**Comment by thymikee** [comment]
Good catch! Looks like the docs need to be updated from 0.60 to 0.61. However you should still be able to test on lower RN versions, just without async act. Would you like to send a PR do the docs? :)

**Comment by mdjastrzebski** [comment]
Closing issue as fixed.
