### ISSUE TITLE
Long press (fireEvent API)

### ISSUE THREAD

**Issue by jakub-pietras** [callstack/react-native-testing-library#707]
## Describe the Feature
Support for triggering longPress using fireEvent.
It's a must have in some situations, for example long press on list item to open up actions menu.

## Possible Implementations
API usage:
```
fireEvent.longPress(screen.getByText('Example'));
```

As far as I understand RNTL just triggers handlers attached to React elements. This should be as simple as adding new handler using invokeElement() in fireEvent file. Correct me if I am wrong though, I just started using RNTL and I didn't yet explore it in-depth.

**Comment by thymikee** [comment]
You can do `fireEvent(element, 'onLongPress')` today. For now we don't plan to add more shorthands, but this may change, e.g. to reflect only core components (where longPress is included). Closing. 

If you feel like championing this, please create a new issue describing the problem and sketching potential solutions :)
