### ISSUE TITLE
Update documentation in React Navigation example for React Native v0.64

### ISSUE THREAD

**Issue by raychanks** [callstack/react-native-testing-library#711]
React Native@0.64 had moved the file `NativeAnimatedHelper.js` from `react-native/Libraries/Animated/src/NativeAnimatedHelper` to `react-native/Libraries/Animated/NativeAnimatedHelper`(without putting the file in `src`).

Would like to add a comment to the `React Navigation` example in the documentation to signal this update.

**Comment by thymikee** [comment]
Please send a PR changing it, sounds like a great opportunity for a contribution!

**Comment by raychanks** [comment]
Sure, will send a PR for it
