### ISSUE TITLE
fireEvent.press is fired when giving container

### ISSUE THREAD

**Issue by nassim99** [callstack/react-native-testing-library#713]
## Describe the bug

Hello,
when i was testing a button, i notice weird behavior, the function is called even if the button is loading when giving rendered.container!

## Expected behavior

onPress function shouldn't be called

## Steps to Reproduce

example

button.test.js

     describe("<Button /> loading", () => {
     let loading = true;
     const setLoading = jest.fn(() => {
     loading = !loading;
     });
     let rendered: RenderAPI;
     beforeEach(() => {
     rendered = render(
      <Button onPress={setLoading} loading={loading} />,
     );
    });
      it("check loading is true ", async () => {
    expect(rendered.container.props.loading).toBeTruthy();
    //fireEvent.press(rendered.getByTestId("buttonOnPress")) // works !!
    fireEvent.press(rendered.container);

    expect(setLoading).not.toHaveBeenCalled(); // fail
    expect(loading).toBeFalsy(); // fail
    });

button.js 

    const handleOnPress = disabled || loading ? () => 0 : onPress;
    <TouchableOpacity
      activeOpacity={loading ? 1 : 0.4}
      disabled={disabled}
      style={combinedContainerStyle}
      onPress={handleOnPress}
      testID="buttonOnPress">

            <Text>
              {title}
            </Text>

    </TouchableOpacity>

**Comment by mdjastrzebski** [comment]
Closing because of lack of recent activity.
