### ISSUE TITLE
Performing a query on child element

### ISSUE THREAD

**Issue by Sakarisson** [callstack/react-native-testing-library#715]
## Ask your Question

Hey RN Testing Library maintainers! 👋 

Is it possible to perform a query within a queried element? In my case, I'd like to find an element with a certain ID and make sure that it contains some specific text.

Contrived example of what I'm trying to do:

```typescript
it('shows date', () => {
  const DATE = '01/01/2001';
  const { getByTestId } = render(
    <ElementThatRendersDate date={DATE} />,
  );

  const dateElement = getByTestId('DateContainer');

  expect(dateElement).toHaveText(DATE);
});
```

Of course the API doesn't have to follow that exact outline, but in general I'd like to find an element, and then perform a  query on that.

**Comment by raychanks** [comment]
Maybe you can refer to the `Additional jest matchers` section in README.md

After installing `@testing-library/jest-native`, you can do something like

```
it('shows date', () => {
  const DATE = '01/01/2001';
  const { getByTestId } = render(
    <ElementThatRendersDate date={DATE} />,
  );

  const dateElement = getByTestId('DateContainer');

  expect(dateElement).toHaveTextContent(DATE);
});
```

**Comment by Sakarisson** [comment]
Nice, this is exactly what I needed. Thanks for the response!

**Comment by pedpess** [comment]
@raychanks @Sakarisson After checking the docs, I installed the `@testing-library/jest-native` but even with that my `JestMatchers` doesn't recognize the new method `toHaveTextContent()`. Is there some extra config that needs to be done?

**Comment by pedpess** [comment]
Thanks, @Sakarisson ... Checking the usage of the lib I didn't know I had to import it as well. Thought it would come out of the box with RNTL :)

Usage link: https://github.com/testing-library/jest-native#usage
