### ISSUE TITLE
Does waitFor can check multiply components or only one?

### ISSUE THREAD

**Issue by Luk-kar** [callstack/react-native-testing-library#717]
Does code like that work?

```
        await waitFor(() => {
            getByText("Some text");
            getByText("Some other text");
        });

```
Because when I do something like that:

```
        await waitFor(() => getByText("Some text"));
        await waitFor(() => getByText("Some other text"));

```
I got a Warning, but it passes test:

```
Warning: You called act(async () => ...) without await. This could lead to unexpected testing behaviour, interleaving multiple act calls and mixing their scopes. You should - await act(async () => ...);
```
---------------------------------------------------------------------------------------------------------------------------------
"@testing-library/react-native": "^7.2.0",
"react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",

**Comment by nassim99** [comment]
i have used this one before and its works for me

`await waitFor(() => (
            getByText("Some text"),
            getByText("Some other text")
        ));`
