### ISSUE TITLE
Cannot assert if given string DOES NOT exists

### ISSUE THREAD

**Issue by Luk-kar** [callstack/react-native-testing-library#718]
## Describe the bug

1) When asserting if given string does not exist in component:
```
await waitFor(() => {
            expect(getByText("Some string")).toBeNull();
        });
```
2) I got the following error:
```
Unable to find an element with text: Some string
```

## Expected behavior

Not rendering the error in the console and therefore failing the test. Checking if a given string DOES NOT exist in the component.

## Steps to Reproduce

1) command: 
`yarn jest`

2) test:
```
test("Some component: valid string", async () => {
        const { getByText } = render(
            <SomeComponent />
        );
        await waitFor(() => {
            getByText("Some string").toBeNull();
        });
    });
```

## Versions
    npmPackages:
    @testing-library/react-native: ^7.2.0 => 7.2.0 
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-test-renderer: ^17.0.2 => 17.0.2

**Comment by thymikee** [comment]
Use `queryByText`, it will return null instead of throwing like `getByText`.

**Comment by Luk-kar** [comment]
Thanks, it worked out!
