### ISSUE TITLE
no Jest preset installed with 7.2.0

### ISSUE THREAD

**Issue by githorse** [callstack/react-native-testing-library#719]
## Describe the bug

After installing the package with `yarn add -D @testing-library/react-native`, and adding the [custom Jest preset line](https://github.com/callstack/react-native-testing-library#custom-jest-preset) in `jest.config.js`, I get this error:

```
yarn run v1.22.10
$ jest
● Validation Error:

  Module @testing-library/react-native should have "jest-preset.js" or "jest-preset.json" file at the root.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Sure enough, there's no `jest-preset` anything in `node_modules/@testing-library/react-native`:

```
$ ls -a node_modules/@testing-library/react-native
.
..
build
dont-cleanup-after-each.js
LICENSE
node_modules
package.json
pure.js
README.md
typings
```

## Expected behavior

Jest preset should be available (even if maybe it doesn't fix the timer thing). 

I've deleted `node_modules` and re-installed, no change. What am I doing wrong here?

## Steps to Reproduce

```
$ yarn add -D @testing-library/react-native
$ yarn test
```

## Versions

```
  npmPackages:
    @testing-library/react-native: ^7.2.0 => 7.2.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-test-renderer: 17.0.1 => 17.0.1 
```

**Comment by thymikee** [comment]
Custom preset is only available since v8.0.0-rc.0.
