### ISSUE TITLE
 TypeError: Cannot destructure property 'config' of 'options' as it is undefined.

### ISSUE THREAD

**Issue by pouyarahmti** [callstack/react-native-testing-library#743]
## Ask your Question

Hi, I have installed React Native Testing Library and i wanted to test React Navigation as the docs has explained. But i got an error which says  TypeError: Cannot destructure property 'config' of 'options' as it is undefined. I wonder if you could help me fix it.

ReactNative: 0.64.1
Jest: 27.0.3
ReactNativeTesting Library: 7.2.0

**Comment by b3coded** [comment]
@pouyarahmti React Native is using `@jest/create-cache-key-function` 26.5.0 that is incompatible with jest 27

I'm using jest 27 with yarn resolutions on my package.json
```
"resolutions": {
    "react-native/@jest/create-cache-key-function": "^27.0.2"
 }
```

if it does not work for you, maybe you should downgrade to jest 26 for now

**Comment by pouyarahmti** [comment]
It didn't work with resolutions but with downgrading to jest 26 everything was running okay. Thanks for your help

**Comment by thymikee** [comment]
See: https://github.com/facebook/react-native/pull/30637. Closing. As a workaround, you can use Yarn's `resolutions` field and pin `"@jest/create-cache-key-function": "^27.0.1"`

**Comment by charlestbell** [comment]
@pouyarahmti 's solution worked for me. Had to go to version 26. Basically this means that jest's `node --inspect-brk ./node_modules/jest/bin/jest.js --runInBand` commadn doesn't work on anything newer than 26. They really should improve their documentation.

**Comment by bonusrk** [comment]
maybe it will help someone in 2022.
i figured it out bumping all libraries connected with jest to the same (as jest) version. for me it was:

```json
{
  "devDependencies" : {
     "jest": "^29.3.1",
     "babel-jest": "^29.3.1",
      // should not raise error in runtime but fresh types are fresh
     "@types/jest": "^29.2.3",
     "ts-jest": "^29.0.3",
  }
}
```
