### ISSUE TITLE
Error boundary while running tests in Jest

### ISSUE THREAD

**Issue by HunterJS-bit** [callstack/react-native-testing-library#764]
My Test file:

```

import 'react-native';
import React from 'react';

import {cleanup, render} from '@testing-library/react-native';
import {ListScreen} from '../../../../src/screens';

import {Provider} from 'react-redux';
import {store} from '../../../../src/store/configureStore';

describe('Vehicle List Component', () => {
  beforeEach(() => jest.useFakeTimers());
  afterEach(cleanup);


  it('should render', () => {

    const navigation = {
      setParams: () => {},
      navigate: () => {}
    };

    const route = {

    };
    const component = (
      <Provider store={store}>
      <VehicleGeneralInfo navigation={navigation} route={route} />
</Provider>
    );

    const rendered = render(component);
  });
});

```

When I run my test file I get following error:

 **The above error occurred in the <ListScreen> component:
        in ListScreen
        in Provider
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.**

Does anyone has some advice or know what could be the problem ?

**Comment by AugustinLF** [comment]
Could you give us the details of the `above error` to better understand what's happening? Or a repro for us to reproduce the issue?

Based on the output it looks like an error is thrown by one of your components while rendering, but without more details I cannot help you. I'll close meanwhile, but we'll reopen as soon as I get more details.
