### ISSUE TITLE
Make async methods compatible with jest's fake timers. 

### ISSUE THREAD

**Issue by ArshanKhanifar** [callstack/react-native-testing-library#775]
## Describe the Feature

It'd be awesome if the async methods such as `waitFor` could detect if fake timers are being used, and advance the timers manually, until the condition is met. Right now they're not compatible with jest timers. This test will fail, for example: 

```

beforeEach(() => {
  jest.useFakeTimers('modern');
});

afterEach(() => {
  jest.useRealTimers();
});

test('simple async thing', async () => {
  let hello = false;
  setTimeout(() => {
    hello = true;
  }, 100);

  jest.advanceTimersByTime(200);
  await waitFor(() => expect(hello).toBeTruthy());
});

```

## Possible Implementations

Manually advance the timer in `waitFor`. Right now I'm guessing what `waitFor` does is that it repeatedly polls for the condition to happen, but when fake timers are used there are two problems: 
1. waitFor uses timers itself to operate, so maybe instead of doing setTimeouts, it should call jest.advanceTimersByTime() repeatedly, and check for the condition. It might need access to the native `setTimeout` for it not to be a tight poll. 

## Related Issues

#506

**Comment by thymikee** [comment]
Please check the v8.0.0-rc.1

**Comment by pierrezimmermannbam** [comment]
Using the @testing-library/react-native preset allows waitFor to work with modern fake timers, the documentation explains how to use the preset  https://github.com/callstack/react-native-testing-library#custom-jest-preset
