### ISSUE TITLE
Get Element By Icon

### ISSUE THREAD

**Issue by HunterJS-bit** [callstack/react-native-testing-library#777]
Hello guys I have a quick question is it possible to get element, icon ?

For Example I have following element:

```
import MCIcon from 'react-native-vector-icons/MaterialCommunityIcons';

 <TouchableOpacity
      style={[
        style]} {...props}>
      {SVG ?
        <SVG /> :
        <MCIcon name={'magnify'} size={24} color={color} />
      }
    </TouchableOpacity>

```

Is it possible to get Following element by Icon? 
Like searching by Text or any other method ??

**Comment by thymikee** [comment]
No, it's not. An icon should have an accessibilityLabel which you could query by
