### ISSUE TITLE
How to use `getByTestId` on web?

### ISSUE THREAD

**Issue by conor909** [callstack/react-native-testing-library#786]
I believe there was recently a merge to make sure `getByTestId` only returns native elements.
https://github.com/callstack/react-native-testing-library/pull/324

Does this mean we can't use `getByTestId` on web?

In my test file in `web` says no element matches the testID, where as in `iOS` it' finds the element and my test passes.  If I switch to use a `queryByText` query, it works fine on both platforms. But I'm targeting a plain react native `<View>` to check the styling on it is expected, so I need to target by `testID`.

```js
  // Fails to find ID
  if (Platform.OS === 'web') {
    test('StickyHeader should have sticky position prop on web', () => {
      const { getByTestId } = renderRoute(<AuthenticatedApp logOut={jest.fn} user={user} />)
      const stickyHeader = getByTestId('sticky-header')
      expect(stickyHeader).toHaveStyle({ position: 'sticky' })
    })
  } 

  // Passes
  if (Platform.OS === 'ios') {
    test('StickyHeader should have relative position prop on ios ', () => {
      const { getByTestId } = renderRoute(<AuthenticatedApp logOut={jest.fn} user={user} />)
      const stickyHeader = getByTestId('sticky-header')
      expect(stickyHeader).toHaveStyle({ position: 'relative' })
    })
  }
```

debug
```js
// prints out the screen structure and I can see an object with `testID='sticky-header'`
// it also includes style object with `position: 'sticky'`, so I can see it does exist
const { debug } = renderRoute(<AuthenticatedApp logOut={jest.fn} user={user} />)
debug()
```

**Comment by conor909** [comment]
Realize this was a lack of understanding

**Comment by mitramejia** [comment]
@conor909 can you expand a bit? what was the lack of understanding you realized?

**Comment by conor909** [comment]
@mitramejia I cant remember the exact issue, but I've been having trouble with testing-library in general.  Its never clear how to write the test.  Sometimes need to `await` the query, or sometimes I need to `await` the the `expect()`.  I also find it very difficult to know what query to use, `get`, `find` etc.  Generally it's usually async problems, but also even using the basic api I get warnings in the console about state updates not being wrapped in `act()`, or Im trying to update state even after a test has ended, and I have no idea how to fix those warnings, the components are not even complex.

**Comment by AlanSl** [comment]
I think the original "lack of understanding" was misunderstanding the old linked PR "to make sure getByTestId only returns native elements. https://github.com/callstack/react-native-testing-library/pull/324" - reading it as web vs native when it was actually nothing to do with web, and by "native elements" it meant React Native primitives (View, Text, TextInput) that directly correspond to an underlying iOS or Android element vs custom intermediary components that only exist in JS / React.

As for the question of how to use `*ByTestId` in cross-platform tests that include React Native Web, the closest I can find to an answer is this long discussion here - https://github.com/callstack/react-native-testing-library/pull/407

**Comment by mdjastrzebski** [comment]
@AlanSl due to various reasons (basically: available people & our time, solving one problem well instead of spreading thin), we focus on React Test Renderer-based tests. This assumption is reflected in how all our queries and event handling works, and what our own tests check. In a sense RNTL covers the general React Native platform (we do not run iOS or Android native code), so we also support RN part of RN web apps.

Rendering using RN Web renderer is quite different, and works in a completely different environment with browser APIs exposed by jsdom. This happens to be the same setup that React Testing Library is created for, so we recommend using the OG testing library as far better alternative, providing much more reliable testing at the cost of having a separate general RN Web test suit. For all of the above reasons using RNTL to test RN Web rendering is not supported, sorry.

**Comment by conor909** [comment]
At the moment I believe the only solid approach to testing web and mobile is to write 2 tests, I’m sure it’s only a matter of time before someone can marry rntl and rtl successfully, or come up with a cool new library. If anyone has any other options please share

**Comment by mdjastrzebski** [comment]
Please do not reopen this issue, as it is not actionable. If this is for reference then users can also browse closed issues. Otherwise it only clutters the overview of the features and issues we actually plan to work with. 

BTW if someone is looking for an experimental side project, then building a small wrapper over RTL + RNTL to allow testing may be a way to go.

**Comment by AugustinLF** [comment]
> At the moment I believe the only solid approach to testing web and mobile is to write 2 tests, I’m sure it’s only a matter of time before someone can marry rntl and rtl successfully, or come up with a cool new library. If anyone has any other options please share

We're using that in our app, with a small shim `testing-library.native.ts` and `testing-library.web.ts`, using some nice module resolution, and it works without much problems tbh. So IMO not really a need for a separate library :)

**Comment by conor909** [comment]
@AugustinLF that's interesting, do you have any gists?  It could help a lot of people in the react native web world

**Comment by conor909** [comment]
I've asked [this question](https://stackoverflow.com/questions/74132753/web-mobile-cross-platform-tests-by-merging-react-testing-library-with-react-na) on SO if it's more appropriate place to discuss.

**Comment by AugustinLF** [comment]
Our tooling knows how to resolve `.(web|native|ios|android)` files, both in tests and build. Based on that, from a test I can import an internal package that has will resolve either to `@testing-library/react` on web, or `@testing-library/react-native`. And then we run the test twice, once with a native configuration, and once with a web one. Implementation is not really interesting, there's not much, it's more the whole thinking and tooling that'd be relevant, but that's non trivial to share. I'll look into writing a blog post at some point, but that's not a big prio for me for now :)
