### ISSUE TITLE
Testing components with async API query libraries giving inconsistent results

### ISSUE THREAD

**Issue by wwdrew** [callstack/react-native-testing-library#810]
React Native: 0.65.1
Jest: 27.1.0
RNTL: 8.0.0-rc.1
MSW: 0.35.1

Example repo: https://github.com/wwdrew/rtk-query-async-test

I'm trying to test components that load data from an external API using React Native Testing Library. For the API access I've tried using RTK Query and React Query and they both give me the same warning:

`A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.`

Additionally, the RTK Query test fails, whereas the React Query one passes despite the warning - this is before I've mocked the endpoints using MSW. If I _do_ mock the endpoints, all tests pass successfully except the same warning still occurs.

As a sanity check, I created a custom hook to call the same endpoint and that one works as expected, with no warning.

To test a theory it was fetch-related, I even created a RTK Query version using axios too with the exact same result: test works, warning message. I've had to install a polyfill for node in order to run these tests which has been an effort in itself. The most successful fetch polyfill I've tried is `cross-fetch`, but I've tried `node-fetch` (v2 and the just-released v3), `whatwg-fetch` and `isomorphic-fetch`. They all work to varying degrees, they differ mostly in how to apply them in node as a polyfill.

As another attempt to track down where this warning is coming from, I built the exact same tests and components using React web and tested using React Testing Library and they all passed as expected but without this warning. This suggests to me it's something going on in RNTL. I've even tried using fake timers, but that completely breaks the tests.

The only workaround I've come across is to add `--forceExit --detectOpenHandles` to the jest command, but this doesn't seem like an actual solution to me and still doesn't explain why it's happening.

What I find most curious about this whole situation, though, is why it's only the query libraries I'm using that are causing this warning and not the custom hook I've written.

I've completely run out of ideas on how to solve this, so if anyone has any suggestions on what might be the cause of it or how to fix it I'd be super appreciative.

**Comment by thymikee** [comment]
RTL runs in jest-environment-jsdom, while RNTL in jest-environment-node + polyfills from the react-native preset, which is less web-friendly (RN patches some globals with its own native modules at runtime). I'd check this trait.

**Comment by wwdrew** [comment]
@thymikee Thanks for the reply, I've been trying to dig into this but I'm not getting anywhere with it.

It also doesn't explain why it works fine using a custom hook, but not when using a library to do the same thing.

**Comment by Michael-M-Judd** [comment]
FWIW we also experience this when using apollo. I don't think it's particular to the library you're using. We do full integration tests that cover large pieces of our app and we frequently hit the same issue. It's plagued our test suite for a while but we haven't come to any great conclusion as to why it happens.

**Comment by wwdrew** [comment]
I've had a think about this a little bit over the months and I did wonder if it's something to do with the components not being unmounted properly. From what I can gather, subscriptions should be closed down when the component is unmounted, which would explain why my custom hook works fine as it's only making the one call, but the libraries are being kept alive and hence failing to be unmounted.

I did try to follow that train of thought for a few minutes but I just couldn't devote any more time to it.

**Comment by mdjastrzebski** [comment]
Closing issue as stale. @wwdrew please report a new GH issue if the problem is present in the current version of RNTL (v11) in the recommended setup as in the [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic). If so, please also provide a minimal repro repository.

**Comment by ajsmth** [comment]
I ran into this and fixed by setting the cache time of queries and mutations to 0:

Ref: https://github.com/TanStack/query/issues/1847
