### ISSUE TITLE
Scroll View test keeps on failing.

### ISSUE THREAD

**Issue by irohitb** [callstack/react-native-testing-library#826]
## Describe the bug
My scroll view probably won't scroll because of which my test cases are failingl. 
 

## Expected behavior

Scroll view test should've passed

## Steps to Reproduce
I have a scroll view inside my `Home` which looks like this 
```
<ScrollView
      testID={`ProfileVertical`}
      style={styles.scrollView}
      ref={scrollViewRef}
      pagingEnabled
      contentContainerStyle={{ height: `${100 * profileData.length}%` }}
      // onScroll={onUserScroll}
      onLayout={onLayout}
      onScroll={onUserScroll}
      scrollEventThrottle={20}
      onMomentumScrollEnd={onScrollEnd}
      onScrollBeginDrag={() => setUserScrolling(true)}
    >
```

On Scroll, this changes active component (check screenshot section for gif example). 

I wrote a test case for this like this 

```
it('Scrolling to third profile adds border radius to image circle of second profile', () => {
  const eventData = {
    nativeEvent: {
      contentOffset: {y: 1387, x: 0},
      contentSize: {width: 414, height: 19423},
      layoutMeasurement: {width: 414, height: 693.5},
    },
  };
  const {getByTestId} = render(<Home />)
  fireEvent.scroll(getByTestId('ProfileVertical'), eventData);
  expect(getByTestId('image-circle-3')).toHaveStyle({ borderColor: '#81D4FA' });
})
```

I was expecting this test case to pass but this keeps on failing. 

If I change this line `expect(getByTestId('image-circle-3')).toHaveStyle({ borderColor: '#81D4FA' });` to `expect(getByTestId('image-circle-0')).toHaveStyle({ borderColor: '#81D4FA' });` then test cases passes which means that my component isn't scrolling 

This data 

```
    nativeEvent: {
      contentOffset: {y: 1387, x: 0},
      contentSize: {width: 414, height: 19423},
      layoutMeasurement: {width: 414, height: 693.5},
    },
 ```
 I am getting from console logging onScroll event when running app in simulator 
## Screenshots
![ezgif com-gif-maker](https://user-images.githubusercontent.com/32276134/134831733-e0f730ab-be6f-4d44-8b53-daaf605ef8df.gif)

## Versions

```
    @testing-library/react-native: ^7.2.0 => 7.2.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by Seauning** [comment]
me too, is there a solution now?
