### ISSUE TITLE
Unexpected behavior for <Text /> element

### ISSUE THREAD

**Issue by janhesters** [callstack/react-native-testing-library#83]
In React Native it is okay to pass a number as a child for a `<Text />` element. So
```jsx
<Text>2<Text />
```
is the same as
```jsx
<Text>{"2"}<Text />
```
or
```jsx
<Text>2.toString()<Text />
```
But since `getByText` only accepts a string as it's input, you can't find the element if it's being rendered in the first way.

This took me quite some time to debug and I think it's very counter-intuitive. Maybe there is a good solution so `getByText` finds everything rendered between `<Text />` tags?

**Comment by janhesters** [comment]
@thymikee Thank you for your help! I'm unfamiliar with regexes. Is there a way to convert an object to a regex?

Meaning ideally the test would look like this:
```
// amount is a number
getByText(props.amount)
```
which doesn't work because of the described problem.

Is there something like
```
getByText(/\d props.amount /)
```
?

**Comment by thymikee** [comment]
Yup, you can create a new regex out of a string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

**Comment by janhesters** [comment]
Hmm, thank you again for your help. I tried doing what you said. I found [this stackoverflow question](https://stackoverflow.com/questions/5752829/regular-expression-for-exact-match-of-a-string) and answer Following this I tried to match the string like this:

```js
getByText(/^props.amount.toString()$/)
```

Do you have any idea what is going wrong?

**Comment by janhesters** [comment]
I tried that way, too 

```js
const amountRegex = new RegExp(props.amount.toString());
expect(getByText(amountRegex)).toBeDefined();
```

and still the component isn't found.

**Comment by thymikee** [comment]
Awesome you made it!
