### ISSUE TITLE
Press doesn't exist on element

### ISSUE THREAD

**Issue by joshuakelly** [callstack/react-native-testing-library#85]
If i have the following component setup and then `render(<SignUp />);` in a test file. Trying to check if the event fires on press does not register.

```jsx
export class SignUp extends Component {
  handleSignUp = () => ({})

  render() {
    return (
      <View>
        <TouchableOpacity testID="sign-up-button" onPress={this.handleSignUp}>
          <Text>Sign up</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

test('should invoke specified event', () => {
  const handleSignUp = jest.fn();
  const { getByTestId } = render(<SignUp />);
  fireEvent(getByTestId('sign-up-button'), 'press');
  expect(handleSignUp).toHaveBeenCalled();
});

Expected mock function to have been called, but it was not called.
```

**Comment by thymikee** [comment]
Let's have a look at your test:
```js
  const handleSignUp = jest.fn(); 
  const { getByTestId } = render(<SignUp />);
  fireEvent(getByTestId('sign-up-button'), 'press');
  expect(handleSignUp).toHaveBeenCalled();
```
You're declaring a mock handler, but not passing it to the component. The component is calling `handleSignUp` – but the one which is inside your component instance, no the one you declared earlier and never passed anywhere.

Usually you'd pass it as a prop:
```jsx
  const handleSignUp = jest.fn();
  const { getByTestId } = render(<SignUp onSignUp={handleSignUp} />);
  expect(handleSignUp).toHaveBeenCalled();
```

This way you pass a mock, so it actually has an ability to be called.

**Comment by joshuakelly** [comment]
How would I test a class method using this though? If I make a press on the button that calls a class method, the class method should fire. There's no props on this component.

**Comment by thymikee** [comment]
And how does user know that this method fired? What happens? Whether a method fired inside a component it's its own business, it's private, it's an implementation detail. You should be only interested in observable output.

So, what happens? Either a prop call (not this case) or setState (the output will change then and you should assert on that), or an API call (you'll need to mock network request and assert on that).
