### ISSUE TITLE
Get a Pressable given a text contained within the same level of its wrapping view 

### ISSUE THREAD

**Issue by jmoliugp** [callstack/react-native-testing-library#861]
## Ask your Question

Hi everyone, I am still new to the library, in the last few days I have been testing it and I would like to know how to solve the scenarios in which I have a list of components where each element has at least a text that identifies it and at the same level a pressable that wraps an image or a SVG.

I'd like to query for the list element given a text and then interact with the pressable contained within the same element.

As an example, how could you select the pressable of an element from the title of a ToDo given this component?

```typescript
type Props = {
  navigation: HomeProps
}

export const TodoNote: React.FC<{ item: TodoItem }> = ({ item }) => {
  const { mutate } = useOptimisticEditTodoMutation()

  const navigation = useNavigation<DetailsProp>()

  let icon = item.isChecked ? checkIcon : uncheckIcon

  const onPress = async () => {
    await mutate({ ...item, isChecked: !item.isChecked })
  }

  const navToDetails = () =>
    navigation.navigate(Routes.Details, {
      todoId: item.id,
    })

  return (
    <View style={styles.listElement}>
      <Pressable onPress={navToDetails}>
        <View style={styles.listContent}>
          <View style={styles.textGroup}>
            <Text style={styles.todoTitle}>{item.title}</Text>
            <Text style={styles.todoDescription}>{item.description}</Text>
          </View>
          <View style={styles.elementCheck}>
            <Pressable onPress={onPress}>
              <Image source={icon} />
            </Pressable>
          </View>
        </View>
        <View style={styles.separation} />
      </Pressable>
    </View>
  )
}


export const Home: React.FC<Props> = ({ navigation }) => {
  const { data } = useTodosQuery()
  useNavOptions(navigation)

  return (
    <SafeAreaView style={styles.navbarContinuation}>
      <StatusBar backgroundColor={Palette.PRIMARY} />
      <View style={styles.whiteBackground}>
        <FlatList<TodoItem>
          data={data}
          renderItem={(item) => <TodoNote item={item} />}
          keyExtractor={(item) => item.id.toString()}
        />
        <View>
          <Pressable onPress={noop}>
            <Text style={styles.clearAllDone}>{strings.clearDone}</Text>
          </Pressable>
        </View>
      </View>
    </SafeAreaView>
  )
}
```

**Comment by MattAgn** [comment]
Hi @jmoliugp ! There is something I don't quite understand in your example. According to your code, you have a pressable inside another pressable. When you simulate a press on your test (with `fireEvent.(getByText("my note"))`), you will trigger the onPress from the outer pressable (so the `navToDetails ` function) because the onPress event will bubble up. Is that what you want? Or do you want to know how to trigger the onPress on the image?

**Comment by mdjastrzebski** [comment]
@MattAgn I am curious which `Pressable` will be actually called inside the test: inner or outer. 

Also which should be called to make sense. As far as I understand how RN works, then inner `Pressable` will be called and will consume the event, so that outer `Pressable` will never receive it.

**Comment by MattAgn** [comment]
@mdjastrzebski you're right, I don't remember why I wrote that but I agree with you, I think if it bubbles up, the first pressable will catch it
Here's a quick snack that shows it https://snack.expo.dev/@mattagn/nervous-truffle

**Comment by mdjastrzebski** [comment]
@jmoliugp In very simplified terms when you use any of the `byText` queries then it will return you the deepest level `Text` element that contains given text or matches given regex. If you then call `fireEvent.press` on that element, then event dispatching logic in RNTL will look through its ancestors to find the nearest *host* view that contains `onPress` event handler.

So in your case this should simply be:
```ts
const item = getByText('Title of element here');
fireEvent.press(item);
```
