### ISSUE TITLE
Implement `renderHook`

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#869]
## Describe the Feature

See https://github.com/testing-library/react-testing-library/pull/991 for details

## Possible Implementations

Copy the implementation from RTL.

**Comment by MattAgn** [comment]
Hi @thymikee! I'd be glad to help on this, I'll make a  PR shortly

**Comment by pierrezimmermannbam** [comment]
Hi @thymikee, @MattAgn told me he finally couldn't find time for this so I made a pr

**Comment by manugo-dev** [comment]
Hello there!

How about the waitForNextUpdate function ? Im trying to figured out how to upgrade my tests to be compatible with the new renderHook on the react-testing-library

<img width="533" alt="image" src="https://user-images.githubusercontent.com/17772376/164291396-747e3bc1-c646-411f-a6cb-cbd9e9ccbd10.png">

**Comment by pierrezimmermannbam** [comment]
@manugo-dev  you should be able to use react-native-testing-library's waitfor instead. If I'm correct, being able to use the async utils from the library instead of utils such as waitForNextUpdate that are a bit too focused on implementation detailswas one of the reasons why it was decided to implement a renderHook equivalent on react-native-testing-library and on react-testing-library's side

**Comment by mdjastrzebski** [comment]
Closing as implemented by #963.

**Comment by kylebake** [comment]
> @manugo-dev you should be able to use react-native-testing-library's waitfor instead. If I'm correct, being able to use the async utils from the library instead of utils such as waitForNextUpdate that are a bit too focused on implementation detailswas one of the reasons why it was decided to implement a renderHook equivalent on react-native-testing-library and on react-testing-library's side

Am I correct in assuming that what you mean is there's no built in way to `waitFor` the return values of hooks directly anymore and we will need to always test the consumers of the hooks and have to `waitFor` elements to show/hide based on the values of the hook?

**Comment by AugustinLF** [comment]
I believe what they mean is that you can simply use `waitFor` to wait for the value of the hook to change. Something like that:
```
import {waitFor, renderHook} from '@testing-library/react-native'
import myHook from './myHook'

test('myHook', async () => {
  const {result} = renderHook(() => myHook())
  await waitFor(() => {
    expect(result.current).toBe(1)
  })
})
```

**Comment by kylebake** [comment]
Yes that's how the other libraries typically work with waitFor, but that's not the functionality I'm seeing with RNTL. I opened a [separate issue here](https://github.com/callstack/react-native-testing-library/issues/1030) that I'm going to be looking more into
