### ISSUE TITLE
RNTL accidentally triggers `jest.useFakeTimers`

### ISSUE THREAD

**Issue by Niryo** [callstack/react-native-testing-library#886]
## Describe the bug
I am using sinon-fake-timers together with jest, because jest's exposes only minimal part of sinon timers and I need more advanced capabilities. The thing is that React native testing library mistakenly thinks that I am using "jest.useFakeTimers", because of [this check](https://github.com/callstack/react-native-testing-library/blob/c42bae123d69375e27b94ff0329380a13e31e87b/src/helpers/timers.js#L40):  

```javascript
  if (
    typeof globalObj.setTimeout.clock !== 'undefined' &&
    // $FlowIgnore[prop-missing]
    typeof jest.getRealSystemTime !== 'undefined'
  )
```

The first statement is true because I am using sinon fake timers, and the second is true because I am using jest, so it assumes that I am using `jest.useFakeTimers`, and it automatically turn it on for me [here](https://github.com/callstack/react-native-testing-library/blob/main/src/helpers/timers.js#L17):

```javascript
  if (fakeTimersType) {
    jest.useFakeTimers(fakeTimersType);
  }
```

This results in both custom sinon timer and jest's fake timers being installed, and it causes issues in my tests. 

## Expected behavior

`jest.useFakeTimers` should not be called if the user didn't call it explicitly.

## Steps to Reproduce
use jest 27 and sinon-fake-timers

## Versions

  npmPackages:
    @testing-library/react-native: ^9.0.0 => 9.0.0 
    react-test-renderer: ^17.0.2 => 17.0.2

**Comment by mdjastrzebski** [comment]
@Niryo can you check if the issue persists with current version of RNTL with Jest 29?

**Comment by Niryo** [comment]
Yea, I'll check it later this week

**Comment by Niryo** [comment]
@mdjastrzebski yep, it's still an issue

**Comment by mdjastrzebski** [comment]
@Niryo thanks for checking it. BTW Jest recently (v27 or v28) added more features to its fake timers implementation. Does sinon-fake-timers still has some features that Jest does not?

**Comment by Niryo** [comment]
@mdjastrzebski jest still exposes only a subset of sinon's options

**Comment by Niryo** [comment]
I agree that it's a rare use case. what about introducing an env param? you already have this env param? you already have this `RNTL_SKIP_AUTO_CLEANUP`, I can add another one like  `RNTL_SKIP_SETTING_TIME_MOCKS`.

**Comment by mdjastrzebski** [comment]
Sounds like a reasonable solution that would not complicate the API surface for regular users.

@Niryo would you be able to submit a PR for that?

**Comment by Niryo** [comment]
yep, i'll do it

**Comment by Niryo** [comment]
https://github.com/callstack/react-native-testing-library/pull/1169
