### ISSUE TITLE
Combining jsdom testEnvironment and fake timers results in timeout errors

### ISSUE THREAD

**Issue by dcalhoun** [callstack/react-native-testing-library#896]
## Describe the bug

Combining `testEnvironment: 'jsdom'` and fake timers, regardless of "legacy" or "modern" timers, results in timeout errors. It would appear that `setImmediate` does not perform as expected, breaking the built-in `cleanup` functionality of `@testing-library/react-native`.

This issue occurs in Jest 27, not Jest 26. Jest 27 includes [a fair number of changes](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults), including [changes to `setImmediate`](https://github.com/facebook/jest/pull/11222). 

<details><summary>Error Details</summary>

```
> rntl-jsdom-fake-timers@0.0.1 test
> jest

 PASS  ./node-real-timers.test.js
 PASS  ./node-fake-timers.test.js
 PASS  ./jsdom-real-timers.test.js
 FAIL  ./jsdom-fake-timers.test.js (5.829 s)
  ● jsdom test environment with fake timers › does not timeout

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      3 |  */
      4 |
    > 5 | import "@testing-library/react-native";
        | ^
      6 |
      7 | beforeEach(() => {
      8 |   jest.useFakeTimers();

      at Object.<anonymous> (node_modules/@testing-library/react-native/build/index.js:29:3)
      at Object.<anonymous> (jsdom-fake-timers.test.js:5:1)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        6.732 s
Ran all test suites.
```

</details>

## Expected behavior

Combining `@testing-library/react-native`, `testEnvironment: 'jsdom'`, and fake timers does not cause tests to fail with timeout errors. 

## Steps to Reproduce

1. Clone [the reproduction](https://github.com/dcalhoun/rntl-jsdom-fake-timers). 
2. `npm install`
3. `npm run test`

## Screenshots

n/a

## Versions

```
  npmPackages:
    @testing-library/react-native: ^9.0.0 => 9.0.0
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-test-renderer: 17.0.2 => 17.0.2
```

**Comment by mdjastrzebski** [comment]
We only suport `testEnvironment: 'node'`.

If you want to test under `jsdom` (e.g. for React Native Web) then React Testing Library is more suitable option as it provides better interaction with JSDOM.

**Comment by AugustinLF** [comment]
Might be worth warning if that's the case? Where I work we share the same test file for web and native, and have jsdom setup for all our RNTL tests. I'll fix that, but I didn't know it could be a problem.

**Comment by kopax-polyconseil** [comment]
Hello, we also have the same problem and as @AugustinLF pointed out, where can we found the upgrade guide for this version ? We are not aware of what action should be done to succeed an upgrade to jest 27.

**Comment by dcalhoun** [comment]
> Hello, we also have the same problem and as @AugustinLF pointed out, where can we found the upgrade guide for this version ? We are not aware of what action should be done to succeed an upgrade to jest 27.

@kopax-polyconseil there are two options: 

1. Change your Jest configuration to `testEnvironment: 'node'` and address any incompatibility in your test (e.g. DOM references).
2. Continue using `testEnvironment: 'jsdom'` and replace RNTL usage with React Testing Library. 

Option 1 is ideal if achievable for your code, as tests will run faster. 

Also, you may be able to mix both options as need by setting the testing environment for individual files as need [with a comment](https://jestjs.io/docs/configuration#testenvironment-string) in a given test file.

**Comment by thymikee** [comment]
To add to @mdjastrzebski's comment:
> We only suport testEnvironment: 'node'.
> If you want to test under jsdom (e.g. for React Native Web) then React Testing Library is more suitable option as it provides better interaction with JSDOM.

The thing is that even though this library may work within "jsdom" environment, we can't give any guarantee on that, because we're not testing it. We advise using "node" for various reasons outlined in this thread and other ones. 

However, I'm happy to learn about usecases we may miss by not actively supporting "jsdom" :)

**Comment by thymikee** [comment]
@kopax-polyconseil it's unrelated to this library, but you can mock out the `console` object however you like, without relying on external library.

**Comment by kopax-polyconseil** [comment]
You misunderstood me, this module console-fail-test is not a logger, it is meant to fail test if they are logs.

I have described the issue here since we tried the upgrade to jest 27, we are unable to fix it : https://github.com/Codecademy/console-fail-test/issues/72#issuecomment-1190356938

Perhaps you have a hint for us, I don't have any idea atm yet.

**Comment by MaxToyberman** [comment]
how did jsdom work with jest 26 ?

**Comment by dcalhoun** [comment]
> how did jsdom work with jest 26 ?

👋🏻 @MaxToyberman. As I mentioned in the original issue description (quoted below), there were a fair number of changes between Jest 26 and Jest 27 — it may be difficult to provide a concise answer to your question. Also, this issue is quite old, the project maintainers may not notice or respond to new comments. I suggest creating a new issue with details on any specific problems you encountered. 🙇🏻 

> This issue occurs in Jest 27, not Jest 26. Jest 27 includes [a fair number of changes](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults), including [changes to `setImmediate`](https://github.com/facebook/jest/pull/11222).
