### ISSUE TITLE
Setting pointerEvents to "box-none" prevents triggering onTouch* and onLayout events on the element

### ISSUE THREAD

**Issue by dcalhoun** [callstack/react-native-testing-library#897]
## Describe the bug

Setting `pointerEvents: 'box-none'` on a `View` prohibits triggering `onTouch*` or `onLayout` events on the `View`. This behavior differs from React Native itself. This [Expo Snack](https://snack.expo.dev/@davidcalhoun/pointerevents-and-ontouch-events) showcases that pressing the child `Pressable` of a `<View pointerEvents="box-none" />` still triggers the `onTouchStart` and `onTouchEnd` events. This change in behavior, which appears to differ from React Native, began in with `7.2.0` due to changes in https://github.com/callstack/react-native-testing-library/pull/655.

## Expected behavior

Invoking `fireEvent.trigger(viewWithPointerEventsBoxNone, "onTouchStart")` results in triggering the `View`'s `onTouchStart` handler. 

Similarly, invoking `fireEvent.trigger(viewWithPointerEventsBoxNone, "onLayout")` results in triggering the `View`'s `onLayout` handler. 

## Steps to Reproduce

1. Press the "Press me" text in the [Expo Snack](https://snack.expo.dev/@davidcalhoun/pointerevents-and-ontouch-events) to observe the expected behavior. 
2. Clone the [reproduction case](https://github.com/dcalhoun/rntl-reproduction-cases/tree/pointerevents-box-none-and-ontouchevents), specifically the `pointerevents-box-none-and-ontouchevents` branch. 
3. `npm install`
4. `npm run test`

## Screenshots

n/a

## Versions

```
  npmPackages:
    @testing-library/react-native: ^9.0.0 => 9.0.0
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-test-renderer: 17.0.2 => 17.0.2
```

**Comment by thymikee** [comment]
We support gesture responder system, but not `onTouch*`. I see they're not documented though. Ideas why is that?

**Comment by dcalhoun** [comment]
> We support gesture responder system, but not `onTouch*`. I see they're not documented though. Ideas why is that?

@thymikee great question. I am not sure. I found https://github.com/facebook/react-native/issues/23686, which attempted to open a discussion on this specifically. It was closed as off-topic. Unfortunately, there does not appear to be a new discussion in the [appropriate issue tracker](https://github.com/facebook/react-native-website/issues). 

In regards to `onLayout`, it _is_ documented. Is it safe to presume this library _should_ support triggering it with `fireEvent('layout', myElementWithOnLayout)`? If so, I am happy to update my reproduction to include an `onLayout` example or open a PR with a failing test.

**Comment by thymikee** [comment]
Is it possible `onTouch*` are only available with Fabric renderer? There's an example using those so it's definitely an existing feature, but not well documented: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/packages/rn-tester/js/examples/PointerEvents/PointerEventsExample.js

In this light we should extend our pointer events support to these events. `onLayout` should work as well, yes.

**Comment by dcalhoun** [comment]
> Is it possible `onTouch*` are only available with Fabric renderer? 

No, I do not believe so. The failing test case I provided for this issue originates from the WordPress Gutenberg project, which [utilized `onTouch*`](https://github.com/WordPress/gutenberg/commit/2436759c5ef420fc0186e38418fe4f8ae8243bfc#diff-7b2b897ad3d0b43301ff571ca03785e54a80cd10cd254090998e75ee84121dd6R265-R269) alongside of [React Native `0.61.5`](https://github.com/WordPress/gutenberg/blob/2436759c5ef420fc0186e38418fe4f8ae8243bfc/packages/react-native-editor/package.json#L60) at the time. I do not believe React Native `0.61.5` leveraged the Fabric renderer. 
 
> In this light we should extend our pointer events support to these events. `onLayout` should work as well, yes.

👍🏻 Great.
