### ISSUE TITLE
Navigating on a horizontal FlatList doesn't work

### ISSUE THREAD

**Issue by matthias-fi** [callstack/react-native-testing-library#917]
## Navigating on a horizontal FlatList doesn't work

I'm trying to test the behavior of a horizontal `<FlatList />`. 

- Rendering the `<FlatList />` works
- Asserting the content of the first element works
- However, when I  press my "Next" button to navigate to the second FlatList Item, the test render isn't able to detect any elements from the second item.

## Expected behavior

I expect the render method to be able to navigate to the next element.

## Steps to Reproduce

-> [Codesandbox Demo](https://codesandbox.io/s/laughing-alex-nb84x?file=/src/App.js)

This is a minimal reproduction of the bug, including the test case:

```jsx
import {fireEvent, render, waitFor} from '@testing-library/react-native';
import React from 'react';
import {View, Dimensions, FlatList, Text} from 'react-native';

it('Flatlist can navigate to the second element', async () => {
  const {getByText} = render(<FlatListUnderTest />);

  expect(getByText('First item')).toHaveTextContent('First item');

  fireEvent.press(getByText('Next'));

  await waitFor(() => {
    expect(getByText('Second item')).toHaveTextContent('Second item');
  });
});

const FlatListUnderTest = () => {
  const screenWidth = Dimensions.get('screen').width;
  const flatListRef = React.useRef(null);

  const flatListItems = ['First item', 'Second item'];

  const scrollToNextItem = () => {
    // Hard-coded index for simplicity
    flatListRef.current.scrollToIndex({
      index: 1,
    });
  };

  const getFlatListItemLayout = (data, index) => ({
    index,
    length: screenWidth,
    offset: screenWidth * index,
  });

  const renderFlatListItem = ({item}) => (
    <View style={{width: screenWidth, marginTop: 200}}>
      <Text>{item}</Text>
      <Text onPress={scrollToNextItem}>Next</Text>
    </View>
  );

  return (
    <FlatList
      ref={flatListRef}
      horizontal={true}
      pagingEnabled={true}
      scrollEnabled={false}
      data={flatListItems}
      renderItem={renderFlatListItem}
      initialNumToRender={1}
      maxToRenderPerBatch={1}
      getItemLayout={getFlatListItemLayout}
      showsHorizontalScrollIndicator={false}
    />
  );
};
```

### Screenshot of test error

<img width="668" alt="test-case-error" src="https://user-images.githubusercontent.com/60504241/153885856-706d7a6c-3d7b-4f6b-aad2-54d150dd56ce.png">

## Versions

```
  npmPackages:
    @testing-library/react-native: ^9.0.0 => 9.0.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-test-renderer: 16.13.1 => 16.13.1 
```

**Comment by pierrezimmermannbam** [comment]
I believe this has to do with the way react native mocks the scrollview which is used by flatlists as well.

In the [react native jest setup file](https://github.com/facebook/react-native/blob/main/jest/setup.js) : 

```javascript
.mock('../Libraries/Components/ScrollView/ScrollView', () => {
    const baseComponent = mockComponent(
      '../Libraries/Components/ScrollView/ScrollView',
      {
        ...MockNativeMethods,
        getScrollResponder: jest.fn(),
        getScrollableNode: jest.fn(),
        getInnerViewNode: jest.fn(),
        getInnerViewRef: jest.fn(),
        getNativeScrollRef: jest.fn(),
        scrollTo: jest.fn(),
        scrollToEnd: jest.fn(),
        flashScrollIndicators: jest.fn(),
        scrollResponderZoomTo: jest.fn(),
        scrollResponderScrollNativeHandleToKeyboard: jest.fn(),
      },
    );
```

If you use react-native preset or even @testing-library/react-native preset the scrollview is mocked in your tests and since the scrollTo method is just a jest function it will do nothing when scrolling in a test. I added a log in the the mock of the scrollTo function and it is indeed this method that is called when the next button is pressed.

Unfortunately I don't see other solutions to your problem than creating your own flatlist mock or reporting this issue on the react native repo but I'm unsure they'll be willing to change this behaviour

Good luck !
