### ISSUE TITLE
Fire a "swipe" event on a Swipeable component

### ISSUE THREAD

**Issue by gaetan-yg** [callstack/react-native-testing-library#918]
## Ask your Question
I am still quite new to react native and react native testing, so maybe I am missing something.

I have a Swipeable component, something like  :
```javascript
<Swipeable
      ref={swipeableRef}
      renderLeftActions={renderLeftActions}
      renderRightActions={renderRightActions}
      onSwipeableLeftOpen={() => decrease(product)}
      onSwipeableRightOpen={() => increase(product)}
      rightThreshold={70}
      leftThreshold={70}
    >
       <Text style={nameStyle}>{product.name}</Text>
       <Text style={quantityStyle}>{product.quantity}</Text>
 </Swipeable>
```
I am trying to test that swipe left or right triggers the correct action, however I couldn't find a way to fire a "swipe". I ended firing onswipeableRightOpen ie: 
```javascript
fireEvent(getByText('Bananas'), 'swipeableRightOpen')
```

This lets me test my action but I am testing an implementation details here, is there a way to fire a "generic" swipe event? similar to what a real user would do ?

**Comment by thymikee** [comment]
There's no generic swipe event unfortunately. We're operating in React renderer and there's multiple way to achieve this. For your case `fireEvent(getByText('Bananas'), 'swipeableRightOpen')` should be good enough. If you want generic swipe testing, you'll need to use an e2e testing framework, like Detox or Appium

**Comment by gaetan-yg** [comment]
Thanks !
