### ISSUE TITLE
getByText() failing in most basic use case, need help

### ISSUE THREAD

**Issue by jkoutavas** [callstack/react-native-testing-library#920]
Okay, so I'm brand new to react-native-testing as of this morning and have not been able to do something as simple as do `getByText()`. So, I'm not going to claim this issue is a bug with the library, but a "bug" with my basic understanding of how to use it. Please help me see what I'm missing? Thanks.

Given this jest test file in my React Native 0.67.2 app:

```ts
import React from 'react';
import { Text } from 'react-native';
import { cleanup, render, RenderAPI } from '@testing-library/react-native';

describe('react-native-test example', () => {
  let c: RenderAPI;

  beforeEach(() => {
    c = render(<Text>example</Text>);
  });

  afterEach(cleanup);

  test('getByText()', () => {
    c.debug();
    expect(c.getByText('example')).toBeDefined();
  });
});
```

Why do I get this result?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1264625/154850544-5a6d97e9-acd2-4292-935e-cc955624135b.png">

I also tried `<Text>{'example'}</Text>` and `getByText(/example/)` to no avail.

## Versions:

```
    "react": "~17.0.2",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-native": "^9.0.0",
    "jest": "^25.1.0",
```

**Comment by jkoutavas** [comment]
I ended up solving it like so:

```ts
import React from 'react';
import { Text } from 'react-native';
import { cleanup, render, RenderAPI } from '@testing-library/react-native';
import '@testing-library/jest-native/extend-expect';

describe('react-native-test example', () => {
  let c: RenderAPI;

  beforeEach(() => {
    c = render(<Text testID="test">example</Text>);
  });

  afterEach(cleanup);

  test('getByText()', () => {
    c.debug();
    expect(c.getByTestId('test')).toHaveTextContent('example');
  });
});
```

Did I need to go this far?

**Comment by thymikee** [comment]
Nah, it should work. Are you sure you have the same exact version of `react` and `react-test-renderer`?

**Comment by jkoutavas** [comment]
> Nah, it should work. Are you sure you have the same exact version of `react` and `react-test-renderer`?

I'm using `react` and `react-test-renderer` v17.0.2.

**Comment by jim-at-jibba** [comment]
Any movement on this. I am experiencing the same. Using the same versions as above.

**Comment by AugustinLF** [comment]
Any way you could produce a repo we could check out? Because we have tests for cases like that, so it definitely works in general.

**Comment by clrnd** [comment]
Managed to get a small case failing here:

https://github.com/clrnd/react-native-testing-library-example-bug

**Comment by mdjastrzebski** [comment]
I've done some quick research based on repro repo, by adding `console.log`s to `node_modules` of RNTL and found that the culprit is [this line](https://github.com/callstack/react-native-testing-library/blob/2199c1db1b78325688f66d1f4784a9e0303b4869/src/helpers/byText.js#L54) which returns this object when logged to `console.log`:
```
{
    act: [Getter],
    cleanup: [Getter],
    fireEvent: [Getter],
    flushMicrotasksQueue: [Getter],
    render: [Getter],
    shallow: [Getter],
    waitFor: [Getter],
    waitForElement: [Getter],
    waitForElementToBeRemoved: [Getter],
    within: [Getter],
    getQueriesForElement: [Getter],
    getDefaultNormalizer: [Getter]
}
```
Which looks like our own export! Seems like `require('react-native')` is returning output from `requerie('@testing-library/react-native')`

@thymikee , @AugustinLF any idea what might happening?

**Comment by mdjastrzebski** [comment]
I was able to make the test pass. Require changes:
1. In `jest.config.js` L23: `moduleDirectories: ['node_modules', './'],` => `moduleDirectories: ['node_modules'],` <-- This the culprit of messing the imports
2. In `App.test.tsx` L14: `expect(btn).toBeInTheDocument();` => `expect(btn).toBeTruthy();`. There is no concept of document in RNTL.

@clrnd Overall your setup in repro repo is quite strange, e.g. using `testEnvironment: "jsdom"`, ` "jsx": "react"` for tests, `moduleDirectories` mentioned above. 

@thymikee, @AugustinLF Seems like we need some good example project for typescript.

**Comment by clrnd** [comment]
Thanks a lot @mdjastrzebski !

What changes would you make to the setup? Like what would a "correct" value be for `testEnvironment` be?

**Comment by thymikee** [comment]
@clrnd `node` or any custom env that's based on node and not JSDOM. We expect the tests are running in a pure Node.js env, no need for overhead here

**Comment by mdjastrzebski** [comment]
I've added the root cause/fix for this issue to our Troubleshooting guide: https://callstack.github.io/react-native-testing-library/docs/troubleshooting#matching-react-native-react--react-test-renderer-versions
