### ISSUE TITLE
query / test starts after two rerenders of the view

### ISSUE THREAD

**Issue by wmatyjanomtek** [callstack/react-native-testing-library#921]
## Describe the bug

Hi, 
I'm not sure if it's a bug or a question, but it feels for me that it is working the wrong way. 
I want to test a simple thing in one of my views, which is a loader appearance. 

View looks like this: 

```
export const TheView: React.FC<Props> = (props) => {
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
        setIsLoading(true);
        performWhateverPromiseOrRequest()
          .finally(() => {
            setIsLoading(false);
          });
      }
    }
  }, []);

  return (
    <View style={styles.container}>
      {isLoading && <View testID="activityIndicator" style={styles.activityIndicator} />}
{...theRestOfTheView}
    </View>
  );
};
```

And the test looks like this: 

``` 
it('should show the loader at the beginning if coordinates arent defined', async () => {
   // mocks

    const { findByTestId, queryByTestId } = render({
      initialState
    });

    console.log('here');

    const loader = queryByTestId('activityIndicator');

    await waitFor(() => expect(loader).not.toBeNull());
  });
```

Please take a look at the console logs both in the view and the test. 
The result I get from them is: 

  console.log
    false

  console.log
    true

  console.log
    here

  console.log
    true

  console.log
    true

  console.log
    false

It looks like the view is being rerendered twice before the query / test even begins. This is the snippet from the render.js file from the lib: 

```
function render(component, {
  wrapper: Wrapper,
  createNodeMock
} = {}) {
  const wrap = innerElement => Wrapper ? /*#__PURE__*/React.createElement(Wrapper, null, innerElement) : innerElement;

  const renderer = renderWithAct(wrap(component), createNodeMock ? {
    createNodeMock
  } : undefined);
  const update = updateWithAct(renderer, wrap);
  const instance = renderer.root;
  (0, _cleanup.addToCleanupQueue)(renderer.unmount);
  return { ...(0, _getByAPI.getByAPI)(instance),
    ...(0, _queryByAPI.queryByAPI)(instance),
    ...(0, _findByAPI.findByAPI)(instance),
    ...(0, _a11yAPI.a11yAPI)(instance),
    update,
    container: instance,
    rerender: update,
    // alias for `update`
    unmount: renderer.unmount,
    toJSON: renderer.toJSON,
    debug: debug(instance, renderer)
  };
}
```

and it seems like I'm right - I can see `render` and `update` methods called.

## Expected behavior

I'd like the "hear" console.log to appear before any other console.log so that I can actually wait for things that happen from the beginning of the tested component's lifecycle. 

## Steps to Reproduce

Just implement a similar code, put the console logs in the same places and see what happens.

## Versions

 @testing-library/react-native: ^7.2.0 => 7.2.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-test-renderer: 17.0.2 => 17.0.2

**Comment by pierrezimmermannbam** [comment]
The view seems to be rerendered after twice after the render method is called since here is logged before. And I believe that updateWithAct and renderWithAct both return functions, so the render and update methods are not actually called. I tried to reproduce but didn't get the same result. Here is my code : 

```javascript
function FakeComponent() {
  const [isloading, setisloading] = useState(false);

  useEffect(() => {
    setisloading(true);

    const fakeFunc = async () => {
      await Promise.resolve();
      setisloading(false);
    }

    fakeFunc();
  }, []);

  console.log('render');
  console.log('is loading', isloading);

  return <Text>{isloading ? 'loading' : 'finished'}</Text>;
}

it('should renderr once', async () => {
  const { getByText } = render(<FakeComponent />);

  expect(getByText('loading')).toBeTruthy();

  await waitFor(() => {
    expect(getByText('finished')).toBeTruthy();
  });
});
```

Have you tried to add logs in the snippet you showed before the renderWithAct method is called for instance to confirm your hypothesis ?
What does the function performWhateverPromiseOrRequest actually does ? Is it possible that  it triggers state updates that would cause your component to rerender ?

**Comment by wmatyjanomtek** [comment]
@pierrezimmermannbam Thank you for your time ;) 
Well, the `performWhateverPromiseOrRequest` is actually a redux action and it dispatches some things which update the state of the store.

But, are you sure your code didn't get you the same result? Look:

You're starting with the `isloading` set to false and in your `getBy` query you're giving it the 'loading' text which suggests the `isloading` piece of state is set to true. :) 

That's exactly what happened at mine, assuming your test is passing ofc.

**Comment by pierrezimmermannbam** [comment]
@wmatyjanomtek sorry I didn't understand correclty your issue, I thought the problem was that the component rerendered twice while the value of isLoading didn't change.

It is the intended behavior that synchronous effects are run immediately because it ressembles the way the user perceives it., plus it would be really hard to test anything if we needed to wait before useEffects are run. This behavior ensures that when a state changes all useEffects that should trigger do before your next query. 

I'm not sure I understand well your use case either, why do you wish to wait for the things that happen at the beginning of the lifecycle ?

**Comment by wmatyjanomtek** [comment]
I wanted to check if the loader showed up. Now it doesn't matter if it was shown at the beginning or not, right? 
It also means, from a more technical perspective, that the first query can be performed after all the effects are finished, right?

**Comment by pierrezimmermannbam** [comment]
@wmatyjanomtek yes I think it doesn't matter, it is shown instantaneously to the user.
 All synchronous code tun in useEffects will be completed before your first query so there's no need to wait for them to be finished, you should only use waitFor when promises are involved. Also if there are timeouts then you should use jest fake timers api

In addition to what I said earlier, here is the description of the act util from react-test-renderer

```
Wrap any code rendering and triggering updates to your components into act() calls.

Ensures that the behavior in your tests matches what happens in the browser more closely by executing pending useEffects before returning. This also reduces the amount of re-renders done.
```

The act util ensures that all useEffects will be run when udpating a component/hook state in a test to match better the user's experience so it's definitely the intended behavior

**Comment by wmatyjanomtek** [comment]
@pierrezimmermannbam  So I think I didn't catch that properly. Understood. Thank you for your time (again) and explanations. ;)
