### ISSUE TITLE
Warning: You called act(async () => ...) without await

### ISSUE THREAD

**Issue by Natromitus** [callstack/react-native-testing-library#924]
Hey,
I am struggling with `Warning: You called act(async () => ...) without await.`. I have read several blog posts about it but nothing really seems to work for me.

I make changes to the sign in form, then I await conditionally rendered text using **await** findByTestId. I tried other things, like wrapping `fireEvent` in `act` which sometimes helps even though it shouldn't really as `act` is internally in `fireEvent`.
Has anyone encountered similar issue?

**Note:** In some other test cases I was trying to use `waitFor` which didn't work so I instead had to wrap `fireEvent` `act` to make it work.

**Minimal reproduction:** https://github.com/Natromitus/TestNeedHelp

**My test:**
```ts
test.only("Sign in form shows server error", async () => {
    server.use(
        rest.post("url", (req, res, ctx) => {
            return res(
                ctx.status(400)
            );
        }),
    );
    const component = render(<SignInScreen />);
    const usernameInput = await component.findByTestId(tiConfig.SIGN_IN_USERNAME_INPUT);
    const passwordInput = component.getByTestId(tiConfig.SIGN_IN_PASSWORD_INPUT);
    const submit = component.getByTestId(tiConfig.SIGN_IN_SUBMIT);

    // Interacting with Formik form
    fireEvent.changeText(usernameInput, "username");
    fireEvent.changeText(passwordInput, "password");
    fireEvent.press(submit);

    // Getting Warning: You called act(async () => ...) without await. on the line below
    const serverError = await component.findByTestId(tiConfig.SIGN_IN_SERVER_ERROR);
    expect(serverError).not.toBeNull();
    expect(serverError.props.children).toBe(translations.somethingWentWrongTryAgainLater);
});
```

**Comment by pierrezimmermannbam** [comment]
Hey @Natromitus, this issue seems linked to the fact that the react native preset overrides global.Promise. To fix it, you can use instead the @testing-library/react-native preset which restores the original promise. Also it enables the use of modern fake timers which make waitFor timeout otherwise.

**Comment by Natromitus** [comment]
Hey @pierrezimmermannbam,
Thank you for spending your time on this problem. This fixed my issue, thank you!
