### ISSUE TITLE
fireEvent.onPress does not work on TouchableOpacity react-native

### ISSUE THREAD

**Issue by ydhnwb** [callstack/react-native-testing-library#951]
I have a component called Header that look like this:

```
import React from 'react'
import {StyleSheet, TouchableOpacity, View, StyleProp, ViewStyle} from 'react-native'
import {Text} from '..'
import Icon from 'react-native-vector-icons/MaterialIcons'
import {theme} from '@app/presentations/utils/styles'
import {useNavigation} from '@react-navigation/core'

interface IHeaderProps {
  title: string
  headerRight?: () => JSX.Element | false | undefined
  onGoBack?: () => void
  hideBackButton?: boolean
  style?: StyleProp<ViewStyle>
}

const Header: React.FC<IHeaderProps> = props => {
  const navigation = useNavigation()

  const goBack = () => {
    props.onGoBack ? props.onGoBack : navigation.goBack()
  }
  return (
    <View style={[styles.container, props.style]}>
      <View style={styles.leftContent}>
        {props?.hideBackButton ? null : (
          <TouchableOpacity onPress={goBack} testID="headerBackButton">
            <Icon name={'chevron-left'} size={22} color={theme.colors.black} />
          </TouchableOpacity>
        )}
      </View>

      <View style={{flex: 1, flexGrow: 10, alignItems: 'center'}}>
        <Text maxLines={2} style={{paddingHorizontal: 8, textAlign: 'center'}} type="semibold">
          {props.title}
        </Text>
      </View>

      <View style={styles.rightContent}>{props.headerRight && props.headerRight()}</View>
    </View>
  )
}

export default Header
```

Focus on TouchableOpacity, I want to fire the onPress of it using testId, but looks like it won't fire.

```
  it('Should have correct behavior', () => {
    const goBackFn = jest.fn()
    const props: IHeaderProps = {
      title: 'My Header',
      onGoBack: goBackFn,
    }
    const {component, getByTestId, queryAllByText} = renderComponent(props)
    expect(component).toMatchSnapshot()

    expect(queryAllByText('My Header').length).toBe(1)
    expect(getByTestId('headerBackButton')).toBeTruthy()
    fireEvent.press(getByTestId('headerBackButton'))
    expect(goBackFn).toBeCalled()
  })
```

The error message was like this  

[![enter image description here][1]][1]

means that my goBack function never executed. I wondering why.
Then I check the snapshots of my Header component, it is not show TouchableOpacity but it shows View with onClick function on it

```
    <View
      accessible={true}
      collapsable={false}
      focusable={true}
      nativeID="animatedComponent"
      onClick={[Function]}
      onResponderGrant={[Function]}
      onResponderMove={[Function]}
      onResponderRelease={[Function]}
      onResponderTerminate={[Function]}
      onResponderTerminationRequest={[Function]}
      onStartShouldSetResponder={[Function]}
      style={
        Object {
          "opacity": 1,
        }
      }
      testID="headerBackButton"
    >
```

My question is how do I execute onPress on TouchableOpacity ?  
Does my snapshot showing a View isntead of TouchableOpacity affect my problem?
Also different name on snapshots (snapshot use onclick, not onPress) can lead to this problem?

i am using @testing-library/react-native version 9.1.0

  [1]: https://i.stack.imgur.com/lDwyk.png

**Comment by pierrezimmermannbam** [comment]
@ydhnwb it should work but it's hard to tell what's the issue here. If you replace the onPress prop of your touchableopacity by a function that logs something, is there an output in your console ?

Regarding what is displayed in the snapshot, it's normal and it's not an issue there is no onClick handler in the native View that gets rendered in the end because fireEvent uses the result of your query which is a completely different thing from what is in your snapshot. What fireEvent.press does is that if the element it's called with has an onPress prop, it calls it, otherwise it looks for an onPress prop in the parent. 

If you log getByTestId('headerBackButton').props, what is the output ?

Are you sure the onGoBack prop is correctly passed to your component in your test ? What does the function renderComponent do ?

**Comment by ydhnwb** [comment]
Thanks for answer my question, I fixed this. At least there is two problem from my implementation.

1. On the Header component, I forgot to add parenthesis () on props.onGoBack function. It should be props.onGoBack() not props.onGoBack


2. I need to add await waitFor(() => { ...wait for my getTestById to be truthy })


![Screenshot from 2022-04-08 13-41-41](https://user-images.githubusercontent.com/26734262/162601914-f12bd3dc-1f34-4690-a5fa-b412b29d090e.png)
