### ISSUE TITLE
queryByText with newline \n doesn't find matching rendered text

### ISSUE THREAD

**Issue by pke** [callstack/react-native-testing-library#983]
## Describe the bug

New lines, that are rendered in RN as separate Lines, are wrongly normalised during testing.

```tsx
const { queryByText } = render(<Text>Line 1\nLine 2</Text>)
expect(queryByText("Line 1\nLine 2")).toBeDefined()
```

## Expected behavior

I expect the test to pass.
I have checked the queryByText and it seems it uses the same normaliser (Default) as the findTextByNode so this should actually work.

I know that in HTML whitespace is ignored and normalised by browsers to one space. But in RN it actually matters and is rendered (at least \n whitespace).

The test can be made to pass by this change:

```diff
-expect(queryByText("Line 1\nLine 2")).toBeDefined()
+expect(queryByText("Line 1\nLine 2".split("\n").join(" ")).toBeDefined()
```

which indicates to me, the queryByText does in fact not normalises the input query text correctly.

## Versions

 npmPackages:
    @testing-library/react-native: 9.0.0 => 9.0.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-test-renderer: 16.14.0 => 16.14.0

**Comment by pke** [comment]
you mean in this line?

```diff
-? normalizedText === matcher
+? normalizedText === normalizer(matcher)
```

and 

```diff
-: normalizedText.toLowerCase().includes(matcher.toLowerCase());
+: normalizedText.toLowerCase().includes(normalizer(matcher).toLowerCase());
```

Sure I will normalize the matcher before comparing it. PR incoming.

**Comment by pke** [comment]
OK, @mdjastrzebski I have created a fix, but it only fixes this case:

```tsx
const { getByText, queryByText } = render(<Text>{'Line 1\nLine 2'}</Text>);
expect(getByText('Line 1\nLine 2')).toBeTruthy();
expect(queryByText('Line 1\nLine 2')).not.toBeNull();
```

when I don't wrap the text in a string, it does not work:

```tsx
const { getByText, queryByText } = render(<Text>{'Line 1\nLine 2'}</Text>);
expect(getByText('Line 1\nLine 2')).toBeTruthy();
expect(queryByText('Line 1\nLine 2')).not.toBeNull();
```

```
Unable to find an element with text: Line 1
    Line 2

      477 | test('getByText with newlines', () => {
      478 |   const { getByText, queryByText } = render(<Text>Line 1\nLine 2</Text>);
    > 479 |   expect(getByText('Line 1\nLine 2')).toBeTruthy();
          |          ^
      480 |   expect(queryByText('Line 1\nLine 2')).not.toBeNull();
      481 | });
      482 |
```

**Comment by ManuViola77** [comment]
I think I have a similar error. I'm using `getByText` and I have a Text that wraps 2 texts inside that have a different style, like this: 

```
<Text style={generalStyle}>
	  <Text style={oneStyle}>Text 1 </Text>
	  <Text style={anotherStyle}>Text 2</Text>
</Text>
```

Before, when I did this `expect(getByText('Text 1 Text 2')).toBeDefined();` it used to pass and now is failing.
