### ISSUE TITLE
_reactNative.renderHook is not a function

### ISSUE THREAD

**Issue by ggunti** [callstack/react-native-testing-library#990]
## Describe the bug

I get `TypeError: (0 , _reactNative.renderHook) is not a function` error.

## Expected behavior

`renderHook` should be a function and work properly

## Steps to Reproduce

This is what my `Signin.test.js` file contains:
```
import React from 'react';
import { useFormik } from 'formik';
import { render, fireEvent, renderHook } from '@testing-library/react-native';
import Signin from '../../../../src/modules/auth/components/Signin';
import CustomIntlProvider from '../../../__helpers__/CustomIntlProvider';

describe('Signin screen component', () => {
  test('signup function is called when the button is pressed', () => {
    const formik = renderHook(() =>
      useFormik({
        initialValues: { email: '', password: '' },
        onSubmit: jest.fn(),
        validateOnChange: false,
        validateOnBlur: false,
      }),
    );
    const signUp = jest.fn();
    const forgotPassword = jest.fn();
    const { getByText } = render(<Signin formik={formik} signUp={signUp} forgotPassword={forgotPassword} />, {
      wrapper: CustomIntlProvider,
    });
    expect(signUp).toHaveBeenCalledTimes(0);
    fireEvent.press(getByText('btn.signup'));
    expect(signUp).toHaveBeenCalledTimes(1);
  });
});
```

## Screenshots

<img width="566" alt="Captură de ecran din 2022-06-06 la 16 01 30" src="https://user-images.githubusercontent.com/26307699/172165890-649e8b9c-e727-41ee-9098-dee5ae13b883.png">

## Versions

    @testing-library/react-native: ^9.1.0 => 9.1.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-test-renderer: 17.0.2 => 17.0.2

**Comment by AugustinLF** [comment]
The version of RNTL with `renderHook` hasn't be released yet.

**Comment by ginnymin** [comment]
Anyone have any insight on when the next release will be? I'm also waiting on `renderHook`

**Comment by mdjastrzebski** [comment]
@thymikee is there anything blocking the release? Seems like working 'renderHook' would be useful to many people.

**Comment by thymikee** [comment]
There was a breaking change right before this feature and I reverted 9.2.0 which had `renderHook`. I've released v10 now
