### ISSUE TITLE
Create an RNTL example for TypeScript

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#993]
## Describe the Feature
Currently we lack good resource of how to use RNTL with TypeScript. Our current example apps all use JS. Let's create a new example app that will showcase how to properly setup RNTL with TypeScript: minimal setup just for TS, no redux, etc, no fuss. Just the stuff that is required for tests to be written in TS in a way that we consider to be model setup.

## Possible Implementations
1. New `examples/typescript` app.

## Related Issues
#920 - when diagnosing this issue I found that we do not have a good resource for TS setup

**Comment by AugustinLF** [comment]
For whoever, this repo works https://github.com/AugustinLF/repro-rntl

**Comment by mdjastrzebski** [comment]
Closing as done by #1025. The model example RNTL setup integration incl. TypeScript is now available as `examples/basic`.
